### ISSUE TITLE
Preserve the expanded or collapsed status of folders between searches.

### ISSUE THREAD

**Issue by JohnLukeBentley** [aaFn/Bookmark-search-plus-2#6] opened 2018-02-08 11:38 UTC
Ideally the expanded or collapsed status of folders that Bookmark-search-plus-2 reveals when you "Find in tree" after a search would reflect the the open or closed status of folders in the native Bookmark manager, excepting the ancestor folders of the found url.

At the moment, with Bookmark-search-plus-2, all the folders are expanded. That's a problem as with Go Parent Folder I'm used to often finding a bookmark by:
* Searching for a string I'm confident will get a small set of bookmarks near or around the target bookmark (having forget the string of the target bookmark). The target bookmark not necessarily being among them.
* Clicking on a url from the search result.
* Being taken to some part of the tree.
* Having a look around various branches in that part of the tree for my target bookmark, usually successfully.

Having all the folders expanded destroys how I set up the tree in order to navigate it.

If that was convincing but you couldn't (easily) keep in sync with the native bookmark manager then preserving the expanded or collapsed status of folders on an Bookmark-search-plus-2 independent basis might work just as well (especially if you also took care of loading optimization ... there'd be no longer any need to use the native bookmark manager).

**Comment by aaFn** [comment] 2018-02-08 15:59
@JohnLukeBentley indeed there is no way to know or change the status of folders (open or closed) in the native bookmark sidebar. The API does not expose that :-(

So we are left only with an independent status, and this is what it does = if you close the browser with the BSP2 add-on active in the sidebar, the next time you open the browser the add-on will be immediately displayed, and the last status of close/open for each folder (even the open ones hidden under a closed one .. try it :-) ) is retained and will be restored.
Same if you switch to another sidebar, and back to the BSP2 sidebar.
So things are basically retained and displayed the way you left them when quitting BSP2.
Purpose being indeed to replace the native sidebar so that you do not need to use it anymore.

And by contrast, you can leave the "All bookmarks" window open all time besides, make modifications there, they are instantly reflected inside the BSP2 sidebar. Or the reverse, modifications in BSP2 sidebar contents are immediately reflected in the "All bookmarks" window if it is open.

Now, you are correct that so far I chose the option to open all by default from start, or when a new folder is created.
I am starting to believe this was a bad choice:
- I need to have them closed by default to improve the visual rendering effect and display things while loading, basically displaying first what is open, and setting up in background and asynchronously what is hidden (closed).
- for someone like @vitaaliy who has 80000 bookmarks, opening them all from start is just nonsense and not practical
- for someone who only has a few bookmarks, he/she doesn't care that folders are opened or closed at start.

So I'll change for setting folders closed by default on first load, or when new folders are created.

Does the above address the whole of what you seek for, or am I missing something ?

**Comment by JohnLukeBentley** [comment] 2018-02-08 21:54
Yes aiming to wholly (or mostly) replace the native sidebar sounds like the aim to have.

Thanks for teaching me that currently you preserve open/close status of folders:

* Between sidebar switching;
* Between opening and closing the browser when then the BSP2 sidebar was open.

That preservation is also retained:
* Between opening and closing the browser when then the BSP2 sidebar was closed.

So that all looks good.

I agree that, given BSP2 must be independent, the first load default ought be to close all nodes.

> Does the above address the whole of what you seek for, or am I missing something ?

Yes it appears that if I close all nodes, perform a search and "Find in tree", then:

* The target url is found (as desired);
* All the ancestor nodes of the target, including the root ancestor, are opened (as desired);
* But all the child nodes of the root ancestor are opened (as not desired).

Imagine I have two folders like this:

    + Folder Level 0
      - Folder Level 1 - A
      - Folder Level 1 - B

`+` means open
`-` means closed
`(*)` will mean bookmark

After I perform a search  for "capacity" and "Find in tree" I'll end up with:

    + Folder Level 0
      + Folder Level 1 - A
        + Folder Level 2 - A
          (*) How to Prolong Lithium-based Batteries - Battery University
        + Folder Level 2 - B
          (*) Capacity loss and discovering what causes a battery to fade - Battery University
      + Folder Level 1 - B
        + Folder Level 2 - C
          (*) BU-603: How to Calibrate a “Smart” Battery – Battery University

What we should end up with is:

    + Folder Level 0
      + Folder Level 1 - A
        - Folder Level 2 - A
        + Folder Level 2 - B
          (*) Capacity loss and discovering what causes a battery to fade - Battery University
      - Folder Level 1 - B

**Comment by aaFn** [comment] 2018-02-08 22:31
Ok, looks like a bug here .. let me look at it in details ...

**Comment by aaFn** [comment] 2018-02-08 23:40
Ok bug identifed, I made a fix. It was a stupid bug, as always :-)
2.0.3 should correct it. Let me know if you see anything of the same kind remaining when it is out.

**Comment by JohnLukeBentley** [comment] 2018-02-08 23:48
Thanks! Yeah most bugs are stupid. Nevertheless there's a great satisfaction in identify even a stupid bug :)

Indeed, I'll give feedback when 2.0.3 is out.

**Comment by aaFn** [comment] 2018-02-09 00:42
Also making folders closed by default now in 2.0.3, when no info on them (= add-on install, or new folder).

**Comment by aaFn** [comment] 2018-02-10 01:09
Hello @JohnLukeBentley , with 2.0.3 out now and fixing the bug above, plus making folders closed by default at add-on install or when new folders, can we agree to close that issue ?

**Comment by JohnLukeBentley** [comment] 2018-02-12 08:10
That's much better. I've got the collapse-by-default (I reinstalled the add-on). 

However, the tree state is not preserved after a jump from a search to a bookmark in the tree. To reproduce:

1. Load BSP2.
2. Type a string in the search box.
3. Left click one of the search results, outside the icon+text (to effect a "Find in tree" command).
4. The bookmark is correctly found in the tree. Only its ancestor folders are expanded. (This is one of the improvements).
5. Click on X in the search text box. ...

Observe the search pane is closed (as desired) but the tree branch that was opened, where your bookmark was found, wrongly collapses.

**Comment by NicolasWeb** [comment] 2018-02-12 09:05
Hello @aaFn and @JohnLukeBentley  I'm running 2.0.4 and the folders' status are kept & expanded when containing a search result. Everything works right upon sessions.
To me, this bug seems fixed.

**Comment by JohnLukeBentley** [comment] 2018-02-12 09:11
> the folders' status are kept & expanded when containing a search result.

What about when, subsequently, *closing* the search result pane (Step 5)?

**Comment by aaFn** [comment] 2018-02-12 15:31
Yes, this behavior is consistent with the old "Bookmarl Search Plus" = when closing the search box, the tree is restored to its previous state .. except if you modify the state of folders on the path, by clicking on the twisties ..
In fact, more exactly, the tree is restored to the latest state of the twisties, which you can modify while the search session is open.

So if you want a search path which was closed before the search to remain open after search, simply go up in the chain of folders in the bookmark pane, and click on them to make them open (the twisties will change direction to show that ..)

I guess both behaviors are valid, I just chose to respect the old one, and I see its benefit = at least this is not constantly polluting the open state of the tree, which would ask you to come later and re-close ..

**Comment by aaFn** [comment] 2018-02-14 19:05
@JohnLukeBentley, @NicolasWeb, can we close this one = problem fixed, and working as designed.

**Comment by JohnLukeBentley** [comment] 2018-02-15 22:22
@aaFn thanks. The issue is still live ...

> So if you want a search path which was closed before the search to remain open after search, simply go up in the chain of folders in the bookmark pane, and click on them to make them open.

Do you mean I'd need to toggle all the ancestor twisties in order to keep open the currently found bookmark?

I seem able to reproduce that behaviour: I'd suggest that is burdensome.

I think I'm coming from using only the "Go Parent Folder" add-on rather than the old  old "Bookmark Search Plus". So I'm after the  "Go Parent Folder" behaviour.

Perhaps, if there emerge differences of opinion about what ought be done here, you could throw in another options setting. 

To clarify what I'm suggesting ...

Currently this sort of thing will happen:

1.  `Find (or Show) in tree` is executed and the bookmark is found in the tree.
2. The user will either:
   a. Not further change the state of the tree; or
   b. Further change the state of the tree
3.  The user closes the search pane (or closes the side panel, or keeps the side panel open but selects a different tool (e.g History)).

None of that should change but our issue is: what should happen upon close (as in the third step above)? I suggest that the state of the tree just before step 3, immediately prior to any closing, should be preserved. That is, regardless of whether the user does 2a or 2b.

... or there should be an option for this behaviour.

**Comment by aaFn** [comment] 2018-02-15 23:49
Can do with an option .. By default I am concerned with people like @vitaaliy who have lots of bookmarks and folders (this is also my case) = don't want to get the tree opening more and more as we do different searches, and so clicking back on twisties to close things after a search to get a clean view of bookmarks fitting our regular usage is just cumbersome and slowing down the navigation.

So what you describe is so far the intended behavior, where cases when we want to keep the tree open after a search are rarer then resetting it to the initial "default" view .. And since we can work on the tree while the search is active, there's not much trouble in having it reset to its initial view when we close the search = do what we want to do with the tree while the search is active, then reset to "default" when finished = the one which was active before the search.

But as for other things, this is a matter of habits, and the add-on is not here to dictate habits. All the more that it is in fact more or less responding to 3 slightly different needs = "Sidebar Bookmark search Plus", "Show Parent Folder" and "Go Parent Folder" .. as you point out.
Even if that was not my initial intent (hence the name), it is a fact that this is filling those 3 things more or less, and I just have to recognize that.

I guess I can add an option of

`[ ] Leave tree open after a show result in bookmark tree`

default unchecked .. Let me know what could be a more appropriate formulation.

**Comment by JohnLukeBentley** [comment] 2018-02-16 07:04
> But as for other things, this is a matter of habits.

Yes, a matter of contrary habits in different individuals. Also a matter of preferences.

> ... and the add-on is not here to dictate habits.

Yes, that's probably the right approach to take. And the way to accommodate different user habits and preferences does seem through options (as you've already begun to use). Indeed sometimes the "options" screen is called "preferences" :)

> don't want to get the tree opening more and more as we do different searches, and so clicking back on twisties to close things after a search to get a clean view of bookmarks fitting our regular usage is just cumbersome and slowing down the navigation.

Quite apart from the current issue, albeit related, I was thinking of suggesting you add several menu items to the right-click menu in the tree pane:

* Expand all
* Collapse all
* Expand all under current folder
* Collapse all under current folder

They might be useful in their own right. But if they existed closing your tree after a search and show, would become less burdensome.

However, it does seem that, in any case, to accommodate different user preferences on the current issue, the issue of whether to leave the tree in it's current state after a search close, adding an option is the way to go (as you are amenable to).

I'd suggest something like the following instead ...
    
    [ ] After "Show in tree" command, leave tree in current state.

Firstly, we are not necessarily leaving the tree open. If, after a "Show in tree" command, a user closes parts of the tree (or all of the tree), on closing search the state of the tree should not change (when this option is checked). So I'm suggesting "leave tree in current state" rather than "leave tree open".

Secondly, rather than "after a show result" here is an opportunity to help with discoverability. If the search pane right click menu has a menu item with "Show in tree" then it is worth repeating that command in the option. That way whether the user first discovers the menu item or the option, they've learnt a command that then gets name recognition when they encounter it again in another part of your app (the menu item or the option).

Default unchecked is fine.

Implementing this behaviour is potentially a lot of work. So you may want to wait until @NicolasWeb weighs in: @NicolasWeb if there was such an option, would you be ticking it?

**Comment by aaFn** [comment] 2018-02-18 22:55
Hello @JohnLukeBentley , as a matter of fact, the current behavior is already to "leave the tree in current state" when closing search.

Indeed, when showing a bookmark or a folder, all folders on the path to it are unhidden as well as their siblings, but folders state is untouched, showing things even if they are closed.
Then the user can modify their state as he/she wants.
And when closing the search, all things which are unhidden but are under a closed folder will be hidden again, and all things behind an open folder remain visible.
Again, this is in line with the old (S)BSP1 extension, reproducing its behavior.

So the preference we are discussing in is fact to change (force) state to "open" for all folders leading to the result bookmark when showing it, rather than untouched.

Therefore I named the preference accordingly:

`[ ] On "Show bookmark", set state to open for all folders on the path to shown bookmark`

Implemented in 2.0.5.
Let me know if you see a better wording than the above.

**Comment by JohnLukeBentley** [comment] 2018-02-21 05:17
@aaFn. Thanks. With that option ticked, the behaviour looks good.

A clearer wording might be ...

    [ ] After "Show Bookmark" then close search pane: keep bookmark open unless you have closed it.

That wording might have the following advantages:

* It uses plain language by avoiding programming terms. E.g. terms like "state", "node", "ancestor", "user" etc.
* Given that it would be impossible to "keep bookmark open" without also keeping "all ancestor folders" open, talk of ancestors can be eliminated.

There may well be a better wording than I've suggested.

**Comment by aaFn** [comment] 2018-02-21 20:49
Hello @JohnLukeBentley , I see. In that spirit and building on your sentence, what about:

`[ ] On "Show Bookmark", open bookmark to remain visible by default when closing search.`
or
`[ ] After "Show Bookmark", leave bookmark open by default when closing search.`

Trying to shorten sentences while keeping the main idea .. :-)

**Comment by JohnLukeBentley** [comment] 2018-02-22 08:02
> [ ] After "Show Bookmark", leave bookmark open by default when closing search.

Yes I think that is the better wording. :)

**Comment by aaFn** [comment] 2018-02-22 23:11
Ok, let's go with that then, thank you.
Will be in 2.0.6.

**Comment by aaFn** [comment] 2018-02-25 00:04
Close .. and also added an "Open parent(s)" action in context menu of an shown result in bookmark pane, when the preference is not set, to open all parent folders if the row was hidden.

If preference is set, Open parent(s) is done automatically, so it is not shown

**Closed by aaFn** 2018-02-25 00:04 UTC
Labels: bug
