### ISSUE TITLE
Load problem

### ISSUE THREAD

**Issue by orropid** [aaFn/Bookmark-search-plus-2#50] opened 2018-07-12 15:12 UTC
Hi,

I'm a user of the add-on, running Firefox on Win7. Since the last update BSP2 doesn't work for me, it just gives me the "Wait background load.." message that hangs on forever. I've been advised to do a traces activation on the options page, through which I got the following:

PlatformOs: win
Setting Windows variations
Load local store duration: 17 ms

I hope this can be solved. Cheers.

**Comment by aaFn** [comment] 2018-07-12 23:21
Hello @orropid , ok this is useful, this is telling me the front end is missing a ready signal from the background page very early, and also that you are in 2.0.28, where I already cured another bug like that.
So that means there is one more lurking ...

Can I ask you to do the following ?
- Open the browser console = Ctrl + Shit + J
- Clear its contents by clicking on the trash icon on top left
- Go to the add-ons page = Tools -> Add-ons -> Extensions
- Disable BSP2 (click on the Disable button ..)
- Wait 5 seconds to make sure
- Enable BSP2
- Wait 5 seconds and take the contents of the Browser console and paste it here ...

That should tell me where the background task is failing (or not), and what can be happening. We'll see when we see your trace.

By the way, do you happen know how many bookmarks you have roughly ?

Thanks, aaFn.

**Comment by orropid** [comment] 2018-07-14 08:17
Hi,

I have about 5000 bookmarks. And this is what I get from the procedure you described:


Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://play.google.com/log?format=json&authuser=0. (Reason: CORS request did not succeed).
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://play.google.com/log?format=json&authuser=0. (Reason: CORS request did not succeed).
Warning: attempting to write 5219 bytes to preference browser.uiCustomization.state. This is bad for general performance and memory usage. Such an amount of data should rather be written to an external file. This preference will not be sent to any content processes.
Load saved state..

background.js:84:5
Read saved tree info..

background.js:84:5
Read saved tree..

background.js:84:5
Read migration state..

background.js:84:5
structureVersion: -img16-bnlist

background.js:84:5
disableFavicons_option: true

background.js:84:5
Load local store duration: 2224 ms

background.js:84:5
No install event background.js:1470:5
(Bypass FF API) Tree load duration: 34 ms

background.js:84:5
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://play.google.com/log?format=json&u=0&authuser=0. (Reason: CORS request did not succeed).
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://play.google.com/log?format=json&authuser=0. (Reason: CORS request did not succeed).

**Comment by aaFn** [comment] 2018-07-14 17:42
Hello @orropid , thanks much.
I believe, I caught the problem .. you have not been running BSP2 for a while and you have a quite old tree structure saved on disk which is going through a path in the code that I didn't test .. my bad.
And of course falling into a bug :-)

That should be corrected in 2.0.29 which I am deploying now.

Let me know if this is not better. Thanks, aaFn.

**Comment by aaFn** [comment] 2018-07-15 15:03
Cool, closing that issue then.
Thanks, aaFn.

**Closed by aaFn** 2018-07-15 15:03 UTC

**Comment by rocketaz** [comment] 2018-07-18 06:49
Sorry to break this solved issue.
I'm having the same problem as orropid. Currently, I'm running Windows 7 x64, with 7500 bookmarks. 
I've tried to remove the extension and manually delete the bookmarksearchplus2@aafn.org in 'extensions' and 'browser-extension-data'. 
Installed back the extension (BSP2 2.0.29), however it doesn't load at all. I'm also not seeing the "Wait background load.." message.

> Loading failed for the <script> with source “moz-extension://63e2bed0-899d-413c-a907-b16059b24d36/sidebar/libstore.js”. _generated_background_page.html:5
Loading failed for the <script> with source “moz-extension://63e2bed0-899d-413c-a907-b16059b24d36/sidebar/libimage.js”. _generated_background_page.html:6
Loading failed for the <script> with source “moz-extension://63e2bed0-899d-413c-a907-b16059b24d36/sidebar/BookmarkNode.js”. _generated_background_page.html:7
Loading failed for the <script> with source “moz-extension://63e2bed0-899d-413c-a907-b16059b24d36/sidebar/favicon.js”. _generated_background_page.html:8
Loading failed for the <script> with source “moz-extension://63e2bed0-899d-413c-a907-b16059b24d36/sidebar/background.js”. _generated_background_page.html:9
NS_ERROR_NOT_AVAILABLE: Component returned failure code: 0x80040111 (NS_ERROR_NOT_AVAILABLE) [nsIWebNavigation.loadURIWithOptions] browser-child.js:352

**Comment by aaFn** [comment] 2018-07-18 17:22
Hello @rocketaz , looks like your system / Firefox has problems unzipping the XPI file .. but is was validated by AMO, and is working everywhere else, so most probably the problem is on your platform.

First, can you look at the `about:debugging` page and report if there are any messages there for the BSP2 add-on when it is installed ?

I can suggest that experiment:
- Go to the extensions directory in your mozilla profile, copy bookmarksearchplus2@aafn.org.xpi as another file (like select, then ctrl-C and ctrl-V), and add .zip at end of it
- Then try to open it with your system ... does it unpack ? Can you see and open the files in it ?
- In particular, can you find and edit the 5 files mentioned in the error messages = libstore.js, libimage.js, BookmarkNode.js, favicon.js, background.js ?

Another useful experiment would be to install a previous version of BSP2 on FF (https://addons.mozilla.org/en-US/firefox/addon/bookmark-search-plus-2/versions/):
- I would suggest first try with 2.0.26 to be on a version which was before I created those files, to verify if that one is working on your system.
- then try with 2.0.28.

Also, just in case, verify your drive is not full, on the one where your FF profile is installed, and on C:. where your OS is installed.

Out of curiosity, are you using the 32 bits version of FF, or the 64 bits one ?

**Comment by rocketaz** [comment] 2018-07-19 08:08
Troubleshoot #1
In about:debugging, there is no 'Reading manifest: Error processing' error on BSP2.

Troubleshoot #2
I can unpack the .xpi file. And, I can see and edit all the 5 files in it.

Troubleshoot #3
Installed a previous version of BSP2. I first installed the version 2.0.26 then later upgrade to version 2.0.28, both version loaded and search for bookmarks just fine. Finally, upgraded to 2.0.29 the next day, it still is working fine too!
Problem solved! I'm on FF 61.0.1 x64

aaFn, thanks for your support! Appreciate your time on this.

**Comment by aaFn** [comment] 2018-07-19 09:50
Ok, good, thank you. So probably there was a glitch when 2.0.29 was loaded first time, and it was in FF cache so when you were reinstalling it with same version, the problem was a solid one. Then by installing 2.0.26 this cleared the cache from the bad download and replaced by a new file, and later upgraded proceeded to a re-download .. and all is back to normal.
Thank you for reaching out.

**Comment by foxxy1223** [comment] 2022-03-01 04:24
I've been having this issue for a few days now on my desktop. Now I'm lost when it comes to technical problems so please make it really easy for me to understand. lo I did the steps in the 2nd post, so I hope I did this right.
23:25:21.441 Load saved state..

background.js:129:10
23:25:21.485 IndexedDB UnknownErr: ActorsParent.cpp:543
23:25:21.486 libstore error on loading from local storage 3 : Error: An unexpected error occurred (retries left: 9) libstore.js:1335:13
23:25:21.486 fileName:   undefined libstore.js:1339:14
23:25:21.486 lineNumber: 0 libstore.js:1340:14
23:25:21.499 IndexedDB UnknownErr: ActorsParent.cpp:543
23:25:21.499 libstore error on loading from local storage 3 : Error: An unexpected error occurred (retries left: 8) libstore.js:1335:13
23:25:21.499 fileName:   undefined libstore.js:1339:14
23:25:21.500 lineNumber: 0 libstore.js:1340:14
23:25:21.507 IndexedDB UnknownErr: ActorsParent.cpp:543
23:25:21.508 libstore error on loading from local storage 3 : Error: An unexpected error occurred (retries left: 7) libstore.js:1335:13
23:25:21.509 fileName:   undefined libstore.js:1339:14
23:25:21.509 lineNumber: 0 libstore.js:1340:14
23:25:21.516 IndexedDB UnknownErr: ActorsParent.cpp:543
23:25:21.516 libstore error on loading from local storage 3 : Error: An unexpected error occurred (retries left: 6) libstore.js:1335:13
23:25:21.516 fileName:   undefined libstore.js:1339:14
23:25:21.516 lineNumber: 0 libstore.js:1340:14
23:25:21.520 UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. ExtensionStorageIDB.jsm:824
23:25:21.520 Content Security Policy: The page’s settings blocked the loading of a resource at eval (“script-src”). moz-extension:1344:15
23:25:21.520 uncaught exception: null
23:25:21.523 IndexedDB UnknownErr: ActorsParent.cpp:543
23:25:21.524 libstore error on loading from local storage 3 : Error: An unexpected error occurred (retries left: 5) libstore.js:1335:13
23:25:21.524 fileName:   undefined libstore.js:1339:14
23:25:21.524 lineNumber: 0 libstore.js:1340:14
23:25:21.534 UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. ExtensionStorageIDB.jsm:824
23:25:21.534 Content Security Policy: The page’s settings blocked the loading of a resource at eval (“script-src”). moz-extension:1344:15
23:25:21.534 uncaught exception: null
23:25:21.535 IndexedDB UnknownErr: ActorsParent.cpp:543
23:25:21.535 UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. ExtensionStorageIDB.jsm:824
23:25:21.535 Content Security Policy: The page’s settings blocked the loading of a resource at eval (“script-src”). moz-extension:1344:15
23:25:21.535 uncaught exception: null
23:25:21.535 libstore error on loading from local storage 3 : Error: An unexpected error occurred (retries left: 4) libstore.js:1335:13
23:25:21.535 fileName:   undefined libstore.js:1339:14
23:25:21.535 lineNumber: 0 libstore.js:1340:14
23:25:21.536 UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. ExtensionStorageIDB.jsm:824
23:25:21.536 Content Security Policy: The page’s settings blocked the loading of a resource at eval (“script-src”). moz-extension:1344:15
23:25:21.536 uncaught exception: null
23:25:21.541 UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. ExtensionStorageIDB.jsm:824
23:25:21.541 Content Security Policy: The page’s settings blocked the loading of a resource at eval (“script-src”). moz-extension:1344:15
23:25:21.541 uncaught exception: null
23:25:21.543 IndexedDB UnknownErr: ActorsParent.cpp:543
23:25:21.544 libstore error on loading from local storage 3 : Error: An unexpected error occurred (retries left: 3) libstore.js:1335:13
23:25:21.544 fileName:   undefined libstore.js:1339:14
23:25:21.544 lineNumber: 0 libstore.js:1340:14
23:25:21.548 UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. ExtensionStorageIDB.jsm:824
23:25:21.548 Content Security Policy: The page’s settings blocked the loading of a resource at eval (“script-src”). moz-extension:1344:15
23:25:21.548 uncaught exception: null
23:25:21.551 IndexedDB UnknownErr: ActorsParent.cpp:543
23:25:21.551 UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. ExtensionStorageIDB.jsm:824
23:25:21.551 Content Security Policy: The page’s settings blocked the loading of a resource at eval (“script-src”). moz-extension:1344:15
23:25:21.551 uncaught exception: null
23:25:21.551 libstore error on loading from local storage 3 : Error: An unexpected error occurred (retries left: 2) libstore.js:1335:13
23:25:21.551 fileName:   undefined libstore.js:1339:14
23:25:21.551 lineNumber: 0 libstore.js:1340:14
23:25:21.563 UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. ExtensionStorageIDB.jsm:824
23:25:21.563 Content Security Policy: The page’s settings blocked the loading of a resource at eval (“script-src”). moz-extension:1344:15
23:25:21.563 uncaught exception: null
23:25:21.564 IndexedDB UnknownErr: ActorsParent.cpp:543
23:25:21.564 libstore error on loading from local storage 3 : Error: An unexpected error occurred (retries left: 1) libstore.js:1335:13
23:25:21.565 fileName:   undefined libstore.js:1339:14
23:25:21.565 lineNumber: 0 libstore.js:1340:14
23:25:21.572 IndexedDB UnknownErr: ActorsParent.cpp:543
23:25:21.572 libstore error on loading from local storage 3 : Error: An unexpected error occurred (retries left: 0) libstore.js:1335:13
23:25:21.572 fileName:   undefined libstore.js:1339:14
23:25:21.572 lineNumber: 0 libstore.js:1340:14
23:25:21.573 Error on loading from local storage : undefined background.js:3068:10
23:25:21.578 UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. ExtensionStorageIDB.jsm:824
23:25:21.578 Content Security Policy: The page’s settings blocked the loading of a resource at eval (“script-src”). moz-extension:1344:15
23:25:21.578 uncaught exception: null
23:25:21.580 UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. ExtensionStorageIDB.jsm:824
23:25:21.580 uncaught exception: null
23:25:21.638 ExtensionPreferencesManager API ftpProtocolEnabled created but addSetting was not called.

**Comment by aaFn** [comment] 2022-03-01 09:11
Hello @foxxy1223 , looks like local storage got corrupted by FF (sorry, this is independent from BSP2, and BSP2 cannot know about it).
See https://github.com/aaFn/Bookmark-search-plus-2/issues/216 if that can solve your problem.
