### ISSUE TITLE
BSP takes forever to do the background load, unusable.

### ISSUE THREAD

**Issue by sdean7855** [aaFn/Bookmark-search-plus-2#197] opened 2021-08-28 00:41 UTC
I actually have no idea how long it takes to chew through my massive set of bookmarks....just sits there with Wait Background Load.
Am I doing something wrong?  Is there a way to preserve the load so I don't have the interminable wait every time I cold boot the system?

**Comment by Gitoffthelawn** [comment] 2021-08-28 02:03
How many bookmarks do you have?  Also, is your device reasonably fast (a processor no more than 10 years old) with no other processes bogging it down?

**Comment by aaFn** [comment] 2021-08-28 06:56
Hello @sdean7855 , in addition to the questions of @Gitoffthelawn :
- Open the browser console (Ctrll+Shift+J)
- Click on the parameter wheel at top right, and enable content messages if not already done
- Do you see any failure message related to BSP2 ? (usually panel.js or background.js)

Then:
- Click on the tray icon at top left to clean the browser console content
- Open a new tab and type the URL `about:addons`  in the address bar
- Use the sliding button to disable and then re-enable BSP2 (that will stop it, and restart it entirely)
- Paste here in this thread the messages that you see appearing in the browser console

That should help understand what is going on ..
Additionally = which kind of OS are you on, and which version of FF ?

**Comment by ocumo** [comment] 2021-09-07 19:10
**I have the same problem.**  It's impossible to get BSP2 to go beyond the "Wait background load..." message.

System:  Linux Ubuntu 20.04
Firefox version: 91.0.2 (64-bit)

@aaFn:  
> 
    - Click on the tray icon at top left to clean the browser console content
    - Open a new tab and type the URL about:addons in the address bar
    - Use the sliding button to disable and then re-enable BSP2 (that will stop it, and restart it entirely)
    - Paste here in this thread the messages that you see appearing in the browser console

Having done those steps, I have pasted (_below_, at the bottom) what the browser console printed.  But before that, note that I had the following preferences:  "Favicon fetching" **Active**, and "Disable favicon fetching" **unchecked**.

So for troubleshooting, I did the following:
1. Disable and enable the extension.  No changes, same problem.
2. Changed the preferences  "Favicon fetching" to **Pause**, and "Disable favicon fetching" to **checked**. No changes, same problem. Disabled and enabled the extension, and no changes, same problem.

And then, afterwards, I noticed that the preferences are again back to the default "Favicon fetching" **Active**, and "Disable favicon fetching" **unchecked**, although I had changed them.  So for whatever reason the changes were not applied.  I guess that is related to the local storage error messages and troubles writting to it.

In addition, there is a strange thing in the preferences page, that I would like to know if that is expected; even after refreshing, it always shows this:
![image](https://user-images.githubusercontent.com/10180992/132397368-0c217a28-4cd0-471b-925a-5d1a017df45b.png)

That doesn't look OK to me... comments?

Now, here are the console logs:

<details>
  <summary>
    <strong>Console Logs [click to unfold]</strong>
  </summary>
<quote>

    XHRGEThttps://github.com/users/aaFn/hovercard?subject=issue:981680348&current_path=/aaFn/Bookmark-search-plus-2/issues/197
    [HTTP/2 502 Bad Gateway 10471ms]

    Warning: attempting to write 7169 bytes to preference browser.uiCustomization.state. This is bad for general performance and memory usage. Such an amount of data should rather be written to an external file. This preference will not be sent to any content processes.
    Load saved state..

    background.js:129:13
    IndexedDB UnknownErr: ActorsParent.cpp:554
    libstore error on loading from local storage 3 : Error: An unexpected error occurred (retries left: 9) libstore.js:1317:13
    fileName:   undefined libstore.js:1321:14
    lineNumber: 0 libstore.js:1322:14
    IndexedDB UnknownErr: ActorsParent.cpp:554
    libstore error on loading from local storage 3 : Error: An unexpected error occurred (retries left: 8) libstore.js:1317:13
    fileName:   undefined libstore.js:1321:14
    lineNumber: 0 libstore.js:1322:14
    IndexedDB UnknownErr: ActorsParent.cpp:554
    libstore error on loading from local storage 3 : Error: An unexpected error occurred (retries left: 7) libstore.js:1317:13
    fileName:   undefined libstore.js:1321:14
    lineNumber: 0 libstore.js:1322:14
    IndexedDB UnknownErr: ActorsParent.cpp:554
    libstore error on loading from local storage 3 : Error: An unexpected error occurred (retries left: 6) libstore.js:1317:13
    fileName:   undefined libstore.js:1321:14
    lineNumber: 0 libstore.js:1322:14
    UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. ExtensionStorageIDB.jsm:831
    Content Security Policy: The page’s settings blocked the loading of a resource at eval (“script-src”). moz-extension:1326:15
    uncaught exception: null
    UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. ExtensionStorageIDB.jsm:831
    Content Security Policy: The page’s settings blocked the loading of a resource at eval (“script-src”). moz-extension:1326:15
    uncaught exception: null
    UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. ExtensionStorageIDB.jsm:831
    Content Security Policy: The page’s settings blocked the loading of a resource at eval (“script-src”). moz-extension:1326:15
    uncaught exception: null
    IndexedDB UnknownErr: ActorsParent.cpp:554
    libstore error on loading from local storage 3 : Error: An unexpected error occurred (retries left: 5) libstore.js:1317:13
    fileName:   undefined libstore.js:1321:14
    lineNumber: 0 libstore.js:1322:14
    IndexedDB UnknownErr: ActorsParent.cpp:554
    libstore error on loading from local storage 3 : Error: An unexpected error occurred (retries left: 4) libstore.js:1317:13
    fileName:   undefined libstore.js:1321:14
    lineNumber: 0 libstore.js:1322:14
    IndexedDB UnknownErr: ActorsParent.cpp:554
    libstore error on loading from local storage 3 : Error: An unexpected error occurred (retries left: 3) libstore.js:1317:13
    fileName:   undefined libstore.js:1321:14
    lineNumber: 0 libstore.js:1322:14
    IndexedDB UnknownErr: ActorsParent.cpp:554
    libstore error on loading from local storage 3 : Error: An unexpected error occurred (retries left: 2) libstore.js:1317:13
    fileName:   undefined libstore.js:1321:14
    lineNumber: 0 libstore.js:1322:14
    IndexedDB UnknownErr: ActorsParent.cpp:554
    libstore error on loading from local storage 3 : Error: An unexpected error occurred (retries left: 1) libstore.js:1317:13
    fileName:   undefined libstore.js:1321:14
    lineNumber: 0 libstore.js:1322:14
    UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. ExtensionStorageIDB.jsm:831
    Content Security Policy: The page’s settings blocked the loading of a resource at eval (“script-src”). moz-extension:1326:15
    uncaught exception: null
    UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. ExtensionStorageIDB.jsm:831
    Content Security Policy: The page’s settings blocked the loading of a resource at eval (“script-src”). moz-extension:1326:15
    uncaught exception: null
    UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. ExtensionStorageIDB.jsm:831
    Content Security Policy: The page’s settings blocked the loading of a resource at eval (“script-src”). moz-extension:1326:15
    uncaught exception: null
    UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. ExtensionStorageIDB.jsm:831
    Content Security Policy: The page’s settings blocked the loading of a resource at eval (“script-src”). moz-extension:1326:15
    uncaught exception: null
    UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. ExtensionStorageIDB.jsm:831
    Content Security Policy: The page’s settings blocked the loading of a resource at eval (“script-src”). moz-extension:1326:15
    uncaught exception: null
    IndexedDB UnknownErr: ActorsParent.cpp:554
    UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. ExtensionStorageIDB.jsm:831
    Content Security Policy: The page’s settings blocked the loading of a resource at eval (“script-src”). moz-extension:1326:15
    uncaught exception: null
    libstore error on loading from local storage 3 : Error: An unexpected error occurred (retries left: 0) libstore.js:1317:13
    fileName:   undefined libstore.js:1321:14
    lineNumber: 0 libstore.js:1322:14
    Error on loading from local storage : undefined background.js:2998:10
    UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. ExtensionStorageIDB.jsm:831
    uncaught exception: null
    ExtensionPreferencesManager API ftpProtocolEnabled created but addSetting was not called.
    XHRGEThttps://github.com/users/aaFn/hovercard?subject=issue:981680348&current_path=/aaFn/Bookmark-search-plus-2/issues/197
    [HTTP/2 502 Bad Gateway 18ms]

</quote>

**Comment by aaFn** [comment] 2021-09-07 20:11
Hello @ocumo , bad news, looks like the local store is corrupted. Nothing that BSP2 can do anything about, or even know about .. this is completely hidden from add-on visibility.
I guess one way to confirm would be to start the developer tools and look at local store content for BSP2, but anyway there would be nothing that can be done to recover.

You could try a "Reload from FF API" in the options page, but I am afraid that if the corruption is spread on the DB space for BSP2, that does not get rid of it.

The safest way should be:
- uninstall BSP2
- exit Firefox
- restart Firefox
- reinstall BSP2

That procedure completly wipes out the DB space used for local storage of uninstalled add-on (work for all add-ons that you would uninstall), and BSP2 will restart with a fresh (and empty) local storage -> that should get rid of all these messages + load failures, and all should be fine again (or the problem is deeper ... but let's see).

Note: NaN above is normal, as it results from the division of 0 by 0 (cf. 0 bookmarks ....)

**Comment by ocumo** [comment] 2021-09-07 23:09
**Thanks @aaFn !**
I did as you suggested, and now **the fresh installation of BSP2 is working as expected**.

I was indeed strongly suspecting the very same thing, but in the interest of documenting all this, I decided to post the case details, resisting the temptation to just remove the extension and reinstall it without asking here.  It would have fixed my problem, and saved me the hassle of posting here, but it was worth it, so now there is a bit of documentation that might help others.

Perhaps my case is similar to @sdean7855 (the OP) case.  I also have a huge number of bookmarks, as he does.  I hope this helps him too.

Thanks for a nice and well done extension!

**Comment by Gitoffthelawn** [comment] 2021-09-08 02:10
@ocumo Glad things are working for you.  Do you have sync enabled in Firefox?  If so, @aaFn will be able to tell you whether or not you need to clear the sync database as well.  It can (unfortunately) store some extension data even after an extension is uninstalled, but I'm not sure if this extension stores any data using that mechanism (so extensions do... some don't).

IIRC, Firefox even does this if sync is *not* enabled, but when sync is not enabled, the data only goes 1-way (into the sync database).

I've been trying to get Mozilla to fix that issue for years.

**Comment by aaFn** [comment] 2021-09-08 07:03
@ocumo , great, and thank you for doing so, as you say that will serve others 👍 
I am just not sure what is causing such corruptions. From the number of cases that get reported to me, this is very rare .. maybe a bad shutdown or kill of FF in some cases.

To answer the point of @Gitoffthelawn , BSP2 does not use sync storage (consciously at least), so all should be ok.

**Comment by Gitoffthelawn** [comment] 2021-09-08 11:05
@ocumo Do you have a realtime antivirus/antimalware running on that box?  I've often wondered if that ever is the cause of Firefox storage corruptions.

As @aaFn mentioned, those corruptions are very rare (especially in recent years), but they are reported to happen once in a great while.  Last one happened to me about a couple years ago... I no longer remember which profile database got corrupted, but I remember having to replace it from a backup.

**Comment by ocumo** [comment] 2021-09-08 22:42
Thank you guys for your interesting comments and pertinent questions.

@Gitoffthelawn 
` Do you have sync enabled in Firefox? ...  Firefox even does this if sync is not enabled ...`
No, I don't use sync. But it is very interesting what you explain. I wouldn't know what might have caused the corruption, unless as suggested by @aaFn, "a bad shutdown or kill FF", which happens to anyone once in a while for any number of reasons.

`Do you have a realtime antivirus/antimalware running on that box?`
Interesting question, but no, like many other Linux users (I admit, rather risky/not-so-clever behavior, nowadays).
I wonder what else (e.g. what other database) might have been affected too, by whatever it is that broke this one. So far all else looks normal, but I'll keep an eye on other possible issues within FF.   In fact, now I know this very simple procedure (previous post), which can help me in troubleshooting this or any other extension.  :smiley: 

@aaFn 
It is good to know that this is a rare case.  For me, it's also new.  In fact, in my other computers (also on Linux), this extension keeps working fine.  I only very seldom would use Windows, to the point that I don't even remember whether I have the extension installed in FF there!

Once again, thanks a lot for very valuable comments and information.

**Comment by Gitoffthelawn** [comment] 2021-09-09 04:56
> Thank you guys for your interesting comments and pertinent questions.

You are most welcome.

> No, I don't use sync. But it is very interesting what you explain. I wouldn't know what might have caused the corruption, unless as suggested by @aaFn, "a bad shutdown or kill FF", which happens to anyone once in a while for any number of reasons.

Yes, they seem to be rare but do happen once in a great while.  I have the system set play a little sound file when I load Firefox, and other one when I close it.  Each sound is about 5-7 seconds long, and I use the opportunities to take my hands off the keyboard and take a few nice deep calming breaths.  It relaxes me and ensures that no new non-scheduled tasks are run during those critical times.  I've been doing that for over a year, and have not experienced any issues with Firefox since implementing that practice.  Plus, it feels good.

> Interesting question, but no, like many other Linux users (I admit, rather risky/not-so-clever behavior, nowadays).
> I wonder what else (e.g. what other database) might have been affected too, by whatever it is that broke this one. So far all else looks normal, but I'll keep an eye on other possible issues within FF. In fact, now I know this very simple procedure (previous post), which can help me in troubleshooting this or any other extension. smiley

Another important database is the bookmarks database (there's also the associated favicons database, but it's not nearly as important).  In Firefox, if you go to `about:support#verify-place-integrity-button` (you may have to go to it twice... you'll see what I mean when you try it... some sort of anchors bug on `about` pages), you'll see a button entitled `Verify Integrity`.  I recommend clicking on that button every so often.  I do it at least once a week.  I vacuums (that's the technical SQL term) the database and cleans up loose ends.  It also will resolve any easily resolvable errors in the bookmarks database.

> EDIT: Oh, of course I cannot rule out some other extension(s). Ever more frequently, I spot a lot of background activity with which I am not at all happy. Extensions which generate a lot of errors in the console, like WorldBrain's Memex, to name one that I had to remove to get rid of that (wouldn't look like corrupted database, looks more like buggy code to me). Others, like e.g. Ghostery, which since some time is logging a huge amount of activity (Cliqz), which I don't understand how to avoid it other than perhaps removing it completely.

Yes, extension conflicts can be challenging to resolve.  Web browsers still don't have a clear way to establish OOP (Order Of Operation) or priorities amongst extensions.  I'm hopeful the developers for all the different browsers work on this over time.

Regarding Ghostery in particular, I used it long ago, but haven't used it for years.  It had some sort of controversy, of which I don't recall the details.  I found, at least for the functionality I wanted, I was better off using other extensions.  I haven't looked at it in a long while, but I'm guessing all/most of its functionality is available from other extensions or now built-in to Firefox itself.

BTW, regarding database corruption, the potential of this was my biggest concern regarding using BSP2.  @aaFn and I had some good conversations on this topic and @aaFn's helpful explanations were sufficient to allow me to comfortably start using BSP2 without worry.

After a period of using BSP2, I'm actually not using it right now, but I'm planning on installing it again in the very near future... perhaps even in the next few days. 😃

**Comment by ocumo** [comment] 2021-09-10 18:47
Woah!, lots of good stuff in there, @Gitoffthelawn ... :fist_left:

I didn't know about the `Verify Integrity` for the bookmarks DB.  That's an important feature and a great advice.  For a huge bookmarks DB, like mine, it certainly makes all sense to use it as you recommend.

![image](https://user-images.githubusercontent.com/10180992/132901806-f0f0c33e-9146-483a-9487-bd29f9d79dd3.png)

[_Indeed, it was necessary to refresh the page to get to the anchor, as you warned_.]

It's clear that Mozilla provides that feature for a good reason: if all DB vacuuming would just be fully automatically done by FF and never a concern for the users, then this wouldn't be there in the first place. So that's a great tool, though it's a pity that being an advanced feature it's in a rather obscure place for most users at least.  (Well hey, it would be impossible to make all useful things visible at the same time, so I wouldn't have a better idea either.)

All in all, it certainly would make a lot of sense for users of extensions like BSP2, to get to know this little tool in case of abnormal situations :fearful: , or even better, to stay out of troubles, in the first place ... :open_umbrella: 

Thanks !

**Comment by aaFn** [comment] 2021-09-10 21:28
Interesting indeed ! 👍 
Note: pressing the button doesn't free anything in the db for me, pre-vacuum size is the same as post-vacum = 15360 KiB

**Comment by Gitoffthelawn** [comment] 2021-09-11 11:11
@ocumo  
> Woah!, lots of good stuff in there, @Gitoffthelawn ... 

Glad to help.  It feels good to share knowledge and experience... especially for something fairly esoteric, but useful and important, like this.

@aaFn  
> Interesting indeed ! +1
> Note: pressing the button doesn't free anything in the db for me, pre-vacuum size is the same as post-vacuum = 15360 KiB

Yes, the size will sometimes change and sometimes not, depending on the type of cleanup the DB requires.  Even when the size does not change, you can go into a SQLite browser or editor (on Windows, I recommend [DB Browser for SQLite portable](https://portableapps.com/apps/development/sqlite_database_browser_portable)) and see all the changes made.

Over the years, by doing this, I've found a few bugs in the bookmarks DB and reported them to Mozilla.  They have now fixed all those big bugs.  There are still a few minor bugs, but I've never experienced any data loss from any of them.  There's one that can cause tags to get converted to lowercase, but it the big picture, that's not a big deal.

BTW, in addition to making SQLite-format bookmark backups, backing up all your bookmarks as both JSON and HTML isn't a bad idea.  It's not fast if you have many bookmarks, so just brew some tea and be patient. :)

As an aside, @aaFn, if you have any interest in developing an extension that will essentially allow 2 sets of bookmarks within a Firefox profile, I am interested in that functionality.  My use case is that I have a few thousand bookmarks that I use regularly, and I want only them to appear in the address bar's dropdown list.  But I also have tens of thousands of saved links that are for occasional reference that I don't want to appear in that list.  They are almost all detailed articles I have saved that maybe I'll reference once every year or two.  Currently, I keep most of them in a text file because I like to be able to quickly find my more commonly used bookmarks in the address bar's dropdown list.  But keeping them in a text file makes both search & maintenance more work and time-consuming.

It's also possible BSP2 could be tweaked to allow this functionality.  On the exterior UI level, it might just require a single checkbox.

**Comment by Gitoffthelawn** [comment] 2021-09-11 11:13
LOL... I've probably written more just in this thread than I've written on GitHub all month.  When people are appreciative and nice, my motivation to help really increases. :)

**Comment by ocumo** [comment] 2021-09-11 16:57
@Gitoffthelawn 
> ...extension that will essentially allow 2 sets of bookmarks within a Firefox profile

:+1: 
I would encorage you to create a separate Feature Request thread, for which I would absolutely vote positively -- unless, of course, @aaFn would have a different opinion, which I would respect.

I have always wished for some kind of a way to "partitioning" or "subsetting" bookmarks pretty much the way you describe. Should that be somehow feasible, a dreamable 2.0 feature would be one in which one can actually have more than two "partitions" or "subsets", a better, more efficient abstraction of what most of us have to do with either trivial "folders" or FF profiles, which are too much hassle when the only need is to split bookmarks, or other convoluted ways of dealing with lots of bookmarks _locally_ (I don't like cloud based "solutions", sorry, thanks but no thanks :wink: ).

**Comment by aaFn** [comment] 2021-10-05 20:59
Out of curiosity, I looked a bit at the question, but:
- I found no way to partition bookmarks in FF .. the only way would be to delete the part(s) we do not want to appear => nothing I want BSP2 to do of course !
- There is a small API called omnibox (https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Browser_support_for_JavaScript_APIs#omnibox) which allows to interact a bit with the address bar, but it is too limited to do something approaching the above.

As for a "tweak" in BSP2, I believe the closest to what you want is in fact #54. I am keeping that as a future todo.

**Comment by aaFn** [comment] 2021-10-05 21:01
For now, I am closing this issue as @ocumo 's iniitial problem is cured, and we didn't hear back from @sdean7855 .
Reopen if needed, thanks aaFn.

**Closed by aaFn** 2021-10-05 21:01 UTC

**Comment by sdean7855** [comment] 2021-10-05 22:07
Works fine now, thanks!!!
    
    On 10/5/2021 5:02 PM, aaFn wrote:
    
    
      
      For now, I am closing this issue as @ocumo
        's iniitial problem is cured, and we didn't hear back from @sdean7855
        .
        Reopen if needed, thanks aaFn.
      —
        You are receiving this because you were mentioned.
        Reply to this email directly, view it on GitHub, or unsubscribe.
        Triage notifications on the go with GitHub Mobile for iOS or Android.
        
      [
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/aaFn/Bookmark-search-plus-2/issues/197#issuecomment-934829364",
"url": "https://github.com/aaFn/Bookmark-search-plus-2/issues/197#issuecomment-934829364",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
    
    
    -- 
      
      -- 
      "..in our direst need, the smallest gifts:
      the nail of the horseshoe, the pin of the axle,
      the feather at the pivot point, the pebble at the mountain's peak,
      the kiss in despair, the one right word. In darkness,
      understanding."
      Dy Cabon's Prayer
      Lois McMaster Bujold, Paladin of Souls
      
      //Stewart Dean
      sdean @ sdean.net, 845 - 336 - 4815, Kingston, NY
