### ISSUE TITLE
Make 'leave bookmark tree open after closing search' enabled by default

### ISSUE THREAD

**Issue by keunes** [aaFn/Bookmark-search-plus-2#110] opened 2019-07-15 19:55 UTC
Using ttps://github.com/cadeyrn/keep-or-delete-bookmarks I identify some of my many bookmarks that should be deleted. I just ran into a bookmark of which (almost) the whole folder should be deleted. And so I looked for the folder in BSP2, and clicked on the search result of the folder, putting focus on the wanted folder. I click then on the cross in the search field to create vertical space to follow up (delete most of the bookmarks in it).
The expected behaviour would be to close the search results pane and keep focus on the selected folder as is. What currently happens, though, is that current focus is taken away, and if I'm not mistaken the parent folder (of the folder I found) even re-collapses.

**Comment by aaFn** [comment] 2019-07-15 22:35
Hello @keunes, yes this is the intended default behavior, clearing the search field restore the previous state of open/closed folders before the search, unless you manually decide to change their open / closed by acting on their twisties.

That can be changed by activating the option `After "Show Bookmark", leave bookmark tree open by default when closing search pane`

Let me know if I am missing your question.

**Comment by keunes** [comment] 2019-07-18 20:11
That's it! Many thanks :)
To be honest, I would suggest to enable this by default.

**Comment by aaFn** [comment] 2019-07-18 21:37
Well the current default is the behavior in the original Bookmark Search Plus extension by alice0775, so I kept it, so that its users can retrieve the same functions.

**Comment by aaFn** [comment] 2019-08-13 19:30
Closing as it is easy to change on the options, and this is by design fitting the initial BSP extension.

**Closed by aaFn** 2019-08-13 19:30 UTC
Labels: wontfix

**Comment by keunes** [comment] 2019-08-19 18:55
Easy to change... if you're aware of this setting ;)

I understand you want some consistency with Bookmark Search Plus, but it's not disruptive for existing users and I think it'd actually be more intuitive for new users (like me). IMHO You may be proud to be the maintainer of this successor and feel free to make any changes that further develop  alice0775's work :)
