### ISSUE TITLE
The path of in search results selected bookmark is not displayed anymore!

### ISSUE THREAD

**Issue by elgreko2** [aaFn/Bookmark-search-plus-2#260] opened 2022-11-11 18:53 UTC
Hey aaFn,

Long time no see,

Hope youre doing well.

However, not sure if it is good to see you still on that s(t)inking shi* called Firefox.

Anyway, as the title say, when changing to BSP2: "Wait background load.." never finishes.

Also, much more important, since last FF update, **the path of in search results selected bookmark is not displayed anymore**, and that was the only BSP2 thing I was using and single most important feature of BSP2!?

Any chance in fixing those?

Best regards

Just looked it up - currently I have 119003 bookmarks, which should be a world record ;)

Sorry for all the edits, I corrected some errors.

**Comment by aaFn** [comment] 2022-11-12 14:19
Hello @elgreko2 , what do you mean by "the path of in search results selected bookmark is not displayed anymore" ?
Do you mean that clicking on a result in the result pane doesn't show anymore the corresponding bookmark in the main pane ?
Or are you referring to the option "On mouse hover above search result, show path to bookmark item instead of title + url" ?

On my side, both work well (I am on FF 106.0.5, Windows).

**Comment by elgreko2** [comment] 2022-11-12 16:52
Believe it or not, I was using only that fn of BSP2 and couldnt remember its name - it was "Bookmark path" in context menu.

It disappeared after last (or the one before that) FF update.
After reading your msg I went to BSP2 options and enabled that "On mouse hover..." - it also wouldnt work. Also noticed stats showed zeroes.

Uninstalled and installed BSP2 and it now works fine - Bookmark path, On mouse hover, stats.

As for stats, why could they be off - in "Restore" option it shows I have 119042, and BSP2 stats show 114293?

Also, when do you plan stopping developing BSP2? You know, those "programmers" at Mozilla are driving FF to the ground, its only a matter of time... If it wasnt for your work, I would have stopped using this browsing garbage long ago.

**Comment by aaFn** [comment] 2022-11-13 10:43
Hi @elgreko2 , it look like the local storage was corrupted if it was showing 0 ..
You could have tried to "Reload from FF API", as first step, but if local storage was corrupted as I suspect from your description, then the only way that I know to recover is what you did, which is to uninstall and reinstall.

On stats, do not forget to add bookmarks + folders + separtors in BSP2 stats before you compare with FF stats.
If there is still a delta, that means something is wrong in the FF bookmark DB .. or mind also that tags are stored as bookmarks (I absolutely do not understand the FF logic of that ...), and that can also create a delta - but add-ons cannot get access to tags, so BSP2 does not see them.

I do NOT plan to stop developing BSP2, I use it myself daily at home and at work, I would die if I didn't have it 😁 
If FF ever becomes too crippled, I will switch to google chrome and port BSP2 to it .. but I am not a big fan of google in general, so for now I always avoided it. We'll see in future ..

Anyway, happy that you enjoy BSP2, and that you recovered all functions.
Thank you, aaFn.

**Comment by elgreko2** [comment] 2022-11-15 14:37
Well, we should have known better - "fix" lasted only 2 days.

Uninstall, restart FF, install again - bravo Mozilla programmers!

**Comment by elgreko2** [comment] 2022-11-17 15:27
Just 2 days later, a minute ago, I went from Bookmarks to BSP2 (remember I am not using BSP2 at all save for that Bookmark path option), did 1 search, clicked on one link and FF froze. After restarting FF - no Bookmark path, no stats. Did a reinstall and it works again.

**Comment by aaFn** [comment] 2022-11-20 09:37
ok, very strange ... the problem might be more profound than that.
If that comes back again, you might want to try in a fresh FF profile (see the profile mgr for switching between two profiles) with importing all your bookmarks in that new profile ? Or look at BSP2 messages in the browser console https://github.com/aaFn/Bookmark-search-plus-2/wiki/Getting-and-providing-logs-for-debugging-BSP2 (or in the trace box which appears when you tick the Trace BSP2 option)

**Comment by aaFn** [comment] 2022-11-24 22:40
Looks like there is a pattern here .... let's hope that having a fresh profile is helping !
At the occasio, when you have the errors, if anything is appearing in the browser console as said above, I will be interested, at to see if I recognize some symptoms .. thank you

**Comment by elgreko2** [comment] 2022-12-01 08:44
28. nov. 21 h - Did a Refresh option
01. dec. 09 h - Bookmark path disappears yet again
Remove and install BSP2 and it works again.

Should I nevertheless try another profile?

**Comment by aaFn** [comment] 2022-12-01 08:51
If you didn't try yet, I would say yes .. to eliminate things or try to better locate the source of the problem.

However, when the problem arrives, if you are able to see if there are BSP2 error messages in the browser console Ctrl-Shift-Jand paste them here, that would also help (just try a few actions on BSP2 if you see nothing related to BSP2 iin the console, in case this could trigger something)

**Comment by elgreko2** [comment] 2022-12-01 09:07
As you instructed me, I just activated trace box. 

But, could it be of any help because, as I already said, I do not use BSP2 save for that Bookmark path option, which, of course, means I am not in BSP2 but in FF Bookmarks?

**Comment by elgreko2** [comment] 2022-12-01 10:21
Trace box:

Load local store duration (folders only): 29 ms
Background load local store duration: 8054 ms
Background bypassed FF API for tree load
Background tree load duration: 23503 ms
Background tree build duration: 319 ms
Background save duration: 9386 ms
isSlowSave: true
Get tree duration: 1 ms
PlatformOs: win
Setting Windows variations
structureVersion: -img16-bnlist-spfldr
disableFavicons_option: false
pauseFavicons_option: false
Display duration: 4839 ms
Total duration: 4869 ms
fontFamily = '"Segoe UI"'
fontSize   = '12px'
Stats:
------
Bookmarks:             229338
Favicons to fetch:     221744
Unsuccessful favicons: 1499
Folders:               9374
Separators:            206
Oddities:              0
--------------------
Favicon display duration: 11090 ms

Since some minutes, I am on FF 107.0.1

For some reason, displayed number of bookmarks doubled.

Most importantly - can not use BSP2 at all because when I am in it, right click on a bookmark, then Properties, then keystroke Home takes **4 to 5 seconds** which makes it unusable.

**Comment by aaFn** [comment] 2022-12-01 10:47
Ok, no error so far .. stop the favicon fetching .. givn you have to restart every 2 days, I do not think this is useful to you for now 😄 
That should solve the 4-5 seconds process delay I presume

**Comment by elgreko2** [comment] 2022-12-24 10:23
Hello aaFn,

Since the last update - 108.0.1, thats 8 days now, freezing never happened so I think its resolved.

"Of course", since the one before last, I think, they introduced another bug - when hovering over a bookmark to show its full name - it flickers making it unreadable...

**Comment by aaFn** [comment] 2022-12-24 10:36
Hello @elgreko2 , good to hear that.
Strange on the flickering, I am also on 108.0.1, and I do not have that effect. Are you sure this is not due to something else configured or added to FF ?

**Comment by elgreko2** [comment] 2022-12-25 13:58
Definitely not.

Try hovering on a bookmark in a left list, then do a search and hover over a result in a list - it flickers.

**Comment by aaFn** [comment] 2022-12-25 20:16
Just tried again, it works perfect for me (FF 108.0.1, Windows 10)

**Comment by elgreko2** [comment] 2022-12-27 09:55
Tested again - do a search, hover over a bookmark - it shows for a second and disappears, repeats it twice, and if I move the cursor and return it it now works.

Do the search again, and above explained repeats, every time.

I am on Win 7.

**Comment by aaFn** [comment] 2022-12-28 19:04
Hello @elgreko2 , I could reproduce it on my Windows 7 VM.
It does not happen on Windows 10 (or I presume 11).

The problem is a bit random, and I didn't find a logic for when it happens and when not.
Sometimes, simply getting away from the line and coming back to it solves the problem. Sometimes not.
It looks like when you click somewhere else than on the search box to remove the cursor focus, the problem disappears. However not 100% of times ..

Note that the problem is general and not just on BSP2 : e.g. open the URL "about:addons", hover over any of the titles the left like "Plugins" and the same happen, the tooltip appears and disappears shortly after (you may have to click inside the page for it to happen, it suffers from the same randomness on my side).

This bugzilla seems related https://bugzilla.mozilla.org/show_bug.cgi?id=1800742, although seemingly a little bit different, but Windows 7 only.
No solution inside, and severity is S3 ..

If you have a deterministic way to reproduce the problem, I suggest that you do a mozregression (https://mozilla.github.io/mozregression/install.html) to pinpoint the patch which created the problem, and then that you report it on bugzilla https://bugzilla.mozilla.org/home, saying that this is on Windows 7 only.

Sorry for no better answer.
Since it is erratic on my side, it is better if you are the one to report it to FF guys.

**Comment by elgreko2** [comment] 2022-12-28 20:09
Bookmark path just disappeared again...

**Comment by aaFn** [comment] 2023-02-27 11:58
Related to Firefox on Win7 only, that is a Firefox (or maybe Windows 7 ?) issue.
Cannot fix it inside BSP2, so closing the issue.

**Closed by aaFn** 2023-02-27 11:58 UTC
Labels: external dependency
