### ISSUE TITLE
"Add new folder" dialog getting progressively smaller

### ISSUE THREAD

**Issue by DmitriR** [aaFn/Bookmark-search-plus-2#123] opened 2020-01-04 22:58 UTC
FF 71 on MacOS 10.14.6 Mojave - but same behavior in several earlier versions of both. 

When creating several new folders consecutively, each subsequent dialog is smaller by about 1cm diagonally; the behavior does not end at any minimal size.

**Comment by aaFn** [comment] 2020-01-05 13:44
Hello @DmitriR , as I do not have any MAC / IOS device (not even as a VM since I would need a licence that I do not have), I cannot test in such environment. However, Apple OS is a BSD UNIX with plenty of common things with Linux as I get it, so I am presuming it works the same.

I see no such behavior on Linux (nor Windows).

A few questions:
- Is that only on "New folder..," or also on "New bookmark.." ?
- Could you try when activating the option "Remember size of resizeable objects .." ?
- Could you see if somebody in your surrounding with a MAC has the same problem, or only you ?

Thank you, aaFn.

**Comment by DmitriR** [comment] 2020-01-06 02:46
Hi aaFn,

(first off, thank you for the very useful add-on! I have thousands of 
bookmarks [they keep accumulating for all the old projects], so a folder 
structure and search are indispensable. Actually there is one other 
thing, comparatively minor, that I keep wishing for all the time - a new 
folder/bookmark being placed above the existing items in the current 
folder, otherwise in a long list I have to scroll down and move it up 
manually)

> - Is that only on "New folder..," or also on "New bookmark.." ?

Both; they behave identically and interchangeably (e.g. after two "New 
bookmark", a "New folder" dialog will be smaller than the preceding "New 
bookmark")

The dialogs (both types) also progressively shift up and to the left on 
the screen as they get smaller, by the amount that is greater than the 
decrease in size (by about 1/3 to 1/2 of the diagonal of the dialog, I 
think).

> - Could you try when activating the option "Remember size of 
> resizeable objects .." ?

The option was checked all along.

Interestingly, if I UNcheck it, the size-decrease behavior stops or is 
slowed down, although the  position creep (up and to the left) 
continues. Checking the option brings back the size-decreasing behavior.

(so I’ll try to keep the option unchecked for now)

> - Could you see if somebody in your surrounding with a MAC has the 
> same problem, or only you ?

Will try to check tomorrow.
Thanks!
Dmitri

**Comment by aaFn** [comment] 2020-01-07 21:27
Ok, thank you.
It can be that the window descriptors I use to save position and size behave differently on MacOS compared to Linux and Windows.
I'll need to verify it happens with others to make sure.

Maybe I could experiment something by giving you a temporary version to try out and to verify.
Would you be open to attempt that ?
This would require to use the debug panel of add-ons, and to load a temporary version which will last only for the FF session, and co-exist with the normal one -> https://developer.mozilla.org/en-US/docs/Tools/about:debugging

Let me know. Thanks, aaFn.

**Comment by DmitriR** [comment] 2020-01-08 03:20
Yes, I can try the development version.
D.

**Comment by aaFn** [comment] 2020-01-11 22:48
Update, I believe I got the problem accidentaly myself : I could reproduce exactly what you describe because of the zoom.

Try it yourself: when the property window is active -> leave the mouse cursor inside the window, then press Ctrl while rolling your mouse wheel = it will decrease / increase the visualisation zoom of the window depending on the direction you scroll the wheel. You can mainly observe it by the size of the characters in the text and buttons.

The effect of this is to change the CSS pixel ratio, and coordinates of the window are obtained in CSS pixel unit, but when opening the property window they are given as physical, so things are shifting ...

For some reason, FF seems to remember the zoom across the property window lives, and even across FF restarts. I will look for a way to reset / impose it to 1.

**Comment by aaFn** [comment] 2020-01-12 00:33
After investigation, there is no way to set / reset the browser zoom by CSS or Javascript in FF, so I cannot change it.
The only way for you to come back to normal size / normal zoom is to use the Ctrl + mouse wheel trick inside the property window.

However, the shortcut to come back to normal doesn't seem to work, so you have no way to know for sure that you came back to 1.0 (= 100%).

Therefore, I will leave in 2.0.70 a trace in the browser console (Ctrl+Shit+J, and check "Show Content Messages" option in the parameters at top right), to display the ratio in the form of:

`closeSelf() - window.devicePixelRatio=1`
or
`closeHandler() - window.devicePixelRatio=1`

When not normal, you will get a 1.xxx or 0.xxx value.

And I improved the code to better behave on position and size, by converting CSS pixels to physical pixels, so the effect will not happen anymore now when zoom is different from normal (= 1).

This will be in 2.0.70 that I will publish this week-end.

**Comment by DmitriR** [comment] 2020-01-12 07:03
… great catch on the zoom! I always have it enabled in FF (to about 
120%) because I use a large external monitor.
Thanks again for the add-on.
Dmitri

**Comment by aaFn** [comment] 2020-01-12 10:03
Ok, I found ways to alter the zoom, but I won't touch it to not interfere with people like you who want to control it. However, in 2.0.70 I will disable Ctrl+mouse wheel effects in the property window.

Out of curiosity, how did you set the FF zoom to 120% by default ?

**Comment by DmitriR** [comment] 2020-01-12 18:18
For zoom I use an add-on, NoSquint Plus, setting "Default full page zoom 
level"

**Comment by aaFn** [comment] 2020-01-12 18:54
Ok, I just verified things were remaning compatible with both "NoSquint Plus" and "Zoom Page WE" -> all is ok.

Therefore BSP2 2.0.70 is now out, improving as said above on zoomed contents handling, and avoiding accidental Ctrl-+mouse wheel zoom changes.

Let me know if any problem, or if the Property window shifting and resizing is still happening while it shouldn't.

Thank you, aaFn.

**Comment by aaFn** [comment] 2020-02-16 17:41
Closing as problem is resolved, aaFn.

**Closed by aaFn** 2020-02-16 17:41 UTC
Labels: bug
