### ISSUE TITLE
Minimum width management / improved compatibility with sidebar autohide css scripts

### ISSUE THREAD

**Issue by Aragon4** [aaFn/Bookmark-search-plus-2#174] opened 2021-01-20 16:29 UTC
Hi, 
I'm a user of a sidebar autohide css script (such as this: https://github.com/MrOtherGuy/firefox-csshacks/blob/master/chrome/autohide_sidebar.css) and as I find there's a critical compatibility issue with BSP2 that I think can be fixed rather easily.
I say critical because it removes the ability to bookmark by dragging links from the address bar and I don't see this as something many can live without. This is "covered" by mozilla in FF's native bookmarks panel probably without specific consideration of this issue so I think it also fits in the "general improvement" category.

Now I know css autohide has its limitations but there are workarounds and by supporting it with BSP2 this would pretty much cover all of the functionality I still miss from the good ol' AiOS and I believe there may be others who feel the same. 
I'll explain below what I mean by "workarounds" because, as I find, css autohide's main issues are that it can't be disabled, so the sidebar will collapse as you reach for the address bar, and then you can't "uncollapse" it while dragging a link because it only responds to hovering (or at least I wasn't able to find any css hacks that can do that, and I'm not a programmer please correct me if i'm wrong).
Because of this css autohide may not look like something really functional, but it's actually still possible to bookmark by dragging. It may seem a bit cumbersome but for me just works well enough. Basically you just need to select the line (bookmark) in the bookmark tree above the point you want to insert the bookmark. Then as the sidebar collapses it will become narrow but still visible and if you set a decent width for the collapsed bar and use a window manager to left align FF's windows to the desktop, then dragging the link over the collapsed sidebar is quite easy. For me it works just fine and I am personally not feeling any need to disable autohide just for this.

But the problem is this actually works only with the native bookmarks panel and not with BSP2, and that's just because of the scrollbar. The native bookmarks panel has a minimum width enforcement which sets the leftmost positions for the scrollbar and close button (assuming sidebar on the left) but BSP2 does not seem to have this "management" and the scrollbar ends up obscuring everything when in collapsed state.

So here comes my proposal, as I can see there's already a feature implemented in BSP to disable scrolling when dragging links from outside the sidebar, and while this seems different than mozilla's implementation I don't see why it wouldn't work just as well. My question is rather obvious at this point: is there any problem with also triggering this same code and hide the scrollbar when the sidebar's width is under a certain limit?

As I see there are people using the tab mode for extra real estate and I believe autohide may be used for the same purpose (and I think it's way cooler) so I hope I have been clear about why I consider this useful. Right now with autohide enabled I have to constantly toggle between BSP2 and native depending if I need to search or bookmark, but with this fixed I really see no significant reason to disable autohide. And as I initialy said I consider this a general improvement as well as there's also an aspect issue, because of the scrollbar BSP2 doesn't look properly when collapsed.

Thanks in advance and also thanks for the extension, I think this really is the proper way bookmarks should be handled given all the existing limitations.

**Comment by aaFn** [comment] 2021-01-20 23:37
Hi @Aragon4 , first let me say this autohide CSS is a rather ugly hack when I look at the code and its effects.
- the content of the sidebar is not very well drawn, depending on the size you specify for `--uc-sidebar-width` in the top `#sidebar-box`
- events also get badly forwarded
- for example:
    - with a width of 20px, no drag event ever arrive, nothing is drawn in the sidebar
    - with a width of 40px, BSP2 appears to receive only the drag events on the leftmost 1st pixel of each line, and drawing is random = sometimes all is blank, sometimes we see bits of what is in the sidebar
    - note also that at 40px, when we see the sidebar content, your workaround trick of highlighting the previous line where to drop works for BSP2 (at least on my system)
    - with a width of 60 px or more (may need to tune that depending on your resolution and settings), drag events are properly received, sidebar drawing is fully functional, and you can drag actively to it. Again the trick of highlighting previous line works well.
- BSP2 does not see its width modified in any way, so it doesn't have a way to know that the sidebar containing it is reduced / collapsed. In fact, BSP2 content of the sidebar is simply hidden / not drawn, partially or fully, and BSP2 doesn't know about it (it doesn't even know about the containing sidebar / sidebar-box objects, they are not visible to BSP2)

Net is that I do not see a way to do what you want, or nothing really reliable nor working in all conditions.

I can only advise you if you want to stick to use this autohide CSS to tune and set a proper value to `--uc-sidebar-width` so that your trick of highlighing the previous line is constantly working
=>that works for me at 40px randomly, at 60px always ... you will need to find your own system specific value by trying.

I can propose also another way to do roughly the same thing as you want, without the autohide CSS =use keyboard shortcuts:
- when you need the side bar to appear, press the keyboard shortcut which makes the sidebar content appear (Ctrl-B for the native bookmark sidebar, or Ctrl-Q in Windows for BSP2)
- then drag into it
- the press again on the keyboard shortcut and the sidebar disappears
- BSP2 option page allows you to set the keyboard shortcut that is most convenient for you, provided it is not already assigned by FF to something else of course (there are not so many which are free ... and they vary by OS 🙄 )

Sorry I do not have any better answer at this time. Thanks, aaFn.

**Comment by Aragon4** [comment] 2021-01-21 12:01
Thanks a lot man for the quick and extensive reply and all the work investigating my request, really appreciated!

And yeah, I have actually considered the sidebar size may not be available but since there's no security concern here
I was worrying more about the trigger event on width change than anything else. But in this case ... problem solved.

Regarding the issues you have noticed I don't see anything of concern on my system:
The native bookmarks works like a charm with --uc-sidebar-width: 2px;
I have no bookmarking failures at this size but you can't see the selected line so obviously not usable.
At 1px the sidebar still opens (uncollapses) perfectly but there's nothing left of it visible and bookmarking is not working at all.
I am using it set to 8px because BSP2 searchbox starts becoming visible at 9px and it doesn't look as well.

With BSP2 at 20px it works just as well, this seems to be the equivalent of native at 2px plus an 18px scrollbar that's in the way.
At 19px behaves like native 1px, not working at all.

So not sure why you are concerned about things being drawn and the events really seem to happen on my system, although I can't verify this other than seeing that the bookmark was placed. I just drag to the left of the screen and release the mouse button, then the sidebar immediately opens as it detects a hover and the inserted bookmark is there every time.
Sure in some cases it's above the selected line rather than below, that's because you actually need to be in the lower half of the selected line and being obscured by the dragged link you can't see exactly where you are when you release the button (or care).
Because the mouse pointer is already in position it's not much of a problem for me to move the bookmark where I want, and
I can even change my mind and move it somewhere else easily at this point. That's why I don't see much difference as compared to the regular way of doing this.

So yeah I agree the hack is just a hack and nothing better 😀 but it seems reliable and good enough for now on my system and not planning to install other extensions that may interfere very soon.
But anyways it's pointless now, if you don't have access to the sidebar width nothing can be done and you can close this request.

And it may appear at this point I could just set it to 30px to make the selected line visible and use it like that.
That is an option but not the best since in autohide mode the sidebar is overlapping the main tab and could cover something.
css autohide it's not like AiOS behavior and I actually like it better this way but it shouldn't be too wide when collapsed.

But I guess these are the options I have for now and for the rare cases when something is not visible I could reach for the toolbar button and temporarily hide the sidebar completely. Or (likely) keep what I'm doing now because at 8px the native just looks so well. 
... Although I am thinking it may be possible to disable scrolling through css 🤔, just that again I don't know how.

Regarding the kb shortcuts I was of course aware of them, they are even displayed in the sidebar header menu, but as far as my habits are they are worse than reaching for the toolbar button. When just browsing I'm not always with my hands on the keyboard.

Thanks again for the help!

**Comment by aaFn** [comment] 2021-01-21 13:14
Ok, glad this works better on your system than on mine .. My concern on things being drawn is that when not drawn (= painted), I see nothing in the sidebar, just white space (not even the scrollbars). In such case, your trick of pre-selecting does not work at all of course.
This is random at 40px for me, sometimes drawing, sometimes not. No need to say that the values of 1, 2, 8, 9 .. 18, 19 px you mention are not functional at all on my side.

Also, even if there were a way to retrieve a width number somewhere, how to get notified of it changing to properly handle things would be the next problem to solve ... (not mentioning how to distinguish between normal user action wanting to reduce and so need to keep the scrollbar, and an action of a script like autohide where the scrollbar would be not so needed).

I am afraid the conclusion is that this approach (at least in that CSS) is not integrated enough with the overall FF behavior and event system to safely devise a stable & reliable solution in code.

=> Net is that best way would be indeed to add a few CSS hack lines to the specific CSS code that you are using.

And I thought I had found something yesterday evening based on :has() and on :-moz-drag-over, but:
- apparently the first one is not working in userChrome.css, it fails in error and breaks the rule (too bad, because then we cannot select #sidebar as needed based on criteria of child components, which is what would be needed to do what you want)
- and the second requires that #sidebar or #sidebar-box handle the dragenter and dragover events to say this is a valid target for it to work,and this is not the case

So having no reliable way for it to work, depending at least on the system of the person, hard to do anything general enough to improve that particular way for all 😞 

---------------------------------------------
Best I can think of at this time is that you add two lines to your autohide CSS, based on selector .bscrollok for a class I am using in my own BSP2 CSS:
```
#sidebar-box:not(:hover) > #sidebar .bscrollok { overflow: hidden !important; }
#sidebar-box:hover > #sidebar .bscrollok { overflow: auto !important; }
```
or something to adjust along that .. (didn't test) .. that might do what you want

**Comment by Aragon4** [comment] 2021-01-21 13:55
OK it looks I was editing the previous message and did not see yours in time...
Thanks a lot for the answer again, I will try to experiment by myself with what you provided although not being a programmer I don't really understand all the details.
But as I said in my edit this has nothing to do with BSP so I should be taking over at this point. 👍 Thanks!

**Comment by Aragon4** [comment] 2021-01-21 14:28
> Also, even if there were a way to retrieve a width number somewhere, how to get notified of it changing to properly handle things would be the next problem to solve ... (not mentioning how to distinguish between normal user action wanting to reduce and so need to keep the scrollbar, and an action of a script like autohide where the scrollbar would be not so needed).

I'll still add a comment to this for clarity though as it was mentioned in OP: the idea was to ALWAYS disable scrollbar when width is under 30px for example, I think this is what mozilla is doing with its native panel (unconditioned) and actually at a bit more than 30px because at such small widths the scrollbar does not help, on the contrary.
As far as the trigger event as I said this was my concern as well... was just hoping there's a known solution for this.

Anyways it is clear for me now that css is the only way, if I manage to do it I'll let you know. Thanks!

**Comment by aaFn** [comment] 2021-01-22 10:35
Bad news ...
It appears (since I do not know when, but post FF 63 because I know that some people were playing such CSS tricks at the time before I introduced customizable folder image, and that was working)
that:
- userChrome.css cannot anymore impact add-ons nor view their CSS objects, they are now completely isolated (by sandboxing ?)
- only userContent.css can have access to add-ons CSS objects
- but of course userContent.css cannot impact the Firefox general behavior / vies FF objects like #sidebar

So your autohide CSS can only reside in userChrome.css, but the CSS modifications to act on BSP2 cannot reside there, they must be on userContent.css to really have an effect .. And the problem is that 1) both must be together to act properly, and 2) such rules refer to both kinds of objects at same time, so no place for them 😞

**Comment by Aragon4** [comment] 2021-01-22 13:22
Yeah, I've spent a bit of time yesterday investigating this and only found suggestions that no longer work.
Such as this (in userContent.css), which was reported to work with older FF versions:
@-moz-document url-prefix("moz-extension://{f08670bc-7289-4dfc-b946-655533921843}/") {
  scrollbar-width: none !important;
}

So I was willing to settle with something that disables scrollbar completely as long as the scroll remains operational, this way no trigger is needed, not even hover. And I was able to disable scrollbar for the native sidebar but nothing worked for BSP2 so I've already given up. I have a gaming mouse with customizable buttons per app, so the final resolution was to map Ctrl-B/Ctrl-Q to the scroll wheel side buttons, this only works on my main machine for now but nothing more can be done at this point.

Still, thanks for the info and for further investigating this, it made things a lot more clearer.

> This is random at 40px for me, sometimes drawing, sometimes not. No need to say that the values of 1, 2, 8, 9 .. 18, 19 px you mention are not functional at all on my side.

Regarding this I would also try with all extensions disabled, if you're on windows I believe something is not working just right on your system. And who knows if you're able to fix the problem you may want to use this hack yourself 😀

**Comment by aaFn** [comment] 2021-01-22 16:19
And last some good news now 😀  

I could find that the top Window object of BSP2 does get notification of resize events when your CSS autohide is acting => so I have a way to know that something is happening.

Therefore with a combination of https://developer.mozilla.org/en-US/docs/Web/API/Window/resize_event
and of https://developer.mozilla.org/en-US/docs/Web/API/Window/getComputedStyle
I have a way to get the real sidebar size when it is changing.

So I implemented a small addition in BSP2 which is called when the sidebar is changing its size, and when I see that this is becoming too small, that is <= 40px, I hide the scrollbars.
I took 40px because:
- this is the point where the behavior start to be random (at least for me, and no I have no other add-on), and where things start to be not reliably usable, so having scrollbars or not does not change much
- below 40px, since not a lot of content is visible when painting properly, who can really care about the scrollbars (apart from you .. 😁 ) ?
- above that value, more is visible and I see it is useful to keep the scrolling
- and 40px is well under the minimum value that a normal user can resize the sidebar to, when on GUI (FF sets a minimum width).
So when getting to such values, this can only be because somebody is tweaking things with userChrome.css like you do ..

=> I won't make this a parameter / an option, this is special code for you basically.

Last, I am still not fan of that method / CSS hack. One big problem I see is that it prevents you to resize the sidebar, so its size is fixed, and if you want to enlarge it when it is"open", or reduce it, you can't.

This will be in next version (2.0.87), hope you will enjoy it.

**Comment by Aragon4** [comment] 2021-01-22 17:22
Awesome, and it happens I was also able to fix it with your previous suggestion as well !!! 
Was having some of the below already edited when I saw your new message, so it seems I'll only be needing to use the current fix until the next version.

Actually the way it's fixed on my side right now is with this:
 .bscrollok{ scrollbar-width: none !important; }

because "overflow: hidden" disables scrolling as well not just the scrollbars and that's not really functional.
The 2-lines code you provided yesterday would not have this problem but it's not working even in userContent for the reasons you already mentioned.
bscrollok was the first thing I tried yesterday per your suggestion, with both overflow and scrollbar-width but it was in userChrome

As I've noticed some people are willing to disable scrollbars even in tabs just for more space which is not something I would do,
but for BSP2 it makes far more sense, the width is much smaller than for a tab and more importantly with bookmarks I don't need an indicator to know where my vertical position is, I can tell by content.
They're still useful for History, which is native so still has them but for me not really useful for Bookmarks.

So the above solution works for me sufficiently well but your new mod is still very much welcome, thanks a lot for that.
And what you did with this mod is exactly what my initial suggestion was and as I said what I believe mozilla is doing with its native panel. It seems they do care what happens below a value by my testing close to 40px as well and this is why their native panel is working well. As I said before I consider this a general behavior improvement, exposable only through css hacks indeed but still an improvement. Would have not requested it if it needed to be an option because I know there's more work with that and would need to have some utility for something other than css hacks.

I agree there's indeed the disadvantage of resizing but at the same time you can set it larger than when not autohiding so I don't feel the need to resize much. So disadvantages and advantages and anyone is welcome to have its own preference, cheers!

Thanks a lot for everything !!! I was actually no longer hoping to have this working! At least not today and not twice 😄

**Comment by aaFn** [comment] 2021-01-26 08:24
2.0.87 has been published. Let me know how that goes now, aaFn.

**Comment by Aragon4** [comment] 2021-01-26 17:07
Just tested and works fine on my system.
Also using .bscrollok in userContent for additional tweaks:
.bscrollok { overflow-x: hidden !important; }
.bscrollok { scrollbar-width: thin !important; }

No issues, thanks! 🥇

**Comment by aaFn** [comment] 2021-01-26 22:17
Ok, good. Just be careful with removing the horizontal scrollbar, because il you have nested levels of folders going too deep, these and their content will get out of sight on the right (and since you cannot resize the sidebar, you won't see their content easily).
=> That trick only works if you do not have too many levlels of folders.

Closing the issue as resolved then. Thanks, aaFn.

**Closed by aaFn** 2021-01-26 22:17 UTC
Labels: enhancement
