### ISSUE TITLE
Blue drag line for bookmarks. Make it so it doesn't wobble the tree.

### ISSUE THREAD

**Issue by JohnLukeBentley** [aaFn/Bookmark-search-plus-2#77] opened 2018-12-17 09:28 UTC
In the native sidebar and BSP2 when you drag a bookmark, as you are finding a place to drop it in the tree, a blue location line is displayed in each. However there is a key difference: the BSP2 blue line wobbles the tree. Specifically the items beneath the current position. The native sidebar doesn't do this.

I suggest BSP2 be made like that native sidebar in this respect.

@aaFn, your hands might be tied here because FF webextensions might block you from implementing the right solution in a similar way it did for putting a border around a default button. 

However, if you weren't restricted, and it is a CSS matter, it sounds like this problem could be solved in one of two ways:

* Use an outline instead of a border (e.g. `outline: 1px solid blue` rather than `border: 1px solid blue`; or
* By default use a white border (``border: 1px solid white;`) on all items and just change the top border's color to blue on hover (`border: 1px solid blue;``) 

As a related but separate matter I think the native border's slightly thicker border around items and (therefore) blue location bar, is better to use. I'd suggest bumping up the border thickness to whatever that value is (2px?).

**Comment by aaFn** [comment] 2018-12-17 21:11
Hello @JohnLukeBentley, as explained elsewhere, this feature (and so inconsistency with native sidebar) is so far wanted, and allows to add an item after a folder which is the very last item of the bookmark pane, even if it is open. This is not possible with the native sidebar as far as I could experiment.

**Comment by JohnLukeBentley** [comment] 2018-12-18 04:34
As far as I can tell this is quiet separate to #61. Here it is merely just an issue of not wobbling the tree. So you could, for example, keep the behaviour you are defending under #61 but fix the issue here ( #77). In other words here, in #77, I'm making no request to remove drop areas.

**Comment by aaFn** [comment] 2018-12-18 07:42
Ah sorry, english is not my native language, so I missed the point.
You mean that the bottom border when appearing is shifting everything below by 1 pixel down, correct ?

I had looked at using outline, but this is creating a counter intuitive effect that the line for the "previous" sibling insert point of the next sibling is visually **above** (by 1 pixel) the line for the folder next sibling insert point .. not very good :-(

From memories, the problem is that the favicon image is 1 pixel too low .. or something like that as the phenomenon does not appear on all objects .. I will look at it in details next week end to see again how to correct that, this is visually annoying I agree. Last time I didn't find a good solution for it.

**Comment by JohnLukeBentley** [comment] 2018-12-19 03:04
> You mean that the bottom border when appearing is shifting everything below by 1 pixel down, correct ? ... this is visually annoying I agree....

Yes, you've got it.

My apologies. I already knew you were not a native English speaker. I should have therefore guarded against your being unfamiliar with "wobbles" (I presume this is where the difficulty arose). 

https://en.oxforddictionaries.com/definition/wobble
> 1.1 ... Move unsteadily in a particular direction.

And just to give you a further hand with English: your "From memories" should have been "From memory" ... the singular.

Anyway thanks for taking a look at the blue drag line.

As I mentioned in my first post ... if `outline` doesn't work then you might like too look at my second suggested technique (a fake border, because it is white, that turns blue on hover).

I should qualify my earlier remarks about the relationship between this issue and #61. Although it remains true, you'll now understand, that they are separate issues they are related in that if you can make the wobble (the "shifting everything below by 1 pixel down") disappear then this might help your defence of the status quo in #61. That is, if the blue line can be made more stable (and, perhaps, thicker) then use of your first child V next sibling drop areas might be less difficult to use.

I've also yet to attend to your latest reply in #61, but hope to do so ... in the fullness of time. :-)

**Comment by aaFn** [comment] 2018-12-19 09:06
Thank you for the English lesson :-)
Yes fake border is more likely, but this is introducing 1 more pixel in height, making things less compact. I have to think more on that path ....

**Comment by JohnLukeBentley** [comment] 2018-12-19 10:32
:-) ... you are welcome.

On 1 more pixel in height: I was going to suggest you do that anyway for the sake of not being too tight. 

Whether to be more or less compact is a design decision that could go either way. I'm not a graphic designer. But I just have happened to read Google's Material Design guidelines that bear on this issue

https://material.io/design/layout/density.html#usage
> Components with high density enable users to process and take action against large amounts of information in a more manageable way. List, tables, and long forms are components that benefit from increased density.

See the accompanying picture: https://storage.googleapis.com/spec-host-backup/mio-design%2Fassets%2F1YKHvHftsbsUjMdrUh0ilymDUZdWEnXMV%2Flayout-density-rows.png

So, on that basis, your instinct to have a compact tree helps users "action against large amounts of information in a more manageable way". 

On the other hand the native bar, in being less compact, seems to have more white space which gives it a sense of breathing room.

I recently discovered your option "Override default font size to". This is a great thing and I've already set to my personal preference (13px). 

Perhaps "Override default item spacing to" would be worth adding. 

These are sort of a separate issues, the issues of the ideal line spacing and/or whether to offer line spacing as a user option, but they interacts so heavily with the current "Blue line wobble" issue that I thought it best to raise it now ... as you think things through and perform experiments.

**Comment by JohnLukeBentley** [comment] 2018-12-23 01:02
Hello @aaFn !

Yes, you've done it! It's look great now. Although there is one side effect which I'll detail below.

Before that detail ....

I didn't realize that `outline` is not quite analogous to `border` at the CSS level. Even looking at the draft CSS 2.2. we find that `outline` doesn't allow for targeting top, right, bottom, or left <https://www.w3.org/TR/CSS22/ui.html#dynamic-outlines>, unlike for `border`.

Your use of negative margins sounds like a clever hack. I get the sense I'd see how this is necessary if I delved into the code. I'm guessing you create hidden areas that overlap the list items in order to have different drop areas (next sibling V next sibling of parent, etc). However, for what it is worth, here is the technique I had in mind for a simple nested list [CodePen > BookmarkSearchPlus2-Issue77-BlueLineWobble-DesignSpike001](https://codepen.io/johnlukebentley/pen/MZmazR).

>  will see if I can add an option for people who would like to add extra spacing later.
I've created #78 for this.

> I tried to do thorough testing as this kind of aesthetic change can in fact have side effects in unexpected places.

Yes I think I've identified a side-effect or a pre-existing bug:
* Open BSP2.
* Drag an item from the address bar to the tree. It all works as expect.
* Now scroll your tree down a bit.
* Drag an item from the address bar to the tree. We find the tree starts to scroll up a little bit as your cursor enters the tree. I'd expect no such scrolling.

**Comment by aaFn** [comment] 2018-12-23 21:07
Yes, this is normal, this is the default scroll bar behavior .. and I do not know of a way to override this.

Plus this is what we need, at least vertically =  when you drag something from the sidebar and you go in the upper zone or the lower zone of the bookmark pane, it respectively auto-scrolls up or auto-scrolls down. This allows to start to drag something from anywhere in the tree and to drop it much upper or lower than the visible zone, so this is good

Horizontally, if I could disable this, I would as it has no use, but it does not seem I can. I tried to search for things describing areas sensitive to mouse position while dragging / selecting, which trigger the autoscroll, and to reduce them to 0, but couldn't find that ...

And if I suppress the horizontal scrollbar, then:
- there is no way to see the full contents of the iems,
- and when the folders are very deep, they go outside the visible zone and we lack a way to horizontally scroll to see them.

so it is not the solution.

----------------------------------
On border and no negative margin, I have to use negative margin because there is an object containing each line (the cell and then the row in the table), which is selectable, I and need to show that selection with the gray / blue bar.
Thanks to the negative margin:
- the 2px line for insertion is crossing each time two such cell/row, 1px inside each, and so it does not expand their height,
- and the 2 px line is at the same position for the "after" one and the "before" one of the next sibbling (only its length varies showing it does not refer to the same sibbling).

**Comment by aaFn** [comment] 2018-12-31 13:39
Hello @JohnLukeBentley , good idea, but there is no event for autoscroll or the like I could observe .. but if you see one, let me know.

We have to mind also that the behavior for drag & drop is quite codified, with expected interactions between the code and FF
cf. https://developer.mozilla.org/en-US/docs/Web/API/HTML_Drag_and_Drop_API/Drag_operations
already using the return value and other preventDefault things ..

Deviating from that would break the drag & drop function, supposing this could have an effect on the auto-scroll bars behavior by the way (which I doubt).

I spent several hours researching obvious & hidden things, but there is nothing I found that I could do to alter that behavior. Ideal would be able to tune the size of the area triggering the auto-scroll, but I really didn't find anything exposed.

On the native bookmark sidebar, I checked, it does the same thing (at least on my OS Win10, I didn't check on Linux and I do not have a Mac):
- Open the sidebar
- Scroll down a little
- Drag the (i) thing passing by the top of the sidebar, remain there at the top a little ... and whooop it auto-scrolls up .. Maybe the dealy for it to happen is longer, but couldn't figure out how to tune that either.

I fully agree it would be better to try to avoid it, or to tune a sufficiently big delay before it happens, or to decrease the auto-scroll area ... I couldn't find any of those so far (and believe me I spent time on it) .. :-( If you see anything, let me know.

**Comment by JohnLukeBentley** [comment] 2019-01-08 03:03
Thanks @aaFn. 

I see now, given your explanation, that the native sidebar behaves similarly excepting there is a delay on hover over the small area at the top which, without the delay or if the delay is over, will cause the autoscroll.

> I fully agree it would be better to try to avoid it, or to tune a sufficiently big delay before it happens, or to decrease the auto-scroll area ... I couldn't find any of those so far (and believe me I spent time on it) .. :-( If you see anything, let me know.

If we can find the mechanism (if it exists) then setting a sufficiently big delay might be ideal. I'll have a look ... even though there's not much hope of finding something given you've had a good look. For the first time I'll stick my head in your code and then the FF WebExtensions API.

**Comment by JohnLukeBentley** [comment] 2019-01-11 09:03
Hey @aaFn. I've just went to review your code (at https://github.com/aaFn/Bookmark-search-plus-2 > Code). However the latest date for any/file folder appears to be 6 months. But, of course, you've made recent changes.

Might a simple git push (from you) to the master branch fix this?

**Comment by aaFn** [comment] 2019-01-11 21:41
Sorry, was traveling ... I just refreshed the code to latest level = 2.0.50.

On the delay, I believe I have an explanation for it:
- BSP2 has smooth scrolling
- The native sidebar has "jerky" scrolling, which is bookmark item by bookmark item = it is not possible to scroll up and show half of a bookmark item at top, whatever the method (even by dragging the lift cursor). Each time there is a scroll up or down, this is by the granular height of 1 bookmark item.

I believe that granular scroll is what is introducing the "delay" = the scroll speed is the same in both cases, and is triggered by the same area, but with the "jerky" move of the native sidebar, things really visually move only when the accumulated amount of scroll is bigger than 1 bookmark item height.

Now:
- I didn't find how to reproduce that "jerky" or granular behavior in MDN https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Scroll_Snap/Basic_concepts
- I do not like that "jerky" behavior anyway :-(

**Comment by JohnLukeBentley** [comment] 2019-01-15 11:05
Hello @aaFn!

On Windows it appears to be now working perfectly and as desired:
* When dragging from the address bar there is no auto-scroll that interferes with your current position; however
* After a while, and from within the sidebar, if you drag up or down then auto-scroll is enabled.

Good luck on a work-around in Linux (I don't have a Linux install to test it). 

Anyway that is great progress.

I note also your update to the code on github. For the moment you've made my looking at the code unnecessary.

So thanks for all that!

**Comment by aaFn** [comment] 2019-01-15 14:05
Good. I am thinking of something for 2.0.52 .. just want to be cautious and to try in details, as I do not want to regress on the Windows behavior .. so going slowly.

**Comment by JohnLukeBentley** [comment] 2019-01-16 03:38
Yeah, that's the right approach.

As an English matter the normal phrase here would be "try it in stages" rather than "try in details". At least that's what I think you are going for.

**Comment by aaFn** [comment] 2019-01-16 08:36
I mean I am tracing like hell to observe, elaborate proper approach, verify, and tune :-)

I think I got a good and simple and robust approach now based on what I observed:
- simulate continuous firing of next dragover events under Linux after receiving a first dragover event, as they should
- stop the simulated events when receiving a drag event of another kind, or when the mouse is out of the Bookmarks pane.

Now I am verifying it in stages .. :-)

**Comment by JohnLukeBentley** [comment] 2019-01-17 08:18
... I'll be here ready to help you with a Windows regression test. :)

**Comment by aaFn** [comment] 2019-01-29 22:42
Hello @JohnLukeBentley , all done, including one small bug that escaped me initially, and extension of the feature to the search result pane also ..
It is out tonight in 2.0.52, along with FF65.

Let me know how you Windows regression goes ..,

Btw, I opened a bug on FF for not doing things as per specs on the dragover event -> https://bugzilla.mozilla.org/show_bug.cgi?id=1523769

Thanks, aaFn.

**Comment by JohnLukeBentley** [comment] 2019-01-31 09:38
Hello great @aaFn!

Yes it still works great under BSP2 2.0.52 and FF65, on Windows.

It was just a quick test of dragging a bookmark to various parts of my tree, including that last most and first most position. All looking good. I think we could therefore call the issue closed.

Now that the wobble is firmly gone targeting the "first child position of folder" V "Next sibling position of folder", issue #61, is far less of a problem (and you've closed that issue anyway).

Terrific work aaFN!

**Comment by aaFn** [comment] 2019-01-31 20:00
Thank you.
Closing the issue then :-)

**Closed by aaFn** 2019-01-31 20:00 UTC
Labels: bug
