### ISSUE TITLE
Search bookmarks freezes on certain bookmarks

### ISSUE THREAD

**Issue by Tarsopilami** [aaFn/Bookmark-search-plus-2#114] opened 2019-08-15 06:00 UTC
Opened this issue, because AaFn kindly asked me to.

On searching for a specific string "angiotensin" for example, the list of bookmarks containing string is shown ok - but when I click on the one I want "Angiotensin II and the vascular phenotype in hypertension. - PubMed - NCBI" for example (show bookmark) it takes somewhere around 30-40s for the extension to respond.  This is kind of random with some bookmarks, with others it does not seem to happen.  Sometimes a freeze also happens while typing a search string.

Maybe we can figure this out ?

**Comment by aaFn** [comment] 2019-08-15 09:01
Hello @Tarsopilami, I believe I see what is happening = you have most probably a lot of bookmarks, and currently BSP2 is fetching the favicons in background because FF does not give access to to them, and then saves them to local storage to cache them.

Since FF version 66, the save to local storage is very cpu consuming. I recently spaced such saves a lot to make things useable, but still have to save because else work is lost -> #103 

- Could you verify in the BSP2 options how many bookmarks you have, and how many remain to be fetched ?
- If still fetching favicons as I believe you are, click on "Pause" favicon fetching, and let me know if the problem disappears

If yes, that confirms my hypothesis. And from there, you have three solutions: 
- Definitely stop (Disable) favicon fetching in the options = you will miss the little bookmark images
- Leave to pause, and when you do not work with FF, set Favicon fetching to "Active" again ... and then "Pause" when working .. etc .. until there remains 0 favicon to fetch
- Live with it until all favicons are fetched

Let's see what you get with these little investigations ... Thanks, aaFn

**Comment by Tarsopilami** [comment] 2019-08-15 12:32
![CopyQ wZ8264](https://user-images.githubusercontent.com/23217644/63094615-3d27ca80-bf69-11e9-8993-f3d76f84c809.png)

Clicked on Pause fetching - but the problem persists as far as I can observe.

**Comment by Tarsopilami** [comment] 2019-08-15 12:44
![CopyQ wZ8264](https://user-images.githubusercontent.com/23217644/63094615-3d27ca80-bf69-11e9-8993-f3d76f84c809.png)

There are no favicons to be fetched left.  
Followed your advice and paused favicon fetching & restarted ... delays are shorter now, but still happen randomly & time and again.

**Comment by aaFn** [comment] 2019-08-15 16:11
Thank you.
So if delays happen while simply and only viewing bookmarks, not adding/deleting/updating them, then not sure of the origin.

Next step then would be to look at a few performance aspects.
- Can you open a new tab with "about:performance", and tell me what are the highest rank consumers in there ?
- Supposing you are on Windows (but let m know), could you look at the amount of cpu and memory taken by Firefox inthere, and the total + remaining free memory you have ?
- Is your disk an SSD disk or a classical hard drive ?

If the problem only happens after a bookmark creation/update/deletion, then I would continue to suspect the duration of saves, given you have 36000 bookmarks and this starts to make some volume.
- If you confirm this is only the case where that happens, I will try to think about how to separate things to decrease the size of saves, like a suggestion in #51 which could help, and which I kept open for that kind of reasons (but at the time, the saves were rapid, so once the root problem cured, it didn't occur ogain, and anyway I never had the time to think about optmizing the structure in much details, that is not a simple transformation)

**Comment by Tarsopilami** [comment] 2019-08-16 07:36
Sorry for the delay.  - The highest consumers in about:performance are three tabs I had pinned - they use somewhere between 1 and 5 units "energy".

When the slowdown happens it is usually when I click on a bookmark in the search list - the freeze takes about 30-40s until the bookmark is located.  In the performance tab listing nothing changes until the end of that freeze, where it shows Bookmarks Search Plus 2 with 2995 units energy for a split second before vanishing.

Deactivating all other extensions, closing all other tabs and restarting browser does not affect behavior.

The machine runs Ubuntu 16.04LTS and hard drive is SSD.

The problem does not happen upon creation/deletion of bookmarks, it happens when locating a bookmark in a list of searched bookmarks.

Hope this gives you a more precise picture of the problem we have here. I'd be glad to hear further suggestions to sort this out, as I find your extension really useful :)

**Comment by aaFn** [comment] 2019-08-16 09:07
Thank you, this is getting more precise in the symptoms, but quite strange I must say ..
Save to disk is not the culprit ..  unless you activated a few related options.
By default, when clicking on a result in the search pane to show the corresponding bookmark, not much happens ... apart unhiding things on screen and using a FF API scroll down primitive ...

A few questions as they come:
- In FF preferences, do you use the Performance recommended settings ? Or is graphical acceleration disabled ?
- I presume you are under FF 68.0.2 and BSP2 2.0.64 .. but checking doesn't hurt ..
- Did you activate the `After "Show bookmark", close search pane. _Implies leave bookmark tree open_` option ?
- Did you activate the `After "Show Bookmark", leave bookmark tree open by default when closing search pane` option ?

If any of the previous 2 options are activated, try with deactivating them .. as they provoke a save to disk.

**Comment by Tarsopilami** [comment] 2019-08-16 13:53
So I checked as you suggested:

Firefox version 68.0.1 / BSP2 2.0.64 / none of the 2 options are activated.

Maybe this is a problem with firefox.  Sometimes I also get freezes for no apparent reason. Since I mainly use WF I thought I might try reset the profile, reimport bookmarks & try again.  Would that help debugging ?

**Comment by aaFn** [comment] 2019-08-16 19:28
It might help if you have some odd options that were modified typically when using about:config in the past, maybe for solving a problem, and onw it would cause another one.

Frankly, with what you verified, I can't see what is making this happen. Except maybe if for some reason hardware graphic acceleration is disabled, or is you are not multi-threaded (e10s feature disabled .. be careful that on my RHEL, I had to remove the libva package, it was causing problems .. now you are more recent with µUbuntu, so I would assume you have the proper fixes for it).

**Comment by Tarsopilami** [comment] 2019-08-17 10:55
Recommended performance settings does not show an option for using hardware graphics acceleration, so I thought it would not be relevant.  But since you mention it again, I remember that in the past I have had to manually disable the graphical GPU, because of drainage issues when running on battery.  Will try to test with graphical GPU enabled and get back to you, as soon as I manage to. Thanks for the input in the meantime :)

**Comment by Tarsopilami** [comment] 2019-08-17 11:02
Recommended performance settings does not show an option for using hardware graphics acceleration, so I thought it would not be relevant. But since you mention it again, I remember that in the past the GPU did drain a lot of battery and disabling it for Ubuntu was the only way to improve autonomy. 

So maybe you just hit a nail on the head - as soon as I get a chance to test with GPU enabled I'll get back to you. Thanks for the input in the meantime :)

**Comment by aaFn** [comment] 2019-08-17 17:00
ok, keep me posted :-)

**Comment by Tarsopilami** [comment] 2019-09-01 15:00
So after a break of 2 weeks, I have some new information on the issue.

Unfortunately the problem seems to persist even when the auxiliary nvidia graphics card is switched on (& machine rebooted).

Another noticeable detail: the delay/freeze only happens the first time a certain bookmark is "shown", performing the same search a second time in the same session does not result in a delay.  Closing ff and starting it again with the same query, reproduces the same freeze.  

Hope this information is useful.  Do you have another suggestion to test or try out ? Thank you :)

**Comment by Tarsopilami** [comment] 2019-09-01 15:21
So after a break of 2 weeks, I have some new information on the issue.

Unfortunately the problem seems to persist even when the auxiliary nvidia graphics card is switched on (& machine rebooted).

Another noticeable detail: the delay/freeze only happens the first time a certain bookmark is "shown", performing the same search a second time in the same session does not result in a delay.  Closing ff and starting it again with the same query, reproduces the same freeze.  

Hope this information is useful.  Do you have another suggestion to test or try out ? Thank you :)

**Comment by aaFn** [comment] 2019-09-01 18:08
Hello @Tarsopilami , well I can't see what is causing that. It looks display / graphic related from your description,


I would suggest maybe to investigate if there is something odd in the FF profile by doing the following (do you confirm you are under Windows 10 ?)
- Export your bookmarks = Ctrl+Shift+B, then "Import and Backup -> Export Bookmarks to HTML.."
- Close FF
- Go to a command line (open CMD)
- Type `C:\Users\Admin>"\Program Files\Mozilla Firefox"\firefox /ProfileManager`
- Firefox starts with asking you which profile to use = Click "Create Profile.." to create a blank new one **besides** your existing one .. Call it "Test" for example
- **Uncheck** the box "Use the selected profile without asking at startup", so that next start using your favorite icon, you can come back easily to your current profile, and you do not remain on "Test"
- Click on "Start Firefox"
- You have a brand new virgin profile .. 
- Import the bookmarks from HTML (Ctrl+Shift+B ...), install BSP2 in there
- Then verify if you have the same problem

When you're done with Test, you can delete it from the profile manager, and reselect the checkbox to start with it automatically.

Let me know if things change ...

**Comment by Tarsopilami** [comment] 2019-09-01 20:46
Hi aaFn & thank you for your patience.
The machine runs on Linux Ubuntu 16.04 - so I tried to follow your instructions by creating a new profile using about:profiles, switching profile, restarting & reimporting bookmarks.

Unfortunately, it stays the same.  
Also tried the "clean firefox" option in about:support (german: Firefox bereinigen).  No change.

What do you think about trying to uninstall & reinstalling ff ?

**Comment by aaFn** [comment] 2019-09-01 21:34
Sorry, yes you had said it was Ubuntu above already, I confused with another topic :-)

Thank you for your test.
It looks like the problem is somewhere else than on FF config then.
I do not believe reinstalling would change anything.

I can be at system level, or related to your bookmarks ...
Out of curiosity, which Graphical Desktop interface do you use ? (Gnome, KDE, Mate, Xfce, ... etc ...)

Another interesting thing to do would be to start FF from a command line, and to look at error messages that could appear there .. if you have some appearing, could you log them here ?

Thanks, aaFn.

**Comment by Tarsopilami** [comment] 2019-09-01 21:47
That's an interesting possibility.  The graphical Desktop interface is Gnome Shell v.3.18.5
Could this be influencing the way firefox works ?
 
Started firefox from terminal as you suggested - but there is not a single error appearing.
So I guess the next step would be to test under a different graphical desktop ?

**Comment by aaFn** [comment] 2019-09-01 22:32
I'll try under Gnome (I am on Xfce, KDE, Mate ...) to verify.
Now Gnome 3.18 seems quite outdated ... even my RHEL seems at a later one ... Maybe upgrade to a more recent version ? (I believe the latest is 3.32)

**Comment by Tarsopilami** [comment] 2019-10-20 19:59
So in the meantime I tried the following:

> KDE plasma 
> Cinnamon DE
> uninstall & reinstall Gnome-Shell
> reset Firefox
> deactivate all other addons

When "show bookmark" is used, there is a long delay & Firefox Task manager shows Web Extension with 25% CPU usage (only addon SBMP2).  Followed by no response and a long delay before showing bookmark.  On repeating the same search it does not get faster either.  

I have 76K Bookmarks - what do you think: could this be the real issue ?

**Comment by Tarsopilami** [comment] 2019-10-24 17:46
In the meantime, disabling favicon caching solved the problem.  Everything works fine now.  Thank you for your help.

**Comment by aaFn** [comment] 2019-12-02 21:19
Closed the issue as problepm solved.
Thank you, aaFn.

**Closed by aaFn** 2019-12-02 21:19 UTC
Labels: not sure.. but fixed
