### ISSUE TITLE
Favicon fetching

### ISSUE THREAD

**Issue by andreygursky** [aaFn/Bookmark-search-plus-2#49] opened 2018-07-11 22:45 UTC
Favicon fetchig seems to consume gigabytes of RAM. If favicon fetching is enabled by default, there should be some visible feedback about the progress.

Follow-up for https://github.com/aaFn/Bookmark-search-plus-2/issues/2. Observations: about 170 MB downloaded but only small percentage of bookmarks has got a favicon.

A couple of questions:
- Actually almost all my bookmarks already have a favicon (in Firefox bookmarks), why they must be downloaded again?
- Some thousands of bookmarks are from only few domains. Does the plugin download favicon for each bookmark or for each domain?
- In order to download a favicon, is the whole web page being fetched before?

Thanks,
Andrey

**Comment by aaFn** [comment] 2018-07-11 23:48
Hello @andreygursky , what I found out is that this is not favicon fetching which consumes RAM, but saving to local store. There is nothing explaining that, I could reproduce the effect by simple experience though . I presume that something inside the FF API local storage code is consuming memory and not making it obvious enough to release quickly by the Garbage Collector ? Anyway, there appears to be nothing that can be done about it from add-on code, and I didn't find a way to force the GC to run either .. Except when the memory used by FF is close to the memory limit of the system .. which is the "memory saw" effect you see in #2. FF is really a memory hungry monster :-(

To fight against that, I implemented a mechanism of spacing saves by minimum 2s, and increasing to 20s spacing when bursts of saves are happening (i.e. when two saves are coming in less than 2s), which gives more time to the Garbage Collector to act, to decrease memory allocated to Firefox, and to keep it usable..
On my machine and others, it works well, however these values are empirical, so cannot guarantee they work well for all. Obviously, for your machine they are not conservative enough.

To answer your questions, and then I will ask some :-)
- Like native bookmarks, when a new tab is loaded or reloaded, favicon is re-fetched in case it changed since last time. It uses the favicon URL from the tab, so it is faster than normal process. In your case, tabs were all reloaded, so you were in the case of a burst of fetches .. resulting in a burst of saves. The save spacing mechanism I implemented should have protected you .. but it appears not. Maybe need to tune more.
- A favicon doesn't depend on the domain, but on the page. This is the `rel="icon"` or r`el="shortcut icon"` tag inside each page. Hence having it for the domain of one page doesn't mean it is good for another page of the same domain. We do not know until we see its URL. So have to download it perpage = per bookmark.
- Yes, to download a favicon, we have to fetch the page first to get the URL of the favicon. Then we have to fetch the favicon itself. So 2 downloads .. but only 1 save to local store, which is the piece triggering memory consumption.

The need to download and save favicons comes from a feature missing from FF bookmarks API = it doesn't give us the favicons ! So we have to download them ourselves and basically this is making storing them twice .. once by FF which keeps them for itself, and once for the add-on. Stupid, but this is how it is with FF today :-(   Several bugs open on that already, asking for the favicons, some since a long time .. not solved yet by FF.

Questions:
- In your case, things started to happen when you did the tabs reload.
How many tabs do you have, roughly ?
- Then when you disable favicons, it clears them all from local store. Next time you re-enable them, the add-on has to download them again. This is triggered around 1 minute after start, to wait for things to be stable. This continues across restart until all favicons have been fetched.
How many bookmarks do you have ? (you can see it by enabling traces in the add-on options page)
- Once you set Disable favicon fetching, no fetch and so no save occurs ... but you say that after one minute you see the effect again. Was that after re-enabling the fetch ? Or can you describe the exact sequence ?

It is true that because of slowness of the FF API on bookmarks load, I had to split the code with a piece in background to keep the tree in memory. So now since 2.0.17 a significant part of the code is running in background, of which the favicon fetching. Good news is that then it happens ony once for all FF windows now.

I may have to tune the protection mechanism further. I will also review things in light of the "tabs reload" use case. However it would be useful if you can answer the questions above.
Thanks, aaFn.

**Comment by andreygursky** [comment] 2018-07-12 19:29
> Like native bookmarks, when a new tab is loaded or reloaded, favicon is re-fetched in case it changed since last time. It uses the favicon URL from the tab, so it is faster than normal process. In your case, tabs were all reloaded, so you were in the case of a burst of fetches

"Loaded" means hopefully when user switches to the tab, not that tabs are just restored as lightweight as possible without fetching from cache / web and rendering. And thus I wouldn't expect any performance hit just like Firefox itself.

> A favicon doesn't depend on the domain, but on the page. This is the rel="icon" or rel="shortcut icon" tag inside each page. Hence having it for the domain of one page doesn't mean it is good for another page of the same domain. We do not know until we see its URL. So have to download it per page = per bookmark.

While in general I agree, but how does it look in practice? I guess most sites use the same favicon. What are your observations? Anyway I'll have to open a corresponding feature request to keep only one favicon for all pages on the same domain (especially because these favicons are really identical).

> Yes, to download a favicon, we have to fetch the page first to get the URL of the favicon. Then we have to fetch the favicon itself.

Do you retrieve only the html page (without all dependencies)? And is the download compressed?

> The need to download and save favicons comes from a feature missing from FF bookmarks API = it doesn't give us the favicons ! So we have to download them ourselves and basically this is making storing them twice .. once by FF which keeps them for itself, and once for the add-on. Stupid, but this is how it is with FF today :-( Several bugs open on that already, asking for the favicons, some since a long time .. not solved yet by FF.

I'm really wondering how NPAPI could be fully dropped, if bugs were not closed before and webextensions are far from being at least as complete as NPAPI was!? The whole data (bookmarks, favicons,...) is there but not accessible! Actually if mozilla bugtracker contains an issue named like "Drop NPAPI in favor of WebExtensions", then all the bugs you've mentioned should be there as blocking. So that NPAPI could not be dropped until the related bugs would be resolved.

Answers:
 - I guess things started to happen after Firefox auto-updated the plugin and the background task appeared. At the moment 4 windows: about 240 + 240 + 75 + 50 tabs.
-
> Then when you disable favicons, it clears them all from local store. Next time you re-enable them, the add-on has to download them again.

Would it be possible to download them incrementally and have a dedicated button "clear favicon cache"? Otherwise it will never finish on this particular laptop with 64 Kbit/s internet connection.

> This is triggered around 1 minute after start, to wait for things to be stable. This continues across restart until all favicons have been fetched.

Now it is clear, why it is enough to start Firefox and wait a bit to trigger the memory monster. So indeed incrementally. Just need separate "enabled" checkbox and "clear cache" button.

I have now 58618 and 74 folders. No tags or similar used.

*
> Once you set Disable favicon fetching, no fetch and so no save occurs ... but you say that after one minute you see the effect again.

No, one I've disabled fetching, I could continue with using Firefox.

> Was that after re-enabling the fetch ? Or can you describe the exact sequence ?

On this 4 GB laptop I cannot re-enable fetch (and continue normally using Firefox) until you would change something so that I could test it.

> Good news is that then it happens ony once for all FF windows now.

That's good. Just in my use case (without 8 GB of RAM) I'm forced to be able to explicitly enable and disable the plugin. Maybe just add something like "enable background only upon showing plugin"?

Thanks for forwarding bugs to Mozilla! BTW, what is the bug with access to favicons? I'd like to follow it.

**Comment by andreygursky** [comment] 2018-07-12 22:44
FYI: bookmarkbackups/bookmarks-2018-07-12...==.jsonlz4 occupies only 6.5 MB. I'm looking now for some easy way to unpack this modified lz4 named mozlz4. But anyway there will be a couple of dozens MB. How this becomes a couple of GB is a mystery. Favicons are also small: few KB.

**Comment by aaFn** [comment] 2018-07-12 23:04
Hello @andreygursky ,
- Loaded means when there is an explicit refresh / reload on an existing tab, or when a new tab is opened, or when you click on a new link inside a tab. But not when an existing tab is selected
See `browser.tabs.onUpdated.addListener()` https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/tabs/onUpdated
- You are most probably right .. however I cannot be approximative ... just have to mimick what the native bookmark sidebar is doing .. :-) If there is only one page different, I cannot miss it .. and there is no way to know until loading the favicon URL.
- I retrieve **only** the HTML page, and I wrote a very fast parser of my own .. not exactly perfect (there's a todo on it with regards to comments), but doing the job 99.99% of the time .. I will improve it later.
Don't know if the doanload is compressed, this is using the standard fetch() method from the FF API .. not view on how it works.
- Yes, that is really a pity. Here are two one, but there are others ...
https://bugzilla.mozilla.org/show_bug.cgi?id=1315616
https://bugzilla.mozilla.org/show_bug.cgi?id=1411120
- Do you know what provoked the error which made you do History -> Restore previous session ? Now I understand the pain, you had 600 fetches at once ... the protection mechanism should have been acting though. I will try to tune a version with higher values for you, if you can try it out.
As I said, this is empirical .. :-(
- And now that you have enabled the "Disable favicon fetching" option, this has cleared the cache ... this is the way to do it by the way, no need for a "Clear cache" button.
- So when disabling the option, it restart the fetch favicons for all your 58000 or so bookmarks .. at the rhythm of 5 per second max (I throttled taht also ..). But as I said, the memory hungry monster is when we save to local store, not when we fetch().
- I can also add a "slow down favicon fetching" option and put higher spacing numbers so that this is slow in background in your case, and not impacting .. again we will have to tune.
- There's no way to control the background task ... as long as you keep the "Disable Favicon Fetching" option set, the backgrounjd task should stay quiet though .. let me know if not.
- On your last point, favicon can be very big .. this is why I implemented a feature of 16x16 conversion in the add-on ... this is gaining a lot of room in storage .. !! :-)

**Comment by andreygursky** [comment] 2018-07-13 17:04
> onUpdated()

> This includes the url, but also potentially the title and **favIconUrl** properties.

Availability of the last property sounds very good.

> Don't know if the download is compressed, this is using the standard fetch() method from the FF API

Thanks for the links!

For example: https://bugzilla.mozilla.org/show_bug.cgi?id=1315616 (bad thing: mozilla's server doesn't compress the page even if requested. Who knows how many servers do not compress either?..):
* favicon size: 1150
* html web page size: about 158538 bytes 

This results in efficiency of 0.73% (1150/158538*100). It is incredibly inefficient.

* minimal size to obtain favicon URL: 8676 bytes

Provided FF allows fetching in chunks of say 1400 bytes: 9800 bytes would be needed. Efficiency: 11.73%. Hmm...

> Do you know what provoked the error which made you do History -> Restore previous session ?

Nothing happened. Unless I have not too many tabs, it is a way how I continue using Firefox after restart.

> And now that you have enabled the "Disable favicon fetching" option, this has cleared the cache ... this is the way to do it by the way, no need for a "Clear cache" button.

If user temporary needs to disable favicon fetching and then enables it again, why must the plugin delete all the data just to start with redownloading all the thousands of web pages again some time later? Wouldn't it be better to let the user choose between just enable/disable and clear cache as I mentioned before?

> I can also add a "slow down favicon fetching" option

Thanks but I'd be able to test it only if the mentioned enable/disable fetching and https://github.com/aaFn/Bookmark-search-plus-2/issues/51 could be resolved.

**Comment by andreygursky** [comment] 2018-07-13 18:42
I'm thinking now, what about to find out, where favicon data is stored. Shutdown FF and copy it over to the place where BSP2 it stores.

**Comment by andreygursky** [comment] 2018-07-13 18:49
The first part was easy to find: avicons.sqlite.

**Comment by andreygursky** [comment] 2018-07-13 18:50
There is a column data. Thus it would be easy to obtain statistic about favicon sizes.

**Comment by andreygursky** [comment] 2018-07-13 19:11
And for BSP2 I guess this is the place: browser-extension-data/bookmarksearchplus2@aafn.org/storage.js.

it is 19 MB for now.

**Comment by aaFn** [comment] 2018-07-13 19:34
"Disable favicon fetching" was invented for this guy https://github.com/aaFn/Bookmark-search-plus-2/issues/30
and his problem is that he didn't want favicons .. full stop .. :-) So i prefer not to change it.

Then maybe I could add an option, exclusive with DFF, which is "Pause favicon fecthing" ? That would do what you want, but not lose the favicons. Need to think if easy to manage with the other one ..

On importing from the sqlite DB of FF, that is an idea, but that cannot be done from the add-on.
That must be done by an external program run by the user ... because the add-on does not have access to such things on the disk.

On optimizing storage.js, yes, could be an idea .. requires to store favicons separately from the rest though, which is then affecting performances for display .. this is critical and what we've been optimizing lately .. so not sure I want to go there for now .. :-)

**Comment by andreygursky** [comment] 2018-07-13 19:46
> "Disable favicon fetching" was invented for this guy

Those users :)

> Then maybe I could add an option, exclusive with DFF, which is "Pause favicon fecthing" ? That would do what you want, but not lose the favicons. Need to think if easy to manage with the other one ..

Yes, this sounds good. Maybe ask the guy, whether it would be OK for him to have enable/disable and clean cache separately?

> That must be done by an external program run by the user

Yes, this part is what I guess I'd need to look into myself.

> performance

What display performance issues did you (and/or other users?) encounter that suggested to put data so tight?

In storage.js the only data which might be frequently updated (even in bursts) is icon data. So storing it separately should even gain performance.

And because of caching if for displaying of many equal icons the same data will be used, this should also positive affect the performance.

**Comment by aaFn** [comment] 2018-07-13 21:45
The problem of performance was on display, see #2 and #5 ... It is now not far from its best I believe.
For people with around 2000 bookmarks, this was starting to show, for people with 10000, this was one of the significant factors with the FF API load of bookmarks, and with people having 80000+ (yes there are :-) ), this was very significant and I could reduce it by a factor of 3 to 4.
In your case, with around 60000 bookmarks, you should also have noticed much improvement by the way ...

I had to resort to clone techniques, smithing every line of code .. etc ... so for making the favicon a separate object, I would need to think carefully as this would introduce an indirection step in the middle.

Also there would be the problem of detecting that two favicons are the same. URL is not sufficient, that should probably be based on a hash to avoid an algorithm in N when trying to see if it already exists ...

Anyway, something for another time .. when this optimization round we just finished is properly stabliized ..

**Comment by aaFn** [comment] 2018-07-14 17:36
Hello @andreygursky , I am publishing 2.0.29 with:

- Increased local store save spacing to try to not trigger the memory hungry monster in your config :-)
- An optimization to not save a favicon when it is the same as before when a tab is reloaded. That should avoid the effect you got when doing History -> Restore previous session.
- An option to Pause the favicon fetches.
It is a radio button, that you can switch between Active and Pause, effective immediately (i.e. Pause stops immediately, and Activate restarts it immediately).
It keeps the already fetched favicons, so no danger.
Activating "Disable favicon fetching" disable those radio buttons (and clears the cache of favicons as before, but now I indicate it as a warning on the options panel).

Let me know how that is going. If ok, we should close that issue, and let #51 open for verifying if we need to add a throttling feature or not to all that ..

**Comment by aaFn** [comment] 2018-07-19 09:53
Hello @andreygursky , any update on your side ? Are you good with theimprovements and the new functions, and in particular the pause and memory consumption ?

**Comment by andreygursky** [comment] 2018-07-19 14:34
Thanks for your optimizations!

Some statistics about memory usage:

* just after Firefox has started:
```
$ ps aux | grep -e RSS -e firefox -e WebC
PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
17296  2.5  9.8 2345632 393512 pts/3  Sl+  15:58   0:10 firefox
17480  0.1  2.7 1637328 110120 pts/3  Sl+  15:58   0:00 /usr/lib/firefox/firefox -contentproc -childID 1 -isForBrowser -prefsLen 25723 -schedulerPrefs 0001,2 -greomni /usr/lib/firefox/omni.ja -appomni /usr/lib/firefox/browser/omni.ja -appdir /usr/lib/firefox/browser 17296 true tab
17598  0.0  2.2 1563684 87628 pts/3   Sl+  15:58   0:00 /usr/lib/firefox/firefox -contentproc -childID 2 -isForBrowser -prefsLen 25727 -schedulerPrefs 0001,2 -greomni /usr/lib/firefox/omni.ja -appomni /usr/lib/firefox/browser/omni.ja -appdir /usr/lib/firefox/browser 17296 true tab
```

* after clicking on BSP2 plugin:
```
$ ps aux | grep -e RSS -e firefox -e WebC
PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
17296  5.8 18.9 2792892 753960 pts/3  Sl+  15:58   0:31 firefox
17480  0.1  2.7 1637328 110120 pts/3  Sl+  15:58   0:00 /usr/lib/firefox/firefox -contentproc -childID 1 -isForBrowser -prefsLen 25723 -schedulerPrefs 0001,2 -greomni /usr/lib/firefox/omni.ja -appomni /usr/lib/firefox/browser/omni.ja -appdir /usr/lib/firefox/browser 17296 true tab
17598  0.0  2.2 1563684 87628 pts/3   Sl+  15:58   0:00 /usr/lib/firefox/firefox -contentproc -childID 2 -isForBrowser -prefsLen 25727 -schedulerPrefs 0001,2 -greomni /usr/lib/firefox/omni.ja -appomni /usr/lib/firefox/browser/omni.ja -appdir /usr/lib/firefox/browser 17296 true tab
```

So to render 19 MB storage.js about 352 MB are needed. Still quite a lot. But loading itself was relatively fast:
```
PlatformOs: linux
Setting Linux variations
Load local store duration: 27 ms
Background load local store duration: 5484 ms
Background bypassed FF API for tree load
Background tree load duration: 57 ms
Background tree build duration: 48 ms
Background save duration: 438 ms
Get tree duration: 1 ms
structureVersion: -img16-bnlist
disableFavicons_option: true
pauseFavicons_option: false
Display duration: 5650 ms
Total duration: 5678 ms
fontFamily = 'Sans'
fontSize   = '12px'
Stats:
------
Bookmarks:  58602
Folders:    74
Separators: 1
Oddities:   0
--------------------
BSP2 version: 2.0.29
```

This was with disabled favicon fetching. Let's see how it looks with enabled...

**Comment by andreygursky** [comment] 2018-07-19 14:58
The saw like memory consumption is present. Sometimes the peaks are relatively high (GB just to save some KB). And I cannot find some progress indicator like favicons fetched / total. In my particular case I'll have to disable it. Good, that the already fetched data will not vanish anymore :)

While using .js for storing some preferences is OK, I don't understand how Mozilla could drop access to sqlite storage for addons to save any other data.

**Comment by aaFn** [comment] 2018-07-19 22:04
Me neither ...
Sorry that the memory saw problem is still there .. I have been fighting against that monster for some time now, I've been successflul on my system and many others, but not on yours then .. :-(

Progress indicator = this is more work, here I tried to go to your immmediate need, which was to give you the pause function.
With that, you can pause when you are working, and then activate when you are away .. and re-pause when you come back .. that at least should give you relief and useablity.

**Comment by aaFn** [comment] 2018-07-21 14:45
2.0.30 is out with stats in the add-on Options panel, and a progress indicator (0.0% means no more favicons to fetch, 100% means all favicons to fetch).

Let me know if ok for you, and I will close this issue. Thanks, aaFn.

**Comment by aaFn** [comment] 2018-07-28 14:21
Hello @andreygursky , supposing all is ok, I am closing that issue.
Come back on #51 if not.

Thanks, aaFn.

**Closed by aaFn** 2018-07-28 14:21 UTC

**Comment by andreygursky** [comment] 2018-11-01 23:32
@aaFn, thanks! It looked very good back to that time!

I haven't been using plugin for a while, especially since Firefox warned me about additional permissions: "Access browsing history". What is it for? I was looking through last commits, but it seems this repository is not anymore up to date?

**Comment by andreygursky** [comment] 2018-11-07 21:46
@aaFn, thanks for pointing out the wiki pages with detailed information!

Now couple of days with activated BSP2, new bookmarks I've added during BSP2 was deactivated still have not appeared.
