### ISSUE TITLE
 The "show parent folder" function urgently needed.

### ISSUE THREAD

**Issue by minshifu** [aaFn/Bookmark-search-plus-2#96] opened 2019-05-03 11:08 UTC
Thank you for your work. Could you pls enhance the "show parent folder" function by embedding it in the Bookmarks Management Panel as shown by the picture below? If possible, could you pls also add the "reverse folder hierarchy" function shown below? You can refer to the addon "show parent folder" herein attached. The function is urgently needed. Thank you and best wishes!

![2019-05-03_185714](https://user-images.githubusercontent.com/5119952/57133695-302a0580-6dd6-11e9-9952-fe5aee36af73.png)

![2019-05-03_185759](https://user-images.githubusercontent.com/5119952/57133703-391ad700-6dd6-11e9-84a2-adbe534b6625.png)

[showParentFolder.zip](https://github.com/aaFn/Bookmark-search-plus-2/files/3141583/showParentFolder.zip)

**Comment by aaFn** [comment] 2019-05-04 03:50
Hello @minshifu, with the new WebExetension API from FF 57 (Quantum) and upper, it is not (yet ?) possible to modify the display of the Bookmarks Library, and in particular to add a new column "Parent folder" like alice0775 could do with its old XUL extension add-on.
This is a security feature from FF .. so this must be seen as a limitation for our good.

However, there's now a possibility since FF65 :-)
I started to use it with version 2.0.50 of BSP2 ., so you have it. it is called "Menu extension" in the FF API, and it is contextual.

To use it from the Bookmarks Library, simply right click on any bookmark item in the big pane with the columns, and you will see in the context menu a BSP2 added submenu, called "Path to bookmark item".
- Click on it ..
- and you will see the full path to the bookmark item, from root, with each parent separated by a ">"

This is the best I can do for now on that function.

---------------------------------------------------------

On the reverse hierarchy, indeed  that could be useful.
I can propose to you 2 choices:
1. Add another BSP2 context submenu (I need to verify I can have more than one), which I would call "Reverse path" for example.
2. Or add an option in the add-on options page, to reverse the displayed values in the submenu.
This would affect all of course.

Which one would you prefer ?

**Comment by minshifu** [comment] 2019-08-02 01:32
Really sorry, I've been very preoccupied recently and forgot to update this issue. Thank you for your kind reply and explanation. Could you kindly realize "jump to the parent folder" function in the bookmark management panel? Besides, after going to the parent folder, can the original bookmark be automatically selected or highlighted? Or it would get lost in other bookmarks very easily. It'd be greatly appreciated.  Best regards!

![图片](https://user-images.githubusercontent.com/5119952/62337335-c91c0a00-b506-11e9-9bbb-f5fa294ee4fb.png)

**Comment by aaFn** [comment] 2019-08-11 21:17
Hello @minshifu , alas it is not possible to interact within the Bookmark Library from WebExtension add-ons. So it is not possible today for an add-on like BSP2 to do what you would like.

On your previous demand, I am adding in 2.0.65 a new option "Reverse folder hierarchy in paths", that will allow to show thing in reverse order, effective in BSP2 Property popups, and in the native Bookmark sidebar, Bookmark Library and Toolbar bookmark context submenus.

**Comment by minshifu** [comment] 2019-08-12 03:30
Thank you for your kind reply. Maybe you could let BSP2 interface float instead of being confined to the sidebar. Many people sure would like a more versatile alternative to the built-in bookmark manager.  Or could you at least add a "Add the current tab as bookmark" function as shown by the picture ( above or below the right-clicked bookmark) ?   Thank you and best regards!
![图片](https://user-images.githubusercontent.com/5119952/62844473-32183480-bcf4-11e9-9970-76961a03c60e.png)

**Comment by aaFn** [comment] 2019-08-12 08:26
Hello @minshifu , making it float is in fact opening it in a browser window = add-ons cannot anymore open their own dedicated window.
There is alreay a way to do that today, although not so visible yet, I will improve that:
- Right click on the magnifying glass, a special "hidden" menu will appear, with the action "Open BSP2 in a tab".
- Click on it and it will create a new tab with BSP2 running in it
- From there you can drag & drop to the sidebar and vice versa, which allows you to reorganize things
- Or you can do that after pressing Ctrl+N to open a new browser window first, which will be the floating window (and hide the sidebar of that windiw)
- Or you can drag the tab out of Firefox, and Firefow will create a new window and transfer that tab in it

For add current tab as bookmark to the place you want, there are already several ways to do that, all based on dfrag and drop:
- Drag the current tab index (at top) to the bookmark tree
- Drag the (i) in the address bar to the bookmark tree
- Click in the address bar (this will highlight the address) and drag it to the bookmark tree

Note: the current context menu being quite loaded already, I am studying the possiblity to add a submenu for such less used functions, but not sure when I would do that yet.

**Comment by minshifu** [comment] 2019-08-14 11:22
Thank you so much for your kind explanation. It works greatly.  If you could combine the original columns of the current bookmark manager with that of parent folder and produce a standalone alternative, that would be perfect and very desirable for many people. Hope you can make it.  Thank you again and best regards!

**Comment by aaFn** [comment] 2019-08-30 21:46
Hello @minshifu, glad it works well.
On you rlast demand, I do not think I will go into reproducing in BSP2 the Bookmark Library screen, this is really too much work ... Maybe somebody will create an add-on specific for that later.

Anyway, closing the issue as done since at least thereverse hierarchy function was possibole to do, and is now in BSP2 2.0.65.

Thank you, aaFn.

**Closed by aaFn** 2019-08-30 21:46 UTC
Labels: enhancement
