### ISSUE TITLE
Possible conflict with QuickBookmarkToFolder extension?

### ISSUE THREAD

**Issue by mlncn** [aaFn/Bookmark-search-plus-2#299] opened 2024-03-07 01:07 UTC
QuickBookmarkToFolder - https://addons.mozilla.org/en-US/firefox/addon/quick_bookmark_to_folder/ - seems to have stopped working after adding Bookmark Search Plus 2:  It still shows its icon and selecting a folder causes the tab to close, but the bookmark does not appear in that folder or anywhere.

These extensions would be fantastic working together— that one to quickly send a tab to a specific bookmark folder, and yours to quickly find the folder when it's time to bring the bookmark up!

Correlation ≠ causation of course, but any quick thoughts?  Thanks!

**Comment by aaFn** [comment] 2024-03-07 09:19
Hello @mlncn , I tested, and this works on my side ..

Note: I found a regression in my code which I just corrected and published (in 2.0.125), but this was only a minor display error on non mainstream code, triggered by the action of adding a new bookmark outside of BSP2, like when using QuickBookmarkToFolder. So I do not think this was at the origin of the problem that you are seeing.

What do you mean by "seems to have stopped working" ?
Is it that the bookmark is not created, or not at the place you want, by QuickBookmarkToFolder ? Or simply that the result was not immediately displayed in BSP2 ? (in that case, the fix I just made might improve things)

**Comment by aaFn** [comment] 2024-05-10 22:57
Closing for now because I can't reproduce, please reopen with more details if/when you have them.
Thank you, aaFn.

**Closed by aaFn** 2024-05-10 22:57 UTC
