### ISSUE TITLE
Stuck in Wait background load in Firefox 130

### ISSUE THREAD

**Issue by nton** [aaFn/Bookmark-search-plus-2#313] opened 2024-09-16 07:16 UTC
This wonderful tool stopped workin on Firefox 130. "Wait background load.." is the message and a small icon showing a circle keeps working for hours.
At first I thought its because of my work environment - FF is under corporate IT. But then in my home PC, same windows 10 - ff 130 version, the same thing happened. I have thousands of bookmarks and now I feel helpless ... 
Please take a look !!!  

Thank you so much for all these years of support !!!

**Comment by aaFn** [comment] 2024-09-16 14:45
Hello @nton , can you apply the procedure here https://github.com/aaFn/Bookmark-search-plus-2/wiki/Getting-and-providing-logs-for-debugging-BSP2, and place the output in this thread ?

Also, you if can activate traces in the BSP2 options, and copy the content of the little trace text area here ..

Let's see what is happening on your side, all is ok on my FF 130.0.

By the way, on which OS/version are you ?

**Comment by nton** [comment] 2024-09-19 09:57
Firth the Multiprocess Browser COnsole output , when BSP2 is disabled-enabled: 
ExpandableSection: The toggleId value must be passed in and must match the toggleId of the ExpandableSectionToggle. 5 13760.697c4f23e2301662.js:2:536676
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. background.js:1
ExpandableSection: The toggleId value must be passed in and must match the toggleId of the ExpandableSectionToggle. 5 13760.697c4f23e2301662.js:2:536676
ExtensionPreferencesManager API ftpProtocolEnabled created but addSetting was not called.
Request to access cookie or storage on “https://d.la4-c1-ia4.salesforceliveagent.com/chat/rest/Visitor/Availability.jsonp?sid=undefined&r=911&Availability.prefix=Visitor&Availability.ids=[5736R000000wk2n]&callback=embedded_svc.liveAgentAPI.connection.handlePing&deployment_id=5726R000000sXtR&org_id=00DA0000000HxWH&version=48” was blocked because it came from a tracker and content blocking is enabled.
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. background.js:1
ExpandableSection: The toggleId value must be passed in and must match the toggleId of the ExpandableSectionToggle. 5 13760.697c4f23e2301662.js:2:536676
Request to access cookie or storage on “https://d.la4-c1-ia4.salesforceliveagent.com/chat/rest/Visitor/Availability.jsonp?sid=undefined&r=230&Availability.prefix=Visitor&Availability.ids=[5736R000000wk2n]&callback=embedded_svc.liveAgentAPI.connection.handlePing&deployment_id=5726R000000sXtR&org_id=00DA0000000HxWH&version=48” was blocked because it came from a tracker and content blocking is enabled.
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. background.js:1
ExpandableSection: The toggleId value must be passed in and must match the toggleId of the ExpandableSectionToggle. 5 13760.697c4f23e2301662.js:2:536676
Could not find any MenuItem with id: root background.js:1:512
Could not find any MenuItem with id: autofill background.js:1:512
Could not find any MenuItem with id: root background.js:1:512
Could not find any MenuItem with id: autofill background.js:1:512
Cookie warnings 2
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. background.js:1
WindowsJumpLists: Failed to fetch favicon for  https://npvmgncs02.illab.us.alcatel-lucent.com/status/result.php NS_ERROR_FAILURE: WindowsJumpLists.sys.mjs:257:29
WindowsJumpLists: Failed to fetch favicon for  https://athitcl05.athmg.eecloud.dynamic.nsn-net.net/status/result.php NS_ERROR_FAILURE: WindowsJumpLists.sys.mjs:257:29
WindowsJumpLists: Failed to fetch favicon for  http://10.84.254.58:8081/builder NS_ERROR_FAILURE: WindowsJumpLists.sys.mjs:257:29
Load saved state..

background.js:143:10
IndexedDB UnknownErr: ActorsParent.cpp:575
UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. ExtensionStorageIDB.sys.mjs:841
libstore error on loading from local storage 3 : Error: An unexpected error occurred (retries left: 9) libstore.js:462:13
fileName:   undefined libstore.js:466:14
lineNumber: 0 libstore.js:467:14
uncaught exception: null
IndexedDB UnknownErr: ActorsParent.cpp:575
UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. ExtensionStorageIDB.sys.mjs:841
libstore error on loading from local storage 3 : Error: An unexpected error occurred (retries left: 8) libstore.js:462:13
fileName:   undefined libstore.js:466:14
lineNumber: 0 libstore.js:467:14
uncaught exception: null
ExtensionPreferencesManager API ftpProtocolEnabled created but addSetting was not called.
IndexedDB UnknownErr: ActorsParent.cpp:575
UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. ExtensionStorageIDB.sys.mjs:841
libstore error on loading from local storage 3 : Error: An unexpected error occurred (retries left: 7) libstore.js:462:13
fileName:   undefined libstore.js:466:14
lineNumber: 0 libstore.js:467:14
uncaught exception: null
IndexedDB UnknownErr: ActorsParent.cpp:575
UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. ExtensionStorageIDB.sys.mjs:841
libstore error on loading from local storage 3 : Error: An unexpected error occurred (retries left: 6) libstore.js:462:13
fileName:   undefined libstore.js:466:14
lineNumber: 0 libstore.js:467:14
uncaught exception: null
IndexedDB UnknownErr: ActorsParent.cpp:575
UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. ExtensionStorageIDB.sys.mjs:841
libstore error on loading from local storage 3 : Error: An unexpected error occurred (retries left: 5) libstore.js:462:13
fileName:   undefined libstore.js:466:14
lineNumber: 0 libstore.js:467:14
uncaught exception: null
ExpandableSection: The toggleId value must be passed in and must match the toggleId of the ExpandableSectionToggle. 13760.697c4f23e2301662.js:2:536676
IndexedDB UnknownErr: ActorsParent.cpp:575
UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. ExtensionStorageIDB.sys.mjs:841
libstore error on loading from local storage 3 : Error: An unexpected error occurred (retries left: 4) libstore.js:462:13
fileName:   undefined libstore.js:466:14
lineNumber: 0 libstore.js:467:14
uncaught exception: null
ExpandableSection: The toggleId value must be passed in and must match the toggleId of the ExpandableSectionToggle. 2 13760.697c4f23e2301662.js:2:536676
IndexedDB UnknownErr: ActorsParent.cpp:575
UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. ExtensionStorageIDB.sys.mjs:841
libstore error on loading from local storage 3 : Error: An unexpected error occurred (retries left: 3) libstore.js:462:13
fileName:   undefined libstore.js:466:14
lineNumber: 0 libstore.js:467:14
uncaught exception: null
IndexedDB UnknownErr: ActorsParent.cpp:575
UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. ExtensionStorageIDB.sys.mjs:841
libstore error on loading from local storage 3 : Error: An unexpected error occurred (retries left: 2) libstore.js:462:13
fileName:   undefined libstore.js:466:14
lineNumber: 0 libstore.js:467:14
uncaught exception: null
IndexedDB UnknownErr: ActorsParent.cpp:575
UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. ExtensionStorageIDB.sys.mjs:841
libstore error on loading from local storage 3 : Error: An unexpected error occurred (retries left: 1) libstore.js:462:13
fileName:   undefined libstore.js:466:14
lineNumber: 0 libstore.js:467:14
uncaught exception: null
IndexedDB UnknownErr: ActorsParent.cpp:575
UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. ExtensionStorageIDB.sys.mjs:841
libstore error on loading from local storage 3 : Error: An unexpected error occurred (retries left: 0) libstore.js:462:13
fileName:   undefined libstore.js:466:14
lineNumber: 0 libstore.js:467:14
Attempting to clear local storage, which will reset all values to default ! libstore.js:479:15
uncaught exception: null
IndexedDB UnknownErr: ActorsParent.cpp:575 2
UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. ExtensionStorageIDB.sys.mjs:841
Clear of  local storage failed : Error: An unexpected error occurred - ending there :-( libstore.js:490:17
Error on loading from local storage : undefined background.js:3586:10
uncaught exception: null
ExpandableSection: The toggleId value must be passed in and must match the toggleId of the ExpandableSectionToggle. 2 13760.697c4f23e2301662.js:2:536676
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. background.js:1
ExpandableSection: The toggleId value must be passed in and must match the toggleId of the ExpandableSectionToggle. 5 13760.697c4f23e2301662.js:2:536676
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. background.js:1

**Comment by nton** [comment] 2024-09-19 10:11
Hello, thank you for your reply and instructions. I'm attaching the file of console:

[console-export-2024-9-19_13-0-39.txt](https://github.com/user-attachments/files/17057386/console-export-2024-9-19_13-0-39.txt)

**Comment by aaFn** [comment] 2024-09-19 11:49
Bad news, your local storage is corrupted in some way, external to BSP2, and BSP2 cannot anything about it, it tried all it could, including clearing the local storage.
=> you have to clear the BSP2 add-on storage yourself ... and the only way I know of is to remove the add-on (here BSP2), and reinstall it 😢 

I will modify the code to add a notification popup instructing the user on what to do when reaching such a case, to make that more explicit.

```
libstore error on loading from local storage 3 : Error: An unexpected error occurred (retries left: 1) libstore.js:462:13
fileName:   undefined libstore.js:466:14
lineNumber: 0 libstore.js:467:14
uncaught exception: null
IndexedDB UnknownErr: ActorsParent.cpp:575
UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. ExtensionStorageIDB.sys.mjs:841
    normalizeStorageError resource://gre/modules/ExtensionStorageIDB.sys.mjs:841
    method chrome://extensions/content/child/ext-storage.js:286
    AsyncFunctionThrow self-hosted:811
libstore error on loading from local storage 3 : Error: An unexpected error occurred (retries left: 0) libstore.js:462:13
fileName:   undefined libstore.js:466:14
lineNumber: 0 libstore.js:467:14
Attempting to clear local storage, which will reset all values to default ! libstore.js:479:15
uncaught exception: null
IndexedDB UnknownErr: ActorsParent.cpp:575
UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. ExtensionStorageIDB.sys.mjs:841
    normalizeStorageError resource://gre/modules/ExtensionStorageIDB.sys.mjs:841
    method chrome://extensions/content/child/ext-storage.js:286
    AsyncFunctionThrow self-hosted:811
Clear of  local storage failed : Error: An unexpected error occurred - ending there :-( libstore.js:490:17
Error on loading from local storage : undefined background.js:3586:10
IndexedDB UnknownErr: ActorsParent.cpp:575


```

**Comment by aaFn** [comment] 2024-09-19 11:50
An additional thought: if the error appeared in two different FF instances at around the same time, in two different environments, look for some common external factor which could provoke that .. (external = outside of BSP2)

**Comment by nton** [comment] 2024-09-19 17:59
Hi,
thank you very much. Re-installing solved the issue.
Lost favicons is a temp collateral loss -slowly fetching 23k icons. Would 'Dual save' option help in re-installing?

-I'm not sure if I can comment on the RC of local storage corruption: It was not about the same time, different days for sure. What is in common is the quite strict antivirus pkgs and rules; both in my corporate laptop (win defender/antimalware) and home pc (kaspersky). I experience sporadic timeouts openning e.g. the downloads folder in the former and issues/delays on the protected FF instance in the latter. Not sure if it could be related at all though..

Once again thank you for this wonderful application. Not many people keep a structured Bookmark Content Sidebar but those who do really appreciate the unparalleled functionality of BSP2 !!

**Comment by aaFn** [comment] 2024-09-22 21:47
I now added a notification popup in 2.0.130 to let the user know of the situation, and to advise directly on the uninstall/reinstall method to cure the problem.

![image](https://github.com/user-attachments/assets/80a7ea64-150b-4463-81a1-3c90609e1802)

**Comment by aaFn** [comment] 2024-09-22 21:48
Closing since the problem is now fixed.

**Closed** 2024-09-22 21:49 UTC
Labels: enhancement, question
