### ISSUE TITLE
Favicon display issue for Google Codelabs

### ISSUE THREAD

**Issue by Arachnopod** [aaFn/Bookmark-search-plus-2#125] opened 2020-01-20 15:31 UTC
BSP2 is setting/resetting the favicon for Google Codelabs to the generic icon.  After BSP2 has updated favicons, clicking on any Google Codelabs link in the BSP2 sidebar will result in the proper loading of its usual icon (a bluish-gray "<>" symbol).

Also, if you get ahead of the BSP2 favicon update and click a Google Codelabs link and set it to "<>", when the BSP2 favicon sweep hits that link in the sidebar, it'll reset it to the generic link icon and not honor the icon already set.  Of course, manually clicking the link again will set it back to "<>". 

Here are a couple example links:
    https://codelabs.developers.google.com/android-kotlin-fundamentals/
    https://codelabs.developers.google.com/codelabs/android-room-with-a-view-kotlin/index.html?index=..%2F..index#0

**Comment by aaFn** [comment] 2020-02-09 23:04
Thanks. Well, for me all is correct on these 2 ones = when I bookmark them, I get the correct favicons in BSP2 (they are slightly different, the first one is a bigger gray <>", and the second one a smaller bluish-grey  "<>".

When reloading the tabs, nothing changes, all remains correct.

So I never get the generic icon. Not sure of the sequence you are following then which results in the generic favicon. Could you describe step by step the actions that you are doing which lead to the generic favicon, so that I can reproduce and investigate ?

Thanks, aaFn.

**Comment by aaFn** [comment] 2020-03-01 16:54
Closing the issue as I can't reproduce.

**Closed by aaFn** 2020-03-01 16:54 UTC
Labels: invalid
