### ISSUE TITLE
Adding bookmark inside the bookmarks tree not indicated sometimes

### ISSUE THREAD

**Issue by vitaaliy** [aaFn/Bookmark-search-plus-2#99] opened 2019-05-10 19:05 UTC
Hi aaFn,
Thank you one more time for the great work you have done :). But now I have to report a very peculiar thing. I have BSP2 2.0.59, FF 66.0.5 (64). BSP2 tree is opened, I try to insert into it a new bookmark. After that I check now the blue star at the address field - right, my new bookmark has got into the designated folder. But it is not shown in the BM left panel. If I switch to the FF BM tree - it is in its place. If I return again to the BSP2 - also correct indication. This effect originates not always - but only sometimes... though being somewhat irritating.

**Comment by aaFn** [comment] 2019-05-11 14:33
Hello @vitaaliy, I guess this is when you use the menu in the address bar ?
I tried and indeed I could reproduce the problem only once on my side, but no more happening.
=> Hard to catch .. I will continue to try and tell you.

**Comment by vitaaliy** [comment] 2019-05-11 20:40
Hi, aaFn,
I am not quite sure that correctly got your phrase: … _this is when you use the menu in the address bar_. At the top of the screen, I have FF menu (File, Edit, View...). Then go tabs... lower is the address bar and addon icons. Next horizontal row is Bookmarks top-level folders. BM tree is as the left sidebar.
I have a habit to drag the current link from the address bar right to its destination to BSP2 left sidebar. Then sometimes it works OK, and sometimes I cannot see the result of its insertion... The same trick when done with the native BM left bar - is always successful.
I feel that this peculiarity appeared not very long ago - before this insertion worked as expected.
The subconscious feeling I get is: sometimes after BK insertion you fail to reread the new state of the pertinent tree fragment.
Waiting for news from you

**Comment by aaFn** [comment] 2019-05-12 15:49
Yes, since FF 65/66 there are some things happening differently than before:
- some notifications do not seem to appear in the same order or as fast as before when coming from FF to BSP2
- sometime BSP2 is even going faster than FF in processing things resulting in de-synchros because things lost (not saved) by FF, but executed and saved by BSP2

I tried to implement a bit of robustness in 2.0.60 to those de-synchros, and couldn't reproduce the problem anymore on my side although intensively dragging / inserting bookmarks.
2.0.60 is out, let me know if things are better on your side.

**Comment by vitaaliy** [comment] 2019-05-12 16:37
BSP2 v.59 wouldn't upgrade itself to v.60 - I deleted it manually and downloaded v.60. Now let us see if it will help. Thank you for your prompt reaction :)

**Comment by vitaaliy** [comment] 2019-05-12 21:28
Alas, no... Our synchro-failures remained...

**Comment by aaFn** [comment] 2019-05-12 21:40
Not sure what is happening.
Could you open the browser console (CTRL+SHIFT+J), and when you see the error occur, copy here the most recent contents of it ? (let's say the last 100 lines max)

**Comment by vitaaliy** [comment] 2019-05-14 20:34
Hmmmm... I looked there at the time I
[Browser Console.docx](https://github.com/aaFn/Bookmark-search-plus-2/files/3179756/Browser.Console.docx)

 saw your comment and was frightened by the picture I saw. Look there yourself, and I will send you the next protocol when I notice the failure.

**Comment by aaFn** [comment] 2019-05-14 21:58
Thanks. Indeed, I see nothing related to BSP2 for now in there.
Let's wait for next time you observe the problem ..

**Comment by vitaaliy** [comment] 2019-05-15 16:49
Several times I have pulled the BM pointer to the exact place in BSP2 tree - nothing wrong happened. But now I clicked the star in the address field and directed insertion point with the help of official dialog. And lo, - this bad situation: the star itself became blue - as always happen due BM insertion, but the tree visually did not change. I opened the Browser Console, copied it and prepared to send you. Then I switched to the native FF BMs - inserted BM really has got to its destination.
[Browser Console.docx](https://github.com/aaFn/Bookmark-search-plus-2/files/3183561/Browser.Console.docx)

**Comment by aaFn** [comment] 2019-05-15 18:22
Thanks. the only thing i see so far in there which could be relevant is

> Type error for parameter query (Value must either: be a string value, or .url must match the format "url") for bookmarks.search. common.js:94

Could you let me know the URL of the page you were trying to insert ?

**Comment by vitaaliy** [comment] 2019-05-15 18:26
Of course: https://newsland.com/user/132871456/content/bulat-okudzhava-predatel-medlenno-dushivshii-rossiiu/5492452?utm_source=24smi.info&utm_medium=referral&utm_campaign=1324&utm_content=1049868&utm_term=2543

**Comment by aaFn** [comment] 2019-05-15 21:53
So no, doiesn't seem to be it .. Out of curiosity, did you have a search result open while doing the bookmarking ?

**Comment by vitaaliy** [comment] 2019-05-15 22:15
I do not remember... Search results are very helpful when finding the needed folder, so, I suspect that probably they were opened... Please instruct me in details - what and in what situation should I do to help you pinpoint this bug.

**Comment by aaFn** [comment] 2019-05-16 06:30
Nothing precise for now, just trying to identify what could happen:
- bookmark is created
- it is in BSP2 cache since when re-displaying you see it

so creation went ok, notification from FF to BSP2 went pok, this is just display of update which failed ... so trying to identify the conditions in which you are when this happens to find where it could fail.

**Comment by vitaaliy** [comment] 2019-05-16 07:08
You know, I have a huge BM tree:
Bookmarks:            87083
Favicons to fetch:    87083 (100.0%)
Folders:              16140
Besides - a gigantic number of open tabs... FF, the poor boy, is always busy with its own activity. Maybe some of its processes interfere with BSP2?

**Comment by aaFn** [comment] 2019-05-16 07:55
Could be, but then this is a question of reinforcing robustness again because things not happening exactly as before. I'll continue to search ..

**Comment by vitaaliy** [comment] 2019-05-16 19:03
Here again. BSP2 opened. No automatic search. Insertion of a link [](https://y-jesus.org/russian/wwrj/6-jesus-rise-from-dead/2/) was done into folder: **Resurrection** with the help of native FF machinery - finding the folder needed.
Oh, you know what has come to my mind? There are probably two BM trees: one _FF native_, and the second - _BSP2_. When I add a link through the **_Blue Star_** help - it is added into FF tree. And probably not dubbed into BSP2. It could explain why we do not see this BM in the BSP2 tree... Is it possible?
[Browser Console.docx](https://github.com/aaFn/Bookmark-search-plus-2/files/3188630/Browser.Console.docx)

**Comment by aaFn** [comment] 2019-05-16 19:14
No that shouod work, and it works on my side. From what I infer; the problem is just a display problem at the end of the process..
Best way to make sure is, when the problem happens, you click on the BSP2 yelow star to make the sidebar disappear, then re-click on it to make it appear again (and so redrawn ....) and you should see the bookmark. But I do not have doubts, from what you say the problem is something breaking on the display step .. sometimes.

**Comment by vitaaliy** [comment] 2019-05-17 18:57
You are right :). The magic BSP2 yellow star does its duty. The inserted bookmark becomes visible in its right place. Though due to the large BM tree it takes considerable time to reinstall the tree.

**Comment by aaFn** [comment] 2019-05-18 08:16
Yes, the problem is really on the last step of display. Need to catch it, but so far nothing is showing in your traces ... Maybe, if you didn't do that already, next time give me the whole contents of the browser console, in case the problem is far away above ....
Due to its non systematic nature, it is hard to catch ..

**Comment by vitaaliy** [comment] 2019-05-19 17:12
Here you are. By the way... If I will use .odt format (LibreOffice) - will it be readable by you?
[Console.docx](https://github.com/aaFn/Bookmark-search-plus-2/files/3195366/Console.docx)

**Comment by aaFn** [comment] 2019-05-21 15:08
Thanks @vitaaliy .
Well, nothing in there is really showing, I believe I caught the main error in the robustness feature, and something else is going on then which is not generating an error (maybe the bookmark ends up somewhere else in the display because of the de-sync in messages now ...). I'll need to dig further ...

Yes, odt is fine.

**Comment by vitaaliy** [comment] 2019-06-16 08:02
Hi @aaFn,
I have now version 2.0.62. I am not sure but it looks like now BSP2 machinery works OK. From now on I will pay special attention to it, and if failure reappears, I will inform you right away.
Thank you for your attention and efforts. I would probably change for another browser, but no one can demonstrate such functionality that we have with BSP2 now. Thank you once more!

**Comment by aaFn** [comment] 2019-06-20 19:34
Hello @vitaaliy , ok thank you fo rth feedback. I tried to peek hard at what could go wrong but didn't find anything so far, and so didn't change anything => if things are varying, that could mean something else exterior is acting ... but that could be even harder to catch. Let's see ...

**Comment by aaFn** [comment] 2019-07-13 08:56
Looks like we are good, so closing the issue.
Not sure what happened though, if that comes back, let me know.

**Closed by aaFn** 2019-07-13 08:56 UTC
Labels: not sure.. but fixed
