### ISSUE TITLE
Don't open the site

### ISSUE THREAD

**Issue by hopalongrock** [aaFn/Bookmark-search-plus-2#7] opened 2018-02-09 09:07 UTC
Please create option to don't open the site (only show the bookmark in the tree folder), or open in a new tab.

**Comment by NicolasWeb** [comment] 2018-02-09 09:11
@hopalongrock Your request is the same as issue #3 
You might close this one ;-)

**Closed** 2018-02-09 09:16 UTC

**Comment by aaFn** [comment] 2018-02-09 09:18
@hopalongrock, indeed, curent behavior is consistent with both the native FF bookmark sidebard and with the old Bookmark Sidebar Plus =
- Click on the link (image or text) = open site and show the bookmark
- Click on the right or the left of the link (so not on image nor text) = just show the bookmark
However, we all agree that the context menu (right click) is missing an action to only show the bookmark.
That will come in 2.0.4.

As for opening in new tab, simply right click and you have a choice of opening in current tab, in new tab, in new window, or in private window .. just like the native FF bookmark sidebard and with the old Bookmark Sidebar Plus

So I am marking this issue as duplicate of #3 if you agree.
