### ISSUE TITLE
"New Folder..." takes very long

### ISSUE THREAD

**Issue by peter-kehl** [aaFn/Bookmark-search-plus-2#241] opened 2022-05-13 00:26 UTC
Hi,

When in BSP2 (whether in Firefox sidebar, or in a separate tab) I choose an existing folder, right click and "New Folder...", it takes 5-6 seconds to show the New Folder dialog.

Everything else works marvels. Any chance of speeding the dialog up, please?

I have current Firefox 100, on current Manjaro Linux x64. I do have **many** Firefox extensions, and many (3000) tabs open. However, I don't have many/unusual popup blockers (only standard Firefox popup preventer, and uBlock Origin - but I believe neither would affect BSP2 since it's privileged.) But if you believe there may be strange interactions, please suggest how I can investigate.

From BSP2 stats:
Bookmarks:             4431
Favicons to fetch:     0 (0.0%)
Unsuccessful favicons: 2968 (67.0%)
Folders:               688

Thank you in advance.

**Comment by aaFn** [comment] 2022-05-13 07:12
Hello @peter-kehl , very fast here, so that must be contextual.
The sequence is as follows:
1. Ask FF to create folder
2. Wait for it to say "done"
3. Open the Properties window

To investigate a bit, could you try to create a new folder from inside the native FF bookmark sidebar, and see how much time it takes to appear ?
Then, could you do the same on BSP2, and look specifically at how much time it takes to appear, to compare ? Then how long is it between end of step 2 (folder appeared) and step 3 (property window open) ?

**Comment by aaFn** [comment] 2022-06-30 14:51
Closing as not able to reproduce.
Please reopen if you have more information and want that we investigate together.
Thanks, aaFn.

**Closed by aaFn** 2022-06-30 14:51 UTC
Labels: cannot reproduce or invalid
