### ISSUE TITLE
"batch" bookmarks

### ISSUE THREAD

**Issue by ohillary** [aaFn/Bookmark-search-plus-2#121] opened 2019-12-20 17:27 UTC
Hello,
Still loving Bookmarks search plus 2; it is a great utility. Up until 2-3 weeks ago, I could grab a batch of tabs and drag them into the appropriate folder in sidebar. Now only one bookmark out of the batch shows up in folder, so I have to drag each one. Really miss the batch function. NOTE: also use "auto tab discard" but that hasn't interfered up until now; disabling doesn't help.
thanks,
O

**Comment by aaFn** [comment] 2019-12-20 18:37
Hello @ohillary , ok I'll check, nothing changed in BSP2 on that, so it is probably a regression due to FF 71 which cha,ged something. I will keep you posted here.

**Comment by ohillary** [comment] 2019-12-20 19:46
must be hard to keep up with FF changes . . . thanks for looking

________________________________

**Comment by aaFn** [comment] 2019-12-21 21:44
So the outcome is that FF dropped the support for that from FF 71, and I could not find any replacement function :-(
See https://developer.mozilla.org/en-US/docs/Web/API/DataTransfer (search for mozItemCount for example), you will find this is deprecated as of FF71.

Investigating with the add-on debugger, I can observe that only 1 element is sent to the add-on, so this is not possible to get around it and to find the others in the drag operation.

Sorry .. for now I have no solution, this is driven by FF.

I opened a bug / request for enhancement at Bugzilla -> https://bugzilla.mozilla.org/show_bug.cgi?id=1605606
Anybody who wants to vote on it is welcome to add their voice there :-)

**Comment by ohillary** [comment] 2019-12-22 02:36
OK, sorry they make busy work for you. Worked fine until they broke it. Thank you for looking into it.
Happy Holidays
O


________________________________

**Comment by aaFn** [comment] 2020-01-01 21:24
Closing the ussue while waiting for FF to fix it / provide again the function they removed.

**Closed by aaFn** 2020-01-01 21:24 UTC
Labels: external dependency
