### ISSUE TITLE
BSP2 losing data

### ISSUE THREAD

**Issue by elgreko5** [aaFn/Bookmark-search-plus-2#102] opened 2019-05-15 12:25 UTC
Hello aaFn,

After a month of trying to use BSP2 (and reporting to you numerous issues, some of which you incorrectly considered features instead of flaws), last months I reduced it's usage only to "BSP2 Path to bookmarked item", because:

BSP2 is losing (my) data (and, of course, time, time that it, instead, should be saving).

Yesterday (it also happened before), I forgot I am in BSP2 and renamed (by renaming I mean putting some new data into names, the data I calculate beforehand, and not some non-important random characters that I put there when I have nothing better to do) some bookmarks and folders in BSP2, just to see, a while later, that BSP2 only displayed them as changed to me and did not in fact change them in FF db.
Moreover, after reopening FF I was "greeted" with new BSP2 window offering me to change that name again, which repeated itself after subsequent reopening.

Earlier, it happened that I edit bookmarks for hours, just to see BSP2 put all that work down the drain. 

Now, I read you wrote something about increasing robustness and waiting for the next occurrence of a problem, and I must say to you that users' loss of data is not something to experiment with.

The only way to deal with data loss is to eliminate it immediately.
All other functions are useless if BSP2 will lose data.
Also, your download page should state, in big red capital letters that BSP2 could cause loss of data, at least when renaming bookmarks. What's more, application with this kind of problems should have major revision 0, not 2, and should be called experimental, not even beta.

It seems I must stress that it's not my computer's fault, it's not shortage of memory or resources, it's not other add-ons... - it is BSP2. 
Also, it doesn't matter at all if everything on your side is fine (which I seriously doubt).

Best regards

**Comment by aaFn** [comment] 2019-05-15 13:15
Hello @elgreko5 , the flow of a modification is as follows:

1. User asks for modification in BSP2, and BSP2 sends the modification to FF. It doesn't modify anything in its cache nor on its display.
Note that this step can be also a modification in FF bookmark, or in FF bookmark library, or in any other add-on.
3. FF notifies BSP2 that a modification is made
4. BSP2 displays it

By modification, I mean create, delete, move, change contents ... really ANY modification to the boomarks.

So when you see the modification on the screen, that means FF said to BSP2 that a modification was made (and presumably saved by it, but we have no way to know), and that now BSP2 has to reflect it.

=> BSP2 cannot "lose" anything

What appears to happen in the case you experience is that FF notifies the modification, but doesn't save it. There's nothing BSP2 can do about that unfortunately, it doesn't know that what FF tells it is not saved by FF.
Note I am not experiencing the same thing than you, and I do use BS2 daily on several computers, I made it for me first thing, and I can tell I use it intensely as you.

I observed that this is coming apparently with FF 66, and also that some things get disordered with that version. Robustness = I am trying to resist a bit to side effects introduced by that disorder, but this is not a cure for the cause that lies in FF, this is simply trying to be able to continue.

**Comment by elgreko5** [comment] 2019-05-15 15:03
Turning a blind eye to errors is something FF developers would do, but to say an application can't lose data...

Even if some FF bug is making BSP2 lose data, it is still BSP2 that is losing data.

If it works well on your computer, good for you.
I have 82k bookmarks, but you have 1.8k IIRC - maybe the bigger number exacerbates the problem.

I already wrote this, but it seems you just ignore what for whatever reason doesn't suit you - it also happened earlier, hence I stopped editing bookmarks from BSP2, and I now only use "BSP2 Path to bookmarked item".

I also already wrote that after reopening FF, BSP2 opened in a window. (Of course, it wasn't opened before closing FF.)

Whatever the case, this is crucial flaw and users should know about it before using (and not after they experience a loss of hours of work).

**Comment by aaFn** [comment] 2019-05-15 15:16
I am really sorry for what is happening, but there's nothing I can do., and it is not ignoring or waiving out.

As I wrote to you, when you see the thing happening on BSP2, this is because FF instructed BSP2 to do it. So BSP2 didn't lose anything.

It is unfair to blame it on BSP2 if FF doesn't save what it instructs BSP2 to do. And again, BSP2 has no way to know that FF didn't save things to disk, an add-on does not (is not allowed to) have access to such things.

I do not see what I can do on this one, and since I cannot reproduce it myself, I cannot even open a bug on FF = they will ask me for details I do not have, as well as do a regression identification procedure to find which defect number introduced it, which I won't be able to do as I cannot reproduce.

At this stage, the only thing I can recommend is that **you use FF version 65 or 64**, where apparently this bug (and disorder in notifications to BSP2, this is probably related) never happened.

And then check next version of FF (67) to verify, when it is out. Or maybe you should try using the Beta or Nightly releases of FF, which are respectively +& and +2 I believe, in case this is working better ?

**Comment by aaFn** [comment] 2019-06-30 21:26
@elgreko5, it may be that I found a workaround to the FF problem, supposing it is due to the new FF66 format of Indexed DB's for local storage, which his inducing very high and long spikes of CPU consumption for users with large or very large numbers of bookmarks (like you).

Theory being that that such high spikes result in FF saying ok to BSP2, but not really saving because it is using the CPU too much, and so it "forgets" or internally times out on such actions.

See https://github.com/aaFn/Bookmark-search-plus-2/issues/103#issuecomment-507068395

Let me know if things are improving on your side with 2.0.63, if you are still experiencing the problem.
aaFn.

**Comment by aaFn** [comment] 2019-07-13 08:53
No news, so I understand the workaround in 2.0.63 for FF66+ did it.
Closing the issue, thank you aaFn.

**Closed by aaFn** 2019-07-13 08:53 UTC
Labels: enhancement
