### ISSUE TITLE
Add bookmark dialog box.

### ISSUE THREAD

**Issue by JohnLukeBentley** [aaFn/Bookmark-search-plus-2#19] opened 2018-03-01 04:50 UTC
@aaFn, the add bookmark dialog box is a problem on my triple monitor setup: it always opens in the centre of the centre monitor. This is no good if my FF is on one of the side monitors.

I'd suggest opening the Add bookmark dialog box at the last, user placed, location.

To recreate:
* Drag url from FF address bar to somewhere in the tree of BSP2.
* Observe the Add bookmark dialog box is in the centre of the screen.

**Comment by aaFn** [comment] 2018-03-03 00:15
Hello @JohnLukeBentley , ok, and of course I am hitting an FF restriction :-)

When trying to restore the window at its old position after saving it on a close, I just observed that when calling the browser.windows.create() function again, the top and left values are ignored for a popup (which is the type of window I have to use so as to not get a normal browser window with its own sidebar, URL, menu .. etc ..) :-(
Cf. https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/windows/create

It puts it in the middle of the main screen - full stop ..!

So I have to do something a little ugly: once the window is displayed, I move it to the saved place.
Therefore, you will see a two steps thing each time: it quickly appears at middle of main screen, and then move to the place saved when closing.
I hope this is ok ..

One additional point:
- To avoid the problem that the popup could become invisible and unreachable in case the origin screen was turned off, or in case the display resolution was changed, when I am detectiing that the saved position of the popup is not in the same screen boundaries than the browser window, then I bring it back to center of the screen where is the browser window => you cannot have the browser window in one screen, and have the popup appear in another. That should be a minor inconvenience, compared to not being able to reach the popup because it appears in a saved position not reachable anymore.

Will be in 2.0.8 if the above is ok with you.

**Comment by JohnLukeBentley** [comment] 2018-03-03 03:46
> it quickly appears at middle of main screen, and then move to the place saved when closing.

Yes, I think that's fine, given the limitations you are up against. At least we'll see how it looks and take it from there.

>   in case the origin screen was turned off ... bring it back to center of the screen where is the browser window.

Yes, that's fine ... that's what I find myself doing anyway. That is, when I have the browser open on side screen and the dialog opens in the centre screen, I drag the dialog to the side screen with the browser.

I'll make an additional request with respect to the Add dialog: map the keystrokes [Enter] and [Esc] to Add and Cancel respectively. That is standard behaviour.

**Comment by aaFn** [comment] 2018-03-08 23:20
Ok, this is in 2.0.8 :-)

**Comment by JohnLukeBentley** [comment] 2018-03-09 11:23
Awesome and thanks. Look forward to it :-)

**Closed** 2018-03-09 15:41 UTC
Labels: enhancement

**Comment by JohnLukeBentley** [comment] 2018-03-15 06:00
Thanks for implementing this.

> it quickly appears at middle of main screen, and then move to the place saved when closing

It does look rough when it is in front of you. Perhaps we should raise a seperate issue for this, as remainder in case the Webextensions API improves.

But, for now, an additional suggestion: The Add Bookmark dialog [Add] Button should be outlined when the enter key will activate it. That's the standard. See, for example,

* Windows Firefox > Ctrl+ B (for native bookmarks manager)
* Right click on a bookmark > Properties ...
* Observe the outlined [Save] button.

**Comment by aaFn** [comment] 2018-03-15 07:53
Hello @JohnLukeBentley , this is even worse as the first time the window is displayed, it is empty .. see bug https://bugzilla.mozilla.org/show_bug.cgi?id=1408446 :-D
I will see if I can reduce a little the brief display period, but I won't be able to make it go unnoticed I am afraid.

On the outlined Save button, this appears to be a platform specific thing, in Linux, the Save button is not outlined for example. I will see if there is something which can be done on the Button object for that.

**Comment by aaFn** [comment] 2018-03-15 08:40
I checked, this looks hard to do:
- In Linux, the text input fields show their focus status, in Windows they don't
- In Linux, focus is by default on the Title text input, not on the button
- In Windows, it looks like the focus is on the Save button, however all keys except Enter go by default to the Title input field like in Linux
- There is possibility to steal the focus from the Save button in Windows, and make it go on the Cancel button, so this is not a graphical artifact
- There is no way to have focus on two places, automatically triaging on keystrokes depending on their nature .. this has to be coded
- Implementing a feature which is giving focus to the button in Windows, but stealing keystrokes to send them to the last text input selected, default being Title, is unnatural and more complex to do than what is currently implemented (= focus first on Title text input, let it change as the user wants, and watch for Enter and Esc whatever is the focus to dispatch an event to either Save or Cancel).

So I can't see for now how to easily do that, sorry.
If I find something later, I'll come back to it, but for now, I should leave it like that if you don't mind.

**Comment by JohnLukeBentley** [comment] 2018-03-15 08:51
This is not a matter of focus. You shouldn't be trying to place focus on the Button.

Try this again:

* Windows Firefox > Ctrl+ B (for native bookmarks manager)
* Right click on a bookmark > Properties ...
* Observe the outlined [Save] button.
* *Observe that the Name Field has focus**.

... The outline is merely an aesthetic marker which, in Windows at least, is the standard for signalling that the Enter key will trigger the outlined button. The outline does not mean the button (necessarily) has focus. The focus marker is separate.

Look in Notepad (in Windows).:
* File > Save As ... 
* [Tab] (on the keyboard) until you are over the [Save] button. 
* Notice the difference between the ever present continuous & think outline (Signalling that Save will trigger on [Enter]) and the broken edged outline (which follows focus).

**Comment by aaFn** [comment] 2018-03-15 11:49
Yes, we are saying the same thing I believe, I was calling it "default button focus" in my post, I agree this is not a good name.

The basic point is that it appears that in Windows native UI interface, there is this thing which shows as  the button outline you mention, highlighting the default button in a group, but in HTML (and so in the FF Javascript API), I didn't find an equivalent. Only the focus .. which is where the keystrokes are going.

**Comment by JohnLukeBentley** [comment] 2018-03-16 04:27
> The basic point is that it appears that in Windows native UI interface, there is this thing which shows as the button outline you mention, highlighting the default button in a group

Yes, we have the same understanding on that ... is is the "default" button, so outlined, which will trigger on the [Enter] key being pressed. And, yes, it may well be a Windows only convention ... "this appears to be a platform specific thing, in Linux, the Save button is not outlined for example".

> but in HTML (and so in the FF Javascript API), I didn't find an equivalent.

```html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
<head>
  <meta charset="utf-8" />
  <title>Outline button</title>
  <style xml:space="preserve">
    /* <![CDATA[ */
    button {
      border: 2px solid #0078D7;
    }
    /* ]]>*/
  </style>
</head>
<body>
  <h1>Outline button</h1>
  <form>
    <button type="submit">Submit order</button>
  </form>
</body>
</html>
```

?

**Comment by aaFn** [comment] 2018-03-16 08:55
He he, I thought of that indeed, but this is not a native Button or HTML form behavior ...
And then I would also have to add code to manage the outline as it can move from Save to Cancel:

- Ctrl B to get native sidebar
- Right click on a bookmark, go to properties
- Press Tab enough times ... the outline moves to Cancel

And also it would probably have to vary by platform to be consistent :-(.

This is why I was initially saying "this looks hard to do" .. I do not want to replicate platform specific or varying UI behaviors in Javascript code.

If it is not natively made available by HTML or by the FF Javascript API, on HTML objects, then this is the intended behavior by HTML and FF Javascript API designers (I guess ..), and I'd rather not patch for that kind of things ... (it would be different if I were creating my own objects, but I am not into that).

So unless we find an FF Javascript API provided method on those object, or an HTML attribute, to set "default button" in a group of button, I prefer to remain with the limitation .. waiting for me to discover what may exist but that I didn't find yet, or waiting for them to be provided by HTML / FF API.

We can open a bug on bugzilla of course, but if this is seen as an HTML Standard feature by FF, that will very quickly get rejected.

**Comment by aaFn** [comment] 2018-03-17 14:14
> It does look rough when it is in front of you.

I tried in 2.0.10 to make it less conspicuous by reducing the size of the initial window ..
And also tried to make the initial flash a little briefer.

Notes:
- Making it 1, 1 in size does not work well, it results in a window with only the bar under Windows, and no way to resize it in Javascript
- I also tried to create it minimized, and then make it appear where I want, but this is worse, FF first creates it big, and then minimizes it => it does not create it minimized in fact ..

FF is not very clean on this ... :-(

**Comment by JohnLukeBentley** [comment] 2018-03-20 06:34
I'm on 2.0.11.

On my machine I have no flash. That looks fantastic. Great work there!

On the size. Yes it looks better shorter. However I'd suggest making it wider (unless that impacts your flashing). Perhaps twice as wide. Both the name and addresses can get quite long and it would be good to see more of both as you decide to edit or accept the default.

On the button outline. ...

If functionality is difficult (or impossible) to implement then that counts as a (defeasible) reason to not do it. But I'd suggest we keep distinct any: difficulty of implementation; from desirablity in terms of user experience.

So on desirability in terms of user experience:

* I don't think we can take the FF api devs to be necessarily expressing their ideal. Given, on FF in windows in the native sidebar, the default button is outlined ... then we can see that the FF general devs are following this convention (of having button outlines) rather than rejecting it. I suspect the FF api devs (rather than the FF general) simply have more work to do.

* Various OSs have their various UI conventions. It doesn't seem wise to break those OS conventions for the sake of uniformity of one's app across OSes. I think that makes for an inconsistent user experience. Speaking as a full time Windows user it's certainly jarring to see a dialog box break Windows conventions, as the BSP2 dialog box presently does.

On difficulty of implementation you mention:

* The css `border` doesn't seem to work. That's surprising. What about 

      button {
        outline: 2px solid #0078D7;
      }
  ?
* OS specific testing. Perhaps you fear that catering for OS specific behaviours might create a great deal of work for you. That's a legitimate concern in general. But in this case is it really a worry? Testing for OSs seems straightforward https://stackoverflow.com/questions/9514179/how-to-find-the-operating-system-version-using-javascript (that is, use `navigator.oscpu`) ... and is there another area, besides button outlining, where we'd need to have OS specific handling?
* "Press Tab enough times ... the outline moves to Cancel". That should be straightforward to implement: 
  * On the [Cancel] button receiving focus - remove outline from [Save], give [Cancel] an outline; 
  * On the [Cancel] button losing focus - remove outline from [Cancel], give [Save] an outline.

You are luring me dangerously close to wanting to dive in and offer you pull requests :)

**Comment by aaFn** [comment] 2018-03-20 07:30
Hello @JohnLukeBentley , thank you for the link on window.navigator.oscpu, this is much useful.

On the topic of button default selection, my position is now as follows:
- HTML  and browsers in general, of which FF, disabled access to system Modal dialogs. Look for things like UniversalBrowserWrite and other related topics, we do not have that capability anymore it seems, or only with deprecating primitives not to use anymore.
- The reason is simple: they do not want an HTML page or an add-on to fake a system dialog and to trick a non experimented user into something
- Therefore, the means left to us are always making the dialog different than a system dialog. On that spirit, any window open by an add-on has "moz-extension:....cabalistic_chars.." at front of the title, which is totally user unfriendly, but there is no way to get around it (look at the title of the BSP2 bookmark property .. even ùy title disappeared, it is ignored :-( .. bug open https://bugzilla.mozilla.org/show_bug.cgi?id=1296365).
- Furthermore, HTML does not implement today the notion of "default selection" on a group of button.
- But any of the above may change in the future as I believe they are going too far, and this is unfair to have access to system dialogs for browser coders, but not for add-on developers.
- Therefore, I **do not want** to go nor to invest on that path of mimicking a system behavior which is not the intended HTML behavior .. I will wait for the day HTML or FF give us that thing natively.

Good that the flash does not appear anymore on your side. On my side I can still see it, but it is true that this is not all the times: this depends on whether the default new window position is the same or not than the saved bookmark property window .. That was not the case before, this is an undocumented side effect of not providing left, top to the browser.windows.create() API method https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/windows/create .. which I discovered at random and am using for the best (however not guaranted then, it can change ..)

On the size of the window, since it is not a modal, you can change it at will :-)
Try it, you will see ..
Maybe what you want is that I save the size and restore it to the size it had last time it was closed (at same time than its position) ?
If so, I would suggest that you create a new issue for that. Then we would need also to figure out a way to restore it to its defaults, in case something goes wrong ... If you want to go there, I would welcome any suggestion on the way to restore defaults.
Also, maybe we should care about users who do not want to change it, even by accident (so next open should come back to default size by default) ?
