### ISSUE TITLE
"Open all in tabs" opens items randomized

### ISSUE THREAD

**Issue by mzso** [aaFn/Bookmark-search-plus-2#196] opened 2021-08-22 11:59 UTC
Hi!

It would be nicer if the tabs opened in the order they appear in the folder. FF bookmark sidebar also mixes up the order.

Which is strange, not sure if it is a problem on my end or neither sidebar cares much about the order.

**Comment by aaFn** [comment] 2021-08-22 12:46
Strange, BSP2 create tabs n the order where they appear in the folder.
Code is doing it that way, and I just tested on my side to make sure, that works that way also.

Are you sure you do not have a special option on tabs which is changing things ? (maybe something in about:config ...)

**Comment by mzso** [comment] 2021-08-22 13:39
[**@aaFn**](https://github.com/aaFn) commented on [2021. aug. 22. 14:46 CEST](https://github.com/aaFn/Bookmark-search-plus-2/issues/196#issuecomment-903263569 "2021-08-22T12:46:07Z - Replied by Github Reply Comments"):
> Strange, BSP2 create tabs n the order where they appear in the folder.  
> Code is doing it that way, and I just re-tested on my side to make sure, that works that way also.
> 
> Are you sure you do not have a special option on tabs which is changing things ? (maybe something in about:config ...)

What special options do you mean? I don't think so. Though I guess there could be conflicts with other addons/scripts. Though no idea why or with what.

**Comment by aaFn** [comment] 2021-08-22 15:39
No idea, but for me something is altering the behavior if you do not see your tabs in the order of bookmarks in the folder.

**Comment by mzso** [comment] 2021-08-22 15:58
[**@aaFn**](https://github.com/aaFn) commented on [2021. aug. 22. 17:39 CEST](https://github.com/aaFn/Bookmark-search-plus-2/issues/196#issuecomment-903287606 "2021-08-22T15:39:14Z - Replied by Github Reply Comments"):
> No idea, but for me something external to BSP2 in your setup / config / installed add-ons is altering the behavior, if you do not see your tabs in the order of bookmarks in the folder.

Well, my first hunch was to disable Tree Style Tab, after which the tabs opened in the order expected.
But should this happen? TST is not supposed to manipulate the order in which the tabs are opened.

**Comment by aaFn** [comment] 2021-08-22 17:45
Interesting .. I suggest that you open an issue there https://github.com/piroor/treestyletab/issues, unless of course you have voluntarily set up an option in TST which is resulting in that effect.

**Comment by aaFn** [comment] 2021-10-05 21:05
Closing, as the problem is most probably triggered / caused by TST.
Thanks, aaFn.

**Closed by aaFn** 2021-10-05 21:05 UTC
Labels: external dependency
