### ISSUE TITLE
Plugin configuration: arrow up / down buttons not clickable

### ISSUE THREAD

**Issue by chr7** [aaFn/Bookmark-search-plus-2#81] opened 2019-01-12 09:10 UTC
On the configuration pane of the plugin, section "User Interface", setting "Override default font size to":
the Arrow up / down button is placed on the field and cannot be clicked (Linux Firefox 64.0)

[![Bookmark-Search-User-Interface.png](https://i.postimg.cc/85cZWYXB/Bookmark-Search-User-Interface.png)](https://postimg.cc/PpGbnSjP)

It works for the "Override default bookmark item spacing to" although the buttons are placed on the field too but the field is wider (which I assume is the reason).

**Comment by aaFn** [comment] 2019-01-12 18:05
Hello @chr7 , well strange, I just used standard HTML code, see:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/number

How does the input show for you in that MDN official page ?

On my Linux'es (I have several), all is ok,, both in the BSP2 options page and in the MDN page above..

=> Which Linux flavor do you use, and more precisely and relevant in this issue, which UI manager do you use ? On my Linux'es (Void Linux and RHEL 7), I have Mate 1.20.4, KDE v4.x and KDE v5.x (I do not have the exact versions for these 2 here under my hand).

Anyway, to avoid any problem, I will fix the size for the two fields to a bigger value = 5 em, that should be sufficient (it is 3 em currently for the fontsize input, and I have set none for the placesize input so far, which explains the difference).

As for buttons placed on the field, this is the standard / default behavior in FF, both in Windows and in Linux (can't tell for IOS as I do not have any), so all is ok there.

This will be in 2.0.51.

**Comment by chr7** [comment] 2019-01-12 21:41
That's how it looks like on that page you gave me the link:

[![MDM-Input-Number-Demo.png](https://i.postimg.cc/2yWPgSp5/MDM-Input-Number-Demo.png)](https://postimg.cc/1V9CqP3x)

I have Ubuntu 18.04.1 with xfce / xfwm4.

**Comment by aaFn** [comment] 2019-01-12 22:50
And how does the "10x" one look like ? It is 3em like mine ..
Scroll down to the Controlling_input_size section ..

**Comment by aaFn** [comment] 2019-01-13 11:32
I confirmed the problem by installing XFCE on one of my Void linux'es.
It is only under that UI mgr that the problem appears.
It is apparently due to an inherited CSS property from a higher level CSS sheet in the options panel, coming from FF ... but I could not figure out which one it is to unset that property :-(

This explains why it is ok on the standard MDN page, but not in the options page (I am already at 3em, like in the standard MDN page).

I am setting it to 4em, it seems to be ok on XFCE, and this does not look awkward under the other OS'es / UI managers even if a little bigger.

I must say btw that the look of that page under XFCE is quite ugly, things vertically overlay a little on each other .. apparently FF doesn't compose so well with XFCE :-( ...

This adjustment will be in 2.0.51 to be out tonight.

**Comment by aaFn** [comment] 2019-01-14 00:57
2.0.51 is out, let me know.

**Comment by chr7** [comment] 2019-01-14 08:06
Perfect - now I see that "Override default font size to" reads 12 actually :-D

[![Bookmark-Search-User-Interface-After-Update.png](https://i.postimg.cc/CxLSqh3d/Bookmark-Search-User-Interface-After-Update.png)](https://postimg.cc/ZCgGkSKh)

**Comment by aaFn** [comment] 2019-01-14 11:21
Good, so let's close the issue then :-)
Thank you, aaFn.

**Closed by aaFn** 2019-01-14 11:21 UTC
Labels: enhancement
