### ISSUE TITLE
Something's wrong with type-to-find

### ISSUE THREAD

**Issue by mzso** [aaFn/Bookmark-search-plus-2#199] opened 2021-09-05 20:29 UTC
Hi!

It seems like it doesn't always find the next one, but jumps through some items all the time.

Maybe diacritics are not well handled because the ones that I noticed being skipped have an í and an é in them.
But it's strange because with the former it never finds it, and for the other it jumps on the second result that starts with the exact same word.
Curiously for the first one if I type only the first letter BSP2 finds but if I type the í which is the second character, it wont find it.
Even more weirdly if do the first character only once, then select an item above, it can find the item normally untill I search for a different string. It's all hard to make sense of.

**Comment by aaFn** [comment] 2021-09-06 11:14
Hello @mzso , yes this is due to diacritics, which I am not handling in the key search.
Let me improve, so that now this will be both case insensitve, and diacritics insensitive.

Will be in 2.0.97.

**Comment by mzso** [comment] 2021-09-06 21:10
[**@aaFn**](https://github.com/aaFn) commented on [2021. szept. 6. 13:14 CEST](https://github.com/aaFn/Bookmark-search-plus-2/issues/199#issuecomment-913565835 "2021-09-06T11:14:24Z - Replied by Github Reply Comments"):
> Hello [@mzso](https://github.com/mzso) , yes this is due to diacritics, which I am not handling in the key search.  
> Let me improve, so that now this will be both case insensitve, and diacritics insensitive.
> 
> Will be in 2.0.97.

Thanks.
Though, as user of a language with a good amount of diacritic marks, I have some doubts that (non-optional) diacritic insensitivity will be a good thing.

**Comment by aaFn** [comment] 2021-09-06 21:36
Understood. However, since Firefox native bookmark searches are also diacritic insensitive, this is to align.

Anyway, diacritic sensitive searches are not working very as you could observe .. (not exactly sure why, but not really going to investigate 😁 ..)

**Comment by mzso** [comment] 2021-09-06 21:42
[**@aaFn**](https://github.com/aaFn) commented on [2021. szept. 6. 23:36 CEST](https://github.com/aaFn/Bookmark-search-plus-2/issues/199#issuecomment-913861730 "2021-09-06T21:36:19Z - Replied by Github Reply Comments"):
> Understood. However, since Firefox native bookmark searches are also diacritic insensitive, this is to align.
> 

Really? Maybe it's a recent thing. Pre "quantum" FF didn't even have that for the findbar.

**Comment by aaFn** [comment] 2021-10-05 21:32
Fixed in 2.0.97 which is out just now.
Closing as resolved, thank you, aaFn.

**Closed by aaFn** 2021-10-05 21:32 UTC
Labels: enhancement

**Comment by mzso** [comment] 2021-10-31 08:20
I don't think this works at all. Hell it looks like even non-diacritic letters don't work.

I have for example a bookmark folder starting with "Szilárd" and before it Szilícium, and before that even Szelén, with other bookmark folders. I type "szil", or "szilí", or "szilá", and the highlight jumps to Szelén and never further.
So I create another bookmark before these three "Semmi". Then it jumps to this and no further.Just as I suspected, only the first character works. The highlight jumps to the first item with an S and stays there.

**Comment by aaFn** [comment] 2021-11-01 13:57
Indeed, regression bug introduced when I added the wrapping at start function in https://github.com/aaFn/Bookmark-search-plus-2/issues/181, sorry.
Correction will be in next version.

**Comment by mzso** [comment] 2021-12-04 09:36
[**@aaFn**](https://github.com/aaFn) commented on [2021. nov. 1. 14:57 CET](https://github.com/aaFn/Bookmark-search-plus-2/issues/199#issuecomment-956255765 "2021-11-01T13:57:43Z - Replied by Github Reply Comments"):
> Indeed, regression bug introduced when I added the wrapping at start function in [#181](https://github.com/aaFn/Bookmark-search-plus-2/issues/181), sorry.  
> Correction will be in next version.

When is that version due?

**Comment by aaFn** [comment] 2021-12-05 22:07
Hello @mzso , will be during Christmas vacations, so in 2 to 3 weeks.
Not much time available before that.

**Comment by aaFn** [comment] 2021-12-28 14:52
Helo @mzso , 2.0.100 is out with the fix. Hope this is good this time, thank you aaFn.

**Comment by mzso** [comment] 2021-12-28 19:05
[**@aaFn**](https://github.com/aaFn) commented on [2021. dec. 28. 15:52 CET](https://github.com/aaFn/Bookmark-search-plus-2/issues/199#issuecomment-1002142153 "2021-12-28T14:52:19Z - Replied by Github Reply Comments"):
> Helo [@mzso](https://github.com/mzso) , 2.0.100 is out with the fix. Hope this is good this time, thank you aaFn.

Thanks for the notice. So far so good.
