### ISSUE TITLE
Thick black lines and no indication of choice in lower frame.

### ISSUE THREAD

**Issue by rdigrego** [aaFn/Bookmark-search-plus-2#205] opened 2021-10-28 20:40 UTC
I very much dislike all the dark lines above and below each bookmark.  Their distraction make it hard to read.  

In the first image I searched for "design" and clicked on the second choice, PicMonkey.  Nothing points out to me which is my choice in the lower frame, but it's usually around the middle of the frame, so I usually find my choice.  

<img width="431" alt="image" src="https://user-images.githubusercontent.com/93227534/139323883-0656d6f2-9bff-4f58-abb9-944ac9483637.png">

**Comment by aaFn** [comment] 2021-10-31 22:32
Hello @rdigrego, this doesn't look normal, and this is not how BSP2 is designed.
A few questions to start investigating why you are getting that strange effect:
- Which system / OS version are you on ?
- Which FF version ?
- Do you have other add-ons installed, and if yes which ones ?
- Did you install or activate a theme on FF, and if yes which one ?
- Do you have a userChrome.css script active, and what is its content if yes ?

Thank you, aaFn.

**Comment by rdigrego** [comment] 2021-11-01 17:50
> On Oct 31, 2021, at 5:32 PM, aaFn ***@***.***> wrote:
> 
> 
> Hello @rdigrego <https://github.com/rdigrego>, this doesn't look normal, and this is not how BSP2 is designed.
> A few questions to start investigating why you are getting that strange effect:
> 
> Which system / OS version are you on ?  I’m on two different MacBooks. 

> Which FF version ?  93.0 64bit

> Do you have other add-ons installed, and if yes which ones ? Sever, so I disabled [but did not remove] all but LastPass and BSP2, restarted FF, and it is still the same.

>  
> Did you install or activate a theme on FF, and if yes which one ?  I did install one, but removed it.  Now it’s using this:


> Do you have a userChrome.css script active, and what is its content if yes ?  I have neither userChrome.css nor userContent.css in either the Root or User FF Profiles directory.  I know I’ve looked at that in the past, but there is none now.
> Thank you, aaFn.
> 
> Thank YOU, aaFn!
Rosalie

**Comment by aaFn** [comment] 2021-11-01 18:39
Ok, strange. do you know which version of MacOS you have ? (.. Catalina, BigSur, Monterey ?)
Do you have something activated at OS level for altering colors (like asssistance for color blind people or the like) ?

And for now, I propose to do an experiment:
- Close FF
- Restart it but using the Profile Manager, tp create a fresh new profile (that will keep your existing intact, but the new one will be brand new, no cache, no add-on, no theme, no script .. etc ..)
    - To do that, follow instructions in https://support.mozilla.org/en-US/kb/profile-manager-create-remove-switch-firefox-profiles#w_start-the-profile-manager-when-firefox-is-closed
    - Just make sure you do not check the box to "Use the profile without asking at startup" to avoid looping back on that profile on your next restart
    - Then start FF by pressing the "Start Firefox" button in the Profile Manager
- Once launched, install BSP2 in that profile using the add-ons mgt page  (or use https://addons.mozilla.org/en-US/firefox/addon/bookmark-search-plus-2/ link to do that directly)
- Let me know then if you have the same black lines effect

If no, the problem is with something in your current profile
If yes, the problem is with somethign in the OS or an installed application

At any rate, I re-tested in my Catalina, Big Sur and Monterey VMs, no such effect is happening. So this is not something inherent to the BSP2 code in a standard MacOS + FF install.
Let's see what you get ...

**Comment by Gitoffthelawn** [comment] 2021-11-02 08:38
Possible the OP has system colors enabled in the Firefox `color` preferences.  That can cause dark line issues in various UI areas (not BSP2 specific).  Testing in a new Firefox profile, as @aaFn recommended, will determine if this happens to be the case.

**Comment by aaFn** [comment] 2021-11-02 08:58
And at system level, there is this for example: https://www.imore.com/how-change-your-mac-display-vision-impairments-and-color-blindness

**Comment by Gitoffthelawn** [comment] 2021-11-02 09:00
> And at system level, there is this for example: https://www.imore.com/how-change-your-mac-display-vision-impairments-and-color-blindness

Good point.  And other tools that can do similar things.

**Comment by rdigrego** [comment] 2021-11-03 22:25
I will get back to y'all, likely tomorrow.  Just busy.  Thanks for helping me!

Rosalie

**Comment by rdigrego** [comment] 2021-11-13 16:42
Hello.  Thanks, but I don’t even need glasses at age 70 (just got them checked and donated all glasses).  I haven’t had time to see about a new profile file.  I’ll get back to you ASAP on that score.

Rosalie

**Comment by aaFn** [comment] 2021-12-28 14:50
Hello @rdigrego , assuming the problem is no more here, closing the issue for now, or reopen and let us know if anything new on your side.

Thank you, aaFn.

**Closed by aaFn** 2021-12-28 14:50 UTC
Labels: invalid

**Comment by rdigrego** [comment] 2022-01-02 18:39
I’ll let you know if I find a solution.  I know it was caused by a theme that I later removed.  I probably need to delete the Firefox directory and reinstall the program.

**Comment by rdigrego** [comment] 2022-12-06 23:58
Issue #205 is closed.  The only solution was to reinstall ff…extremely annoying.  So I thought I’d let you know that, though Firefox hasn’t fixed their issue, I have a solution that is annoying, but doesn’t raise the blood pressure.

On a Mac go to Firefox Preferences and then Manage Colors.  
I like to change only the link colors and click on Underline links, but do not click on Use system colors.
Then I either choose Always or Never in the dropdown as to when to override the colors I specified.  
In order to see the links in my chosen colors, I say Always in the dropdown.

Honestly, my only change is the link colors (blue and red, very easy to differentiate for when I visit recipes for Pinterest).

But that makes a few things invisible, such as video controls.  It also screws up Bookmark-search-plus-2, visually, which is why I contacted you.  
So when I don’t need to clearly see link statuses, I just change the dropdown to Never.

It’s easy to see the immediate changes in behavior.  
If you bring up the side panel of Bookmark-search-plus-2 while your are in ff Preferences for “Manage Colors”, you can see how the bookmarks side bar changes as soon as you change the dropdown value and click on OK.  The Overide set on Always causes the thick black lines.

Similarly, bring up two windows side by side, one a video and one the color preferences.  You’ll see immediate changes, again.  Dropdown set to Always screws up video controls; Never value fixes that.

No need to respond.  This is FYI.  I’m sick of the issue and don’t even plan to report it to Mozilla.

Thanks again for looking into the problem.

Enjoy the winter holidays!


Rosalie DeGregory

**Comment by aaFn** [comment] 2022-12-16 22:14
Hello @rdigrego , I checked on my side on Windows, and there is the same effect.
Basically, the "override colors" plays its role, it removes the values decided by the page or the add-on, and replaces them with what you pick.
=> it does what it is supposed to do ... and there is no way for BSP2 to get around it.

Maybe, instead of using this "feature", you should look for a theme which does what you want on the links (visited and non visited), and let's the rest go as defaults ? Or create your own theme .. ?
Then it wouldn't impact BSP2, because the theme would only apply to pages (when those pages do not override the theme of course).

Sorry, I see no other good solution .. "override" is a bit too violent feature.
