### ISSUE TITLE
regression : BSP2 treeview does'nt load in private window

### ISSUE THREAD

**Issue by eseb63** [aaFn/Bookmark-search-plus-2#186] opened 2021-05-05 13:20 UTC
hello,
after updating with last version, the treeview doesnt load anymore in private window : the message "load saved state..." remains pending with waiting cursor and the loading stucks.

if i activate traces, i get:
_In private browsing window
Error on loading from local storage 1 : Error: Type error for parameter keys (Value must either: be a string value, .37 must be a string value, or be an object value) for storage.StorageArea.get._

BSP2 works fine in classic window (Firefox 86.0.1 on windows 7).

thanks in advance for fixing

**Comment by aaFn** [comment] 2021-05-05 17:31
Hi @eseb63 , indeed, a regression introduced by a typo error in code for private windows, introduced by an additional "," which I did not see !

(typical problem with Javascript and all those languages which are not typed, and which non-proficient coders seem to like a lot without any sense of reality : cannot detect such bugs until we run on them... 😢 .. true coders hate those languages for that very reason, because we all know this is a total loss of time, for users and for us, while it could be easily detected at "compilation")

Sorry for the inconvenience, correction will be in 2.0.91, to be out shortly then

**Comment by lbecque** [comment] 2021-05-05 22:06
Ah!  I was wondering if someone would report this.  I noticed the same several days ago.  Now I know its not just me.  Thanks!

**Comment by aaFn** [comment] 2021-05-05 22:22
Done, 2.0.91 is out with the correction. Let me know if any problem.

Thanks both for notifyhing me, aaFn.

**Closed by aaFn** 2021-05-05 22:22 UTC
Labels: bug

**Comment by lbecque** [comment] 2021-05-07 16:21
confirmed 2.0.9.1 fixes this bug.  Thanks for the quick support!
