### ISSUE TITLE
BSP2 uses resources when it's not open?

### ISSUE THREAD

**Issue by ttggzz** [aaFn/Bookmark-search-plus-2#60] opened 2018-10-18 22:17 UTC
Hi, it appears that BSP2 uses resources when it's not open? I had it disabled for 6 weeks, just re-enabled and, with the sidebar closed, noticed everything slowing down. Text lagging when typing, scrolling lagging, ditto on dragging links to regular bookmark sidebar, etc...

Tried emptying cache, and went to about:memory and did the empty garbage routine, no change. Disabled BSP2, everything immediately back to normal.

I should note hovering over "import and backup > restore" in the library shows about 85,000 "items". I use "separators" [and folders] heavily, don't know whether those are part of the item count. When I first installed BSP2 I had a huge session open, maybe 10 windows with hundreds of tabs. Everything ground to a standstill, I ended up having to restart in safe mode and disabling bsp2.
thanks

**Comment by aaFn** [comment] 2018-10-18 23:48
Hello again @ttggzz , yes if you have 85000 booklarks (or more), this can be very long, and the problem is in the FF API,
cf https://bugzilla.mozilla.org/show_bug.cgi?id=1396364

This is why I am trying to not use it except when really necessary, relying on modification notifications and local storageafter the initial load.

There's nothing we can do about it .. this is internal FF code .. until they correct the problem.
You can read in the bug that this is due to SQL select statements and DB structure which are very badly coded / thought, mixing tags and bookmarks in the same table .. ugly ...

When doing the query, one thread in FF is run on that internal API call and can use up a full core in a multicore CPU (which is mostly the case nowadays), hence slowing down many things although not halting them.

It is also true that to accelerate loading and optimize things, I had to split the code into a background task and a sidebar task. See #5 and  #2
There are as many sidebar taks as there are FF windows open, by FF construction, and they run only when open.
There is only one background task, and it runs from start.

That background task is doing the call to the FF API when you press on the "Reload from FF API now" button in options, or when it runs first time, or when it detects by itself that there is a desynchro with the real FF base of bookmarks.

The sidebar tasks are now very lightweight, only taking care of presentation, and not duplicating anything as it was the case in the early days of BSP2.

Given the amount of bookmarks you have (you will see the exact count in the BSP2 Options page when the FF load is finished), the FF API load is very long.

Also, if you disabled and made many changes, then there is the problem of favicons, not made available by FF,
https://bugzilla.mozilla.org/show_bug.cgi?id=1315616
which I have then to reftech from sites directly (note: this is not through Google as this would be a privacy issue).
This is also making things a little jerky for a long time when you have lots of them to catch up with (basically, I am rate lmiting to 5 to 10 fetches per second to keep things from getting resource hungry).

In your case, I would propose - if that is not creating any problem for you -, that you enable BSP2 before going to bed, press the "reload from FF API now" button at that time, leave your computer running, and all should be ok some time later.
And then, I would advise against keeping it disabled when you are doing lots of modifications.

Sorry for that, FF  Web Extension (Quantum) API bugs and limitations do not leave much choices now.
The 2 major plagues are the bookmarks very slow / cpu hunfgry load, and the favicons not made available as cited in the two links above.
One day FF will surely cure them, and things will be much better :-)

**Comment by ttggzz** [comment] 2018-10-18 23:58
Excellent explanation, thank you. I think what I may try doing for now is just enable bsp2 when I need it, as the lag is intolerable. I am just grateful to have a location search feature at all. We corresponded earlier about having the library open in a tab, I have since started using the bookmark sidebar after years of neglect. I am finding it very handy moving stuff around between the library in the tab and the bookmark sidebar right beside it. One benefit is if you move something from the library to the sidebar it doesn't jump to the top, losing your place in perhaps hundreds of tabs you were just scrolling through. When I find a lost item using bsp2 I find I can then proceed as described above and close out the bsp2. 
thanks

**Comment by aaFn** [comment] 2018-10-19 21:51
Ok, good. Note as I said that if you leave BSP2 alone for some time while you go doing something else, the annoyance of lag will only happen once in BSP2 add-on life, until it catches up. After that, all will be smooth at all times. The problem will only come back if you disable BSP2 and make plenty of modification while it is disabled, then re-enable.

Note that by disable and enable, I am talking of the disable/enable button in the add-on panel.
Hiding the sidebar, or showing the native FF bookmark sidebar instead of BSP2, or any other sidebar add-on, is not disabling BSP2, only stopping the sidebar thread. The background thread will continue to catch up any modification done to bookmarks and faithfully reproduce them in its internal cached structure and fast local storage, so that this is seamless and transparent next time you show the BSP2 sidebar again.

**Comment by ttggzz** [comment] 2018-10-20 22:44
ahh, OK I think I might not have caught or fully understood that the first time around, thanks for the follow up. I will give that a try then and let it run overnight or something to load/catch up. Yeah, I had disabled in the add-on panel. I use a 10 year old laptop core 2 duo with 8 GB of ram, I thought maybe it was just too much for the machine, I'll give it another go. thanks!

**Comment by aaFn** [comment] 2018-11-19 00:00
Closing the issue as the question is answered.

Thank you, aaFn.

**Closed by aaFn** 2018-11-19 00:00 UTC
Labels: question
