### ISSUE TITLE
2.0.84 regression in drag & drop handling

### ISSUE THREAD

**Issue by eseb63** [aaFn/Bookmark-search-plus-2#167] opened 2020-12-20 13:52 UTC
after updating BSP2 to 2.0.84, the drag & drop feature from Firefox address bar to BSP2 tree pane stops working (portable Firefox 83) ; it looks like a no-drop protection mistake, as the cursor while dragging shows that dropping is allowed in BSP2 search bar, but not in the treeview (it should be the opposite behavior)
thanks in advance for the fix

**Comment by aaFn** [comment] 2020-12-20 15:10
Hello @eseb63 , indeed, sorry for missing that in my non-regression tests.

This was due to me now changing the visual feedback of the drag & drop to "move", while apparently it is "copy" on address bar drag & drops, and so this is interpreted by the API as "no drop".

I corrected in 2.0.85 which is out now, you can update, I am now changing the visual really only for internal drags to avoid such problem with any other externally initiated drag.

Closing the issue, but let me know and reopen if there is still a glitch.
Thanks, aaFn.

**Closed by aaFn** 2020-12-20 15:10 UTC
Labels: bug
