### ISSUE TITLE
Add a bookmark by drag and drop

### ISSUE THREAD

**Issue by Ehamings** [aaFn/Bookmark-search-plus-2#37] opened 2018-04-29 14:00 UTC
Hi,
In the specification of bookmark-search-plus-2 if i red it right it's mentionned that we can add a bookmark simply by drag and drop the web address.
Obviously, this function don't work for me. Is there a way to make it functional.

**Comment by aaFn** [comment] 2018-04-29 14:14
Hello @Ehamings , like the native bookmark sidebar, there are 3 ways to create bookmarks by drag & drop:

1. When viewing a page you want to bookmark, move your mouse to the (i) at left of the address bar and drag + drop it where you want in the bookmark tree in the sidebar.
2. When viewing a page you want to bookmark, move your mouse pointer to the tab header (the highlighted one) and drag + drop it where you want in the bookmark tree in the sidebar.
3. On a page where three is a link to another page you are interested to bookmark, simply drag + drop the link at the place you want in the bookmark tree in the sidebar.

Let me know if that is not working for you.

**Comment by aaFn** [comment] 2018-05-06 16:35
Closing the issue, as i presume this is answering the question and the function is ok.
Let me know if not.
Thanks, aaFn.

**Closed by aaFn** 2018-05-06 16:35 UTC
Labels: question

**Comment by ttggzz** [comment] 2018-08-30 04:42
Hello, as advised above, when dragging from the left of the address bar or from a link within the page, the bookmark is successfully dropped/shown in the sidebar. However, a dialog box opens and you have to click "add" or "cancel". Is there a way to bypass that/turn the dialog box off? If you "X" out the box without making a choice, the bookmark still stays. Alternatively, dragging from the tab itself the add/cancel box does not open [thankfully].

**Comment by aaFn** [comment] 2018-08-31 21:29
Helllo @ttggzz , all that you describre is correct, and faithfully reproducing the behavior of the native bookmark sidebar, step by step. The intent of BSP2 is to mimick and to remain as close as possible to the native FF bookmark interface and behavior.

**Comment by aaFn** [comment] 2018-09-01 16:14
Hello @ttggzz , so I re-checked, and you are correct, FF changed the default behavior in the native bookmark sidebar. Don't know when ... I will align in 2.0.35, should be out this week-end.

Thanks for the trick on chrome://browser/content/places/places.xul, this is indeed useful. Yes it looks like BSP2 functions well with that page open, which is good .. let me know if you see any problem.

**Comment by aaFn** [comment] 2018-09-03 00:02
Hello @ttggzz , 2.0.35 is out tonight with the new updated behavior. Let me know if any problem.
