### ISSUE TITLE
Please do not steal the input focus

### ISSUE THREAD

**Issue by hungaleida** [aaFn/Bookmark-search-plus-2#67] opened 2018-11-29 19:11 UTC
Thanks for this really useful add-on! Unfortunately the autofocus option at the "Search bookmarks..." input field steals the focus from the URL line.

When the browser is setup to start with an empty page, the expected behavior is to have the input focus at the URL line, so that one can immediately enter an URL or search something on the Internet. With the Bookmark search plus 2 sidebar opened, this is no longer the case. The behavior is unpredictable, as it depends if the sidebar was visible or not when the browser was closed the last time.

I understand that the autofocus might be useful on some use cases, on the above one it's not. I guess the best solution would be to autofocus only when the user manually opens the sidebar (via hotkey or button). But if that's not possible, a setup option to enable or disable the autofocus should do it as well.

**Comment by aaFn** [comment] 2018-11-30 23:20
Hello @hungaleida , strange, ... there is no autofocus possible for an add-on, add-ons cannot steal the focus by themselves, and there is anyway no way to ask for that or to code for that in an add-on (security feature of FF I guess).

Even worse, it is not possible today to get focus on the sidebar when the user manually opens it (cf. https://bugzilla.mozilla.org/show_bug.cgi?id=1502713) !!

I tried myself on a fresh FF61 install under Windows that I had under the hand (I guess this is the same in more recent versions), under the conditions you describe, nothing as what you say is happening:
- I set the option to open on "blank page" (but any other option does not change the behavior, I tried all)
- If I open FF with BSP2 which was open before closing FF, then FF starts with BSP2 open, and the cursor is correctly in the URL address bar, typing characters on keyboard all go to it
- If I open FF with BSP2 which was closed before closing FF, then FF starts with BSP2 closed, and cursor is like the case above, that makes no difference.

So I am unable to reproduce what you explain, and I confirm anyway again it is not possible for an add-on to do that.

I guess some datils could help:
- Which FF version do you have ?
- What other add-ons do you have installed ?
- Which OS version do you have ? (Windows 7, Windows 10, Linux, Mac ?)
- Is that the latest version of BSP2 ? (2.0.42)
- Anything else of interest to mention ?

Thanks, aaFn.

**Comment by hungaleida** [comment] 2018-12-01 02:17
Hi aaFn,

I am using Firefox 60.3.0esr on Debian Jessie with BSP2 2.0.42. I disabled all other add-ons and the issue is still there. Since it only happens with new windows but not with new tabs, I also tried about:newtab as start page, but same issue.

It's definitely the autofocus option as I removed it from the panel.html file of the BSP2 add-on and the issue is gone (fortunately on Firefox ESR it's still possible to install unsigned add-ons):
```
diff -urN bsp2-orig/sidebar/panel.html bsp2-changed/sidebar/panel.html
--- bsp2-orig/sidebar/panel.html        2018-11-24 12:42:32.000000000 +0100
+++ bsp2-changed/sidebar/panel.html     2018-11-29 18:33:09.000000000 +0100
@@ -9,7 +9,7 @@
 <body id="body" class="fontdflt">
   <div id="searchbox">
     <img src="/icons/search.png" id="mglass"/>
-    <input id="searchtext" type="text" placeholder="Search bookmarks.." class="fontdflt" size=1 autofocus>
+    <input id="searchtext" type="text" placeholder="Search bookmarks.." class="fontdflt" size=1>
     <input id="cancelsearch" type="image" src="/icons/empty.png" disabled>
   </div>
   <div id = "searchresult" hidden=true>
@@ -231,4 +231,4 @@
   <script src="panel.js"></script>
 </body>

-</html>
\ Kein Zeilenumbruch am Dateiende.
+</html>
```

Thanks
hungaleida

**Comment by hungaleida** [comment] 2018-12-01 02:36
Just tried the default Firefox start page and it's also affected on ESR 60.

BTW Firefox bug 1502713 does not apply to ESR 60. If I open BSP2 with CTRL+SHIFT+B right now during typing this text, then I have the focus in the search field of BSP2 and can type into it. When pressing CTRL+SHIFT+B again then the focus is back at the github input field and I can continue with typing this text.

It looks to me like the security feature you mentioned was introduced after ESR 60 which also caused bug 1502713.

**Comment by aaFn** [comment] 2018-12-01 11:01
Ah ah, interesting, thank you for the investigation ..!
I could reproduce it indeed on FF 60.3 ESR.

This is not the intended behavior of add-ons and HTML specs ... so it looks to me this is a bug on FF ESR.

I need the autofocus behavior so that when somebody clicks on a non selectable item of the sidebar (e.g. click on the lifts), focus is on the searchtext input field, this is to ease life of users.

And it is in CSS, so it is not possible to deactivate the option depending on FF version or depending on an option.

Therefore, I propose for now to wait for FF to upgrade ESR to a fresher version of the code where this bug is corrected.

Note: I use FF ESR 60.3 at work, and handn't noticed this .. but I have plenty of tabs open and restored when opening FF, I never start on FF by typing a new URL, only when doing new tabs, and there I confirm the problem isn't present. Again thank you for the detailed invesitgation.

**Comment by aaFn** [comment] 2018-12-01 11:04
Note: I tried on FF57, and the problem is not thre, so ESR 60 must be very old in its codebase ... or may have a different codebase ??

Maybe the best would be to open a bug on FF ESR to get that corrected as a security exposure ?

**Comment by aaFn** [comment] 2018-12-08 18:13
I checked, the problem only happens on the ESR 60 in Linux.
Under Windows ESR 60, there is not the problem ...
And FF 63 std on Linux does not have the problem either.

I opened a bug on Bugzilla https://bugzilla.mozilla.org/show_bug.cgi?id=1512818
We should follow there.

Meanwhile, I am closing this issue as the correct behavior if for FF ESR Linux to fix.

Thank you, aaFn.

**Closed by aaFn** 2018-12-08 18:13 UTC

**Comment by hungaleida** [comment] 2018-12-08 20:01
I tested in the meantime a few Firefox versions as well and can confirm that this is something very specific to ESR 60 on Linux and not a general issue with BSP2. As a workaround I use for now my slightly modified version of BSP2 (with autofocus removed) until the ESR line behaves correct.

Thanks for your help with this strange issue, hungaleida

**Comment by aaFn** [comment] 2018-12-09 18:37
For the sake of follow up, here is what  I found in https://bugzilla.mozilla.org/show_bug.cgi?id=1512818

```
the mozregression process bisected it to:
https://hg.mozilla.org/integration/mozilla-inbound/pushloghtml?fromchange=1c52d8baf78986cb9497d48b8b88291686a681ca&tochange=c034e7ddbacdbe80ec8ce5b844e4299fcac9287c

Trace at end of the bisection process:
--------------------------------------
11:57.30 INFO: application_buildid: 20180725225713
11:57.30 INFO: application_changeset: 1c52d8baf78986cb9497d48b8b88291686a681ca
11:57.30 INFO: application_name: Firefox
11:57.30 INFO: application_repository: https://hg.mozilla.org/integration/mozilla-inbound
11:57.30 INFO: application_version: 63.0a1
Was this inbound build good, bad, or broken? (type 'good', 'bad', 'skip', 'retry', 'back' or 'exit' and press Enter): bad
16:45.60 INFO: Narrowed inbound regression window from [081eba54, c034e7dd] (4 builds) to [1c52d8ba, c034e7dd] (2 builds) (~1 steps left)
16:45.60 INFO: No more inbound revisions, bisection finished.
16:45.60 INFO: First good revision: c034e7ddbacdbe80ec8ce5b844e4299fcac9287c
16:45.60 INFO: Last bad revision: 1c52d8baf78986cb9497d48b8b88291686a681ca
16:45.60 INFO: Pushlog:
https://hg.mozilla.org/integration/mozilla-inbound/pushloghtml?fromchange=1c52d8baf78986cb9497d48b8b88291686a681ca&tochange=c034e7ddbacdbe80ec8ce5b844e4299fcac9287c


Looking at the two changes, it is not obvious which one it would be, although
    Bug 1357487 Turn on OOP extensions by default on Linux
is the only one on Linux only as it seems, so would correspond best ...

Also, looking at https://wiki.mozilla.org/Add-ons/QA/Testplan/OOP-WebExtensions, this is indeed related to web extensions .. but hard to guess why running in a different process implies a different behavior on the "autofocus" input field of an add-on.

On Windows, this was activated since FF56 as I get it, which would explain why we observed this only on Linux.
(note on MAC, this is since FF61 apparently).
```

So it looks like the thing who fixes the problem is https://bugzilla.mozilla.org/show_bug.cgi?id=1357487

**Comment by aaFn** [comment] 2018-12-09 21:17
Good, so that looks like the proof of it.
Do you want to update https://bugzilla.mozilla.org/show_bug.cgi?id=1357487 with that info, or prefer me to do it for you ?

**Comment by aaFn** [comment] 2018-12-09 22:41
Never mind I updated the bug on bugzilla.

So it appears that you have a workaround (hoping OOP is not introducing unwanted side effects in ESR 60), until FF decides that ESR will get that either through promoting the fix to it, or through next version (= ESR 68, which should be in July 2019 as per https://www.mozilla.org/en-US/firefox/organizations/).

**Comment by JohnLukeBentley** [comment] 2019-09-11 03:03
I'm coming in here motivated by a desire to have @1ras' suggestion implemented
>  I guess the best solution would be to autofocus [on the "Search Bookmarks"] only when the user manually opens the sidebar (via hotkey or button) ...

... or, I'd add, if FF is restarted with BSP2 open (because it was left open on FF close). 

I agree with @1ras that we otherwise wouldn't want for BSP2 to steal focus. 

> When the browser is setup to start with an empty page, the expected behavior is to have the input focus at the URL line, so that one can immediately enter an URL or search something on the Internet. 

... but I disagree with @1ras that this is a problem with the Bookmark search plus 2 sidebar opened. Rather BSP2 shouldn't steal focus (from the Browser URL/Address textbox) only if BSP2 is closed (and I'm not aware the BSP2 ever did steal focus in this circumstance).

I haven't read all the details above around FF bugs preventing work being done here. 

So two questions (for @aaFn, @1ras and anybody else):
* Would you agree with me that stealing focus is not a problem (indeed it is a feature) when BSP2 is open (and that if BSP2 is open the focus should go to the BSP2 "search bookmarks" textbox)?
* Given the pointed to bug [Turn on OOP extensions by default on Linux](https://bugzilla.mozilla.org/show_bug.cgi?id=1357487) has been fixed, are there any impediments to coding my suggestion?

**Comment by 1ras** [comment] 2019-09-11 09:07
As I understand the issue it should not even be possible for an extension to get the focus. So it's not a feature, it's a Firefox bug which was fixed by enabling extensions.webextensions.remote;true. I am still using it with ESR 60, there are a few rendering glitches but nothing dramatically. But it's anyway just a matter of time till Debian updates to the next ESR release.

The browser should IMHO always behave the same, independent of BSP2 being open or closed, as otherwise you end up with an unpredictable behavior. Unpredictable in the sense that I do not know when starting Firefox if BSP2 was open or closed last time and hence I do not know where the focus ends up now.

**Comment by JohnLukeBentley** [comment] 2019-09-11 12:03
> As I understand the issue it should not even be possible for an extension to get the focus. So it's not a feature, it's a Firefox bug which was fixed by enabling extensions.webextensions.remote;true

Do you mean that, as you understand it, the FF developers have intended that "it should not even be possible for an extension to get the focus"? If that's what you mean then it becomes a matter of changing the FF developer's mind, if they are choosing poorly; or supporting their decision, if they are choosing wisely.

> The browser should IMHO always behave the same, independent of BSP2 being open or closed, as otherwise you end up with an unpredictable behavior. Unpredictable in the sense that I do not know when starting Firefox if BSP2 was open or closed last time and hence I do not know where the focus ends up now.

The BSP2 could be, so long as it wasn't prevented by the extension API (by design or by bug), predictable in the same way the native bookmark sidebar is predictable:
* Opening the native bookmark sidebar (Ctrl+ B on windows) immediately sets focus to the "search bookmarks" textbox; and
* If you close FF with the native bookmark sidebar open then, on ff restart, the sidebar is open but focus is just before the content page (but not on any particular UI element). So tabbing once will move focus to the first focus-able element on the content page (e.g. a link or a button).

>  I do not know when starting Firefox if BSP2 was open or closed last time 

It's incidental but right now you can know, when starting Firefox, if BSP2 was open or closed last time. For the BSP2 will be in the state it was last left: open or closed.

**Comment by 1ras** [comment] 2019-09-11 12:28
> > As I understand the issue it should not even be possible for an extension to get the focus. So it's not a feature, it's a Firefox bug which was fixed by enabling extensions.webextensions.remote;true
> 
> Do you mean that, as you understand it, the FF developers have intended that "it should not even be possible for an extension to get the focus"? If that's what you mean then it becomes a matter of changing the FF developer's mind, if they are choosing poorly; or supporting their decision, if they are choosing wisely.

@aaFn explained it on his very first comment.

> > The browser should IMHO always behave the same, independent of BSP2 being open or closed, as otherwise you end up with an unpredictable behavior. Unpredictable in the sense that I do not know when starting Firefox if BSP2 was open or closed last time and hence I do not know where the focus ends up now.
> 
> The BSP2 could be, so long as it wasn't prevented by the extension API (by design or by bug), predictable in the same way the native bookmark sidebar is predictable:
> 
>     * Opening the native bookmark sidebar (Ctrl+ B on windows) immediately sets focus to the "search bookmarks" textbox; and
> 
>     * If you close FF with the native bookmark sidebar open then, on ff restart, the sidebar is open but focus is just before the content page (but not on any particular UI element). So tabbing once will move focus to the first focus-able element on the content page (e.g. a link or a button).

If Firefox is configured to start with a blank page, then the focus is at the address bar and you can immediately type an URL or search keyword. I am basically blindly starting to type something when I start Firefox and go crazy if the focus is wrong.

> > I do not know when starting Firefox if BSP2 was open or closed last time
> 
> It's incidental but right now you can know, when starting Firefox, if BSP2 was open or closed last time. For the BSP2 will be in the state it was last left: open or closed.

It's not that easy as you can have multiple Firefox windows open but only when you close the last one the state of the sidebar is preserved.

**Comment by aaFn** [comment] 2019-09-11 13:02
As a reminder, here is what we are waiting for from FF: https://bugzilla.mozilla.org/show_bug.cgi?id=1502713

Which is to get focus when the sidebar is open by keyboard shortcut or by the action button in the toolbar.
