### ISSUE TITLE
Text and bg colors do not match Firefox's

### ISSUE THREAD

**Issue by rafawendel** [aaFn/Bookmark-search-plus-2#242] opened 2022-05-29 23:37 UTC
Theoretically the theme colors should use Firefox theming, but this doesn't happen despite checking the option to align it (which is the default state), at least for the FF's auto theme option.

**Comment by aaFn** [comment] 2022-05-30 06:58
Hello @rafawendel , go into Options of BSP2, and activate the option to align with FF theme colors.
Or you can customize there as you want.

**Comment by rafawendel** [comment] 2022-05-30 11:38
Oh, I'm posting this issue exactly because it won't match FF _despite_ me checking that option. Setting up a theme manually does work, but it'd be great to just have native color matching.

**Comment by aaFn** [comment] 2022-06-01 21:56
Well, all is working here, since long and still with FF 101.
Which Firefox version are you using, which OS ? Are you sure there is no interference because of other add-ons / themes ?
Best is to restart FF momentarily with a blank new profile, to verify that there is nothing interfering.

**Comment by rafawendel** [comment] 2022-06-03 01:01
MacOS BigSur, FF 101. My theme is `System theme - auto`, the one which enables auto dark mode. I think that might be the cause. I issued because I don't think it _should_ be.

**Comment by rafawendel** [comment] 2022-06-03 01:07
Just verified it: it works with some themes. I suppose the color it points to is not quite the same color, say, FF uses for it's own Bookmarks sidebar, because some themes (Dark Dracula, Dark) change its colors, whereas others just give me a standard white. I can notice subtle changes to FF's own bookmarks panel which are not mimicked by the extension.

**Comment by aaFn** [comment] 2022-06-06 22:18
Ok. BSP2 receives those colors from FF, and does not have any other information.
Cannot tell why native Bookmarks do not respect them, but BSP2 is not able to see that, no other information than what is given by the FF API is visible o BSP2.

**Comment by aaFn** [comment] 2022-06-07 07:25
Fyi, if ou are interested, I am using sidebar_text for text color, and sidebar for background color, from https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/theme#colors, as indicated by tge picture at top, and by the detailed description in the table below.

**Comment by rafawendel** [comment] 2022-06-07 20:42
Were you able to reproduce it?

**Comment by aaFn** [comment] 2022-06-08 05:13
I could not reproduce it on Windows nor Linux.
However, I can observe that on MacOS, yes, BSP2 gets a full white (like in Windows and Linux btw on the same "auto" theme), while the native FF bookmark sidebar shows a light grey => I can only conclude that FF doesn't respect its own theme, or has internally more parameters than what is made available on the FF API.

**Comment by aaFn** [comment] 2022-06-30 14:28
Closing as that seems to be a FF specific behavior on MacOS

**Closed by aaFn** 2022-06-30 14:28 UTC
Labels: cannot reproduce or invalid
