### ISSUE TITLE
Adding Underscores to Underline Access Keys, in Context Menu - Enhancement Suggestion

### ISSUE THREAD

**Issue by Cr8zyIvan** [aaFn/Bookmark-search-plus-2#280] opened 2023-08-15 16:42 UTC
A simple modification to show which Letters on the Keyboard corresponds to which Context Menu item (with the corresponding Underscored Letter) would go a long way.

Eg: 
- Bookmark Tab Here 🡲 H
- New Folder... 🡲 F
- Cut 🡲 t
- etc.

And I'm sorry if people are sick of reading it, but I have to say it, I'm still pretty amazed at Bookmark search plus 2

**Comment by aaFn** [comment] 2023-08-19 17:53
Hello @Cr8zyIvan , thank you.
Well, this is already the case when you run Firefox >= 64, see below
![image](https://github.com/aaFn/Bookmark-search-plus-2/assets/36155054/661a8b7b-ba02-4820-99f0-dba9148086c0)

Which version of Firefox are you running ?

**Comment by Cr8zyIvan** [comment] 2023-10-04 12:17
Oh my god, I'm so sorry I didn't respond to your message. I sometimes Space out and forget to come back to stuff. I apologize for letting this one drift off for so long.

To answer the question:
Yes, your understanding is spot on.
I'm running Firefox Version: 118.0.1 (64-bit)

I took two screenshots of the Context menu. I usually have a Red Theme Installed and thought that might be the cause of me not seeing the Underlines, but I reverted to no Themes Enabled to see if it would change, but it's the same. I'm stumped why I'm not seeing them. I do use a fair number of other Extensions. I'm thinking perhaps they are conflicting with BSP2's Context Menu??

![image](https://github.com/aaFn/Bookmark-search-plus-2/assets/32711839/f2ff147d-1ae6-4d26-beb1-264c009669e5)![image](https://github.com/aaFn/Bookmark-search-plus-2/assets/32711839/457741ec-0e6f-441f-a2ec-138e372a344b)

**Comment by aaFn** [comment] 2023-10-06 06:40
Indeed, strange.

As said, I use the FF API and its native context menu, which allows by the way another of your extensions to add its own menu on BSP2, like "Open Bookmark in Container Tab" that we can see on your screenshots.
And I do tell FF to show which character to underline, as being the keyboard accelerator.

See "title" on https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/menus/create,and the part on "& in title sets access key" in the Browser compatibility table, which tells this is supported since FF63.
(see also https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/user_interface/Context_menu_items for an overview).

Do at least the shortcut keys work, even if not visible ? Or not at all ?

I do not know of a case where this does not work .. unless maybe if you are using an older OS like Windows 7 or older, as I know that not all functions are fully implemented on such old Os'es
=> can you confirm on which OS you are running ?

Of course, interaction from another add-on is not to rule out, but that seems unlikely at this stage, or from what I can see.
Do you have similar symptoms on other add-ons which have their own menus (if you have one or some of them) ? Or on the native FF bookmark sidebar ?

**Comment by aaFn** [comment] 2023-11-01 17:06
Hello, see this link, maybe this is explaining / the cause of your problem ?
https://www.tenforums.com/tutorials/97413-turn-off-underline-access-key-shortcuts-menus-windows-10-a.html

**Comment by aaFn** [comment] 2023-11-05 19:05
**Update:** I found a configuration parameter in FF reproducing what you describe = if you set `ui.key.menuAccessKey` to `0` in about;config, then all underlines of access keys do not show up in context menus.

Cf. https://www.reddit.com/r/firefox/comments/tktfyq/comment/i1siv7p/

Can you check whether this is not your problem ?
Default value is `18`.

As I cannot find any other factor explaining this, and since the function is already there in BSP2, and nothing more can be done in BSP2,
and since there is high probbailiy that this is an external factor / configuration problem,
I am closing the issue, - hoping that the configuration parameter I just found is your cause and that you will be able to come back to the default behavior.

Thank you, aaFn.

**Closed by aaFn** 2023-11-05 19:05 UTC
Labels: question

**Comment by Cr8zyIvan** [comment] 2024-03-26 22:12
I now fully understand why I had this problem initially. Because I want Firefox's Alt Menu disabled (the "Alt + F", "Alt + E", etc.), the "ui.key.menuAccessKey" flag must be set to 0. And at the same time, this flag disables the display of the Underline Access Keys in menus.

I have a massive list of custom personalized Hotkeys that I use with every program that I run and Firefox's Alt Menu Hotkeys screws that up.

Being stuck between a rock and a hard place, for now I am choosing to put it at 0, where the Alt Menu is disabled, and BSP2 "Menu's Underscores" will be absent. I have a pretty good handle on what most of them are. I think I'll be good.

Cheers!
