### ISSUE TITLE
Edge Browser capability Request

### ISSUE THREAD

**Issue by Andre-ADPC** [aaFn/Bookmark-search-plus-2#236] opened 2022-04-13 13:27 UTC
Good day, all.
I have been using your add-on for a couple of months and it is the only one of many I have tried over the years that is clean, simple to use and FUNCTIONAL! Thank you!

However, FFox is a hog on resources. I find that Edge is vastly snappier and more responsive compared to FFox in certain cases. I use both FFox and Edge in dev mode and collect quite a lot of research articles during my workflow, and it is quick to search for the most relevant folder, then drag-n-drop the page link into the desired folder. 

BMSP2 has been **invaluable** to me because of its browser coupled mode, search, and drag-and-drop functionality when it comes to managing complex bookmark folder structures. 

Is it possible to easily convert the code for/or is it under consideration to branch it out to support Edge 100^ as well?
I came up empty-handed after three hours of trying to find a suitable alternative for Edge, so decided to come here and ask.

Thanks again for your efforts and time invested in this repo!

**Comment by Gitoffthelawn** [comment] 2022-04-13 16:06
@Andre-ADPC Hi Andre.  As you await @aaFn's response, if you have specific reproducible examples of cases where Edge is vastly snappier/faster than Firefox, I encourage you to post an issue on https://bugzilla.mozilla.org/

BTW, I know the following isn't a popular thing to say, but I find uBlock Origin (uBO) really makes Firefox feel slower.  So if you're using that extension too, you might want to try disabling it or uninstalling it for some tests.  That said, I think the speed tradeoff is worth it due to the functionality uBO provides.

**Comment by aaFn** [comment] 2022-04-13 21:55
Hello @Andre-ADPC , indeed, to compare things, as @Gitoffthelawn says, you need to disable plugins. E.g. I use NoScript which I find useful because I am a bit paranoid like any developer, however, when I disable it, I find FF a bit faster, even though NoScript is quite light on usage.

On the question of BSP2 working in Edge : I am pretty sure there are parts of the code which wouldn't fit as I had to make some workarounds for FF. So these would need to be set apart. Not to say that FF is worse than others .. my (long) experience with Microsoft products tell me I will find plenty, let's say equal if not more, of limitations, bugs, wrong logics in Edge also (e.g. Outlook is a pain since years, the Win32 interface is illogical in many places .. etc ...).
And so, specific workarounds to add as well

TBH, I am not sure it is easy to convert to Edge .. For sure, the first port I will try one day will be for Chrome, as it is close to FF. Once I get experience on that, I guess Edge could be the next one, but this is not for tomorrow ... sorry.

**Comment by aaFn** [comment] 2022-05-08 23:24
Closing for now. Thanks, aaFn.

**Closed by aaFn** 2022-05-08 23:24 UTC
Labels: for later consideration

**Comment by Andre-ADPC** [comment] 2022-06-21 17:08
Thank you for the guidance and opinions @aaFn  and @Gitoffthelawn. When I do the comparisons I make sure to use the same (minimal) add-ons/extensions. I'm not sure if they behave significantly different regarding the use of resources, but with exactly the same tab-group open in both and running the same extensions, I don't get the same result regarding resource consumption nor browsing Laravel's documentation for example in FF. It seems to get stuck and then react a second or so later when scrolling for example. Maybe there are settings I'm not aware that might be affecting the expereince, not sure. I love FF, especially the Dev version. Edge Dev is not quite as stable as it could be. 

Trying to wade through dev docs and solving your code issues is a major task already. Having to trouble-shoot a browser on top of it, is a PITA.

I will get back to it as some time and tripple-check all the settings in them again. In the meanwhile, thanks for a great extension aaFn! Keep up the great work there! Thanks.
